# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.median
# source_yaml_count=6
# source_api_txt=/root/api_txt/torch.median.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape(fdp, min_rank=0, max_rank=4, min_dim=0, max_dim=8, allow_scalar=True):
    if allow_scalar:
        rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    else:
        rank = fdp.ConsumeIntInRange(max(min_rank, 1), max_rank)
    if rank == 0:
        return ()
    return tuple(fdp.ConsumeIntInRange(min_dim, max_dim) for _ in range(rank))


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, shape, dtype):
    total = _numel(shape)
    if total == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 1:
        vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 2:
        base = fdp.ConsumeIntInRange(-5, 5)
        step = fdp.ConsumeIntInRange(-3, 3)
        vals = [float(base + i * step) for i in range(total)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 3:
        vals = [float(fdp.ConsumeIntInRange(-2, 2)) for _ in range(total)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 4:
        vals = fdp.ConsumeRegularFloatList(total)
        if total > 0:
            dup = vals[0] if vals else 0.0
            for i in range(0, total, 2):
                vals[i] = dup
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    fill = fdp.ConsumeFloatInRange(-100.0, 100.0)
    return torch.full(shape, fill_value=fill, dtype=dtype)


def _make_named_tensor_1d(fdp, dtype):
    n = fdp.ConsumeIntInRange(0, 8)
    t = _make_tensor(fdp, (n,), dtype)
    name = fdp.PickValueInList(["N", "batch", "dim0", "x"])
    try:
        return t.refine_names(name), name
    except Exception:
        return t, None


def _reduction_output_shape(shape, dim, keepdim):
    ndim = len(shape)
    if ndim == 0:
        return ()
    if dim < 0:
        dim += ndim
    if keepdim:
        out = list(shape)
        out[dim] = 1
        return tuple(out)
    return tuple(shape[i] for i in range(ndim) if i != dim)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        branch = fdp.ConsumeIntInRange(0, 5)

        if branch == 0:
            dtype = _pick_dtype(fdp)
            shape = _consume_shape(fdp, min_rank=0, max_rank=4, min_dim=0, max_dim=8, allow_scalar=True)
            t = _make_tensor(fdp, shape, dtype)
            torch.median(t)

        elif branch == 1:
            dtype = _pick_dtype(fdp)
            rank = fdp.ConsumeIntInRange(1, 4)
            shape = tuple(fdp.ConsumeIntInRange(0, 8) for _ in range(rank))
            t = _make_tensor(fdp, shape, dtype)
            if rank > 0:
                if fdp.ConsumeBool():
                    dim = fdp.ConsumeIntInRange(-rank, rank - 1)
                else:
                    dim = fdp.ConsumeIntInRange(-4, 4)
                keepdim = fdp.ConsumeBool()
                if fdp.ConsumeBool():
                    torch.median(t, dim, keepdim)
                else:
                    torch.median(input=t, dim=dim, keepdim=keepdim)

        elif branch == 2:
            dtype = _pick_dtype(fdp)
            rank = 2
            shape = tuple(fdp.ConsumeIntInRange(0, 8) for _ in range(rank))
            t = _make_tensor(fdp, shape, dtype)
            dim = fdp.ConsumeIntInRange(-2, 1)
            keepdim = fdp.ConsumeBool()
            out_shape = _reduction_output_shape(shape, dim, keepdim)
            values = torch.empty(out_shape, dtype=dtype)
            indices = torch.empty(out_shape, dtype=torch.int64)
            if fdp.ConsumeBool():
                torch.median(t, dim, keepdim, out=(values, indices))
            else:
                torch.median(input=t, dim=dim, keepdim=keepdim, out=(values, indices))

        elif branch == 3:
            dtype = _pick_dtype(fdp)
            t, name = _make_named_tensor_1d(fdp, dtype)
            keepdim = fdp.ConsumeBool()
            dim_name = name if (name is not None and fdp.ConsumeBool()) else fdp.PickValueInList(
                ["", "N", "batch", "dim0", "x", "invalid"]
            )
            if fdp.ConsumeBool():
                torch.median(t, dim_name, keepdim)
            else:
                torch.median(input=t, dim=dim_name, keepdim=keepdim)

        elif branch == 4:
            dtype = _pick_dtype(fdp)
            n = fdp.ConsumeIntInRange(1, 8)
            t = _make_tensor(fdp, (n,), dtype)
            out = torch.empty((), dtype=dtype)
            if fdp.ConsumeBool():
                torch.median(t, out=out)
            else:
                torch.median(input=t, out=out)

        else:
            dtype = _pick_dtype(fdp)
            rank = fdp.ConsumeIntInRange(1, 4)
            shape = tuple(fdp.ConsumeIntInRange(1, 8) for _ in range(rank))
            t = _make_tensor(fdp, shape, dtype)
            valid_dim = fdp.ConsumeIntInRange(-rank, rank - 1)
            keepdim = fdp.ConsumeBool()

            torch.median(t)
            torch.median(t, valid_dim, keepdim)

            if rank == 1:
                out_scalar = torch.empty((), dtype=dtype)
                torch.median(t, out=out_scalar)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
