# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.load
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.load.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import io
import os
import pickle
import tempfile

import torch


def _safe_name(s: str) -> str:
    if not s:
        return "f"
    out = []
    for ch in s:
        if ch.isalnum() or ch in ("_", "-", "."):
            out.append(ch)
        else:
            out.append("_")
    name = "".join(out).strip(" .")
    return name or "f"


def _consume_small_string(fdp: atheris.FuzzedDataProvider, max_len: int = 16) -> str:
    return fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, max_len))


def _make_tensor(fdp: atheris.FuzzedDataProvider):
    dtype = fdp.PickValueInList(
        [
            torch.float32,
            torch.float64,
            torch.float16,
            torch.int64,
            torch.int32,
            torch.int16,
            torch.int8,
            torch.uint8,
            torch.bool,
        ]
    )
    rank = fdp.ConsumeIntInRange(0, 4)
    shape = [fdp.ConsumeIntInRange(0, 4) for _ in range(rank)]
    numel = 1
    for d in shape:
        numel *= d
    if rank == 0:
        numel = 1

    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(numel)]
    elif dtype.is_floating_point:
        vals = [fdp.ConsumeFloatInRange(-100.0, 100.0) for _ in range(numel)]
    else:
        vals = [fdp.ConsumeIntInRange(-100, 100) for _ in range(numel)]

    t = torch.tensor(vals, dtype=dtype)
    if rank > 0:
        t = t.reshape(shape)
    else:
        t = t.reshape(())
    return t


def _make_object(fdp: atheris.FuzzedDataProvider, depth: int = 0):
    if depth > 2:
        leaf_kind = fdp.ConsumeIntInRange(0, 5)
    else:
        leaf_kind = fdp.ConsumeIntInRange(0, 9)

    if leaf_kind == 0:
        return None
    if leaf_kind == 1:
        return fdp.ConsumeBool()
    if leaf_kind == 2:
        return fdp.ConsumeIntInRange(-100000, 100000)
    if leaf_kind == 3:
        return fdp.ConsumeFloatInRange(-1e5, 1e5)
    if leaf_kind == 4:
        return _consume_small_string(fdp, 24)
    if leaf_kind == 5:
        return fdp.ConsumeBytes(fdp.ConsumeIntInRange(0, 32))
    if leaf_kind == 6:
        return _make_tensor(fdp)
    if leaf_kind == 7:
        length = fdp.ConsumeIntInRange(0, 4)
        return [_make_object(fdp, depth + 1) for _ in range(length)]
    if leaf_kind == 8:
        length = fdp.ConsumeIntInRange(0, 4)
        return tuple(_make_object(fdp, depth + 1) for _ in range(length))

    length = fdp.ConsumeIntInRange(0, 4)
    d = {}
    for _ in range(length):
        kkind = fdp.ConsumeIntInRange(0, 3)
        if kkind == 0:
            key = _consume_small_string(fdp, 12)
        elif kkind == 1:
            key = fdp.ConsumeIntInRange(-32, 32)
        elif kkind == 2:
            key = fdp.ConsumeBool()
        else:
            key = fdp.ConsumeBytes(fdp.ConsumeIntInRange(0, 8))
        d[key] = _make_object(fdp, depth + 1)
    return d


def _map_location_identity(storage, loc):
    return storage


def _make_map_location(fdp: atheris.FuzzedDataProvider):
    choice = fdp.ConsumeIntInRange(0, 5)
    if choice == 0:
        return None
    if choice == 1:
        return "cpu"
    if choice == 2:
        return torch.device("cpu")
    if choice == 3:
        return {"cpu": "cpu"}
    if choice == 4:
        return _map_location_identity
    return {fdp.PickValueInList(["cpu", "cuda:0", "cuda:1"]): "cpu"}


def _make_pickle_module(fdp: atheris.FuzzedDataProvider):
    if fdp.ConsumeBool():
        return None
    return pickle


def _make_pickle_load_args(fdp: atheris.FuzzedDataProvider):
    kwargs = {}
    if fdp.ConsumeBool():
        kwargs["encoding"] = fdp.PickValueInList(["utf-8", "ascii", "latin1", "bytes"])
    if fdp.ConsumeBool():
        kwargs["errors"] = fdp.PickValueInList(["strict", "ignore", "replace"])
    return kwargs


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        obj = _make_object(fdp)
        use_path = fdp.ConsumeBool()
        map_location = _make_map_location(fdp)
        pickle_module = _make_pickle_module(fdp)

        weights_only_choice = fdp.ConsumeIntInRange(0, 2)
        if weights_only_choice == 0:
            weights_only = None
        elif weights_only_choice == 1:
            weights_only = True
        else:
            weights_only = False

        mmap_choice = fdp.ConsumeIntInRange(0, 2)
        if mmap_choice == 0:
            mmap = None
        elif mmap_choice == 1:
            mmap = True
        else:
            mmap = False

        pickle_load_args = _make_pickle_load_args(fdp)

        with tempfile.TemporaryDirectory() as tmpdir:
            filename = _safe_name(_consume_small_string(fdp, 16)) + ".pt"
            path = os.path.join(tmpdir, filename)

            torch.save(obj, path, pickle_module=pickle_module or pickle)

            if use_path:
                f_arg = path
            else:
                with open(path, "rb") as rf:
                    f_arg = io.BytesIO(rf.read())

            call_mode = fdp.ConsumeIntInRange(0, 3)
            if call_mode == 0:
                torch.load(
                    f_arg,
                    map_location=map_location,
                    pickle_module=pickle_module,
                    weights_only=weights_only,
                    mmap=mmap,
                    **pickle_load_args
                )
            elif call_mode == 1:
                torch.load(
                    f=f_arg,
                    map_location=map_location,
                    pickle_module=pickle_module,
                    weights_only=weights_only,
                    mmap=mmap,
                    **pickle_load_args
                )
            elif call_mode == 2:
                if mmap is None:
                    torch.load(
                        f_arg,
                        map_location=map_location,
                        pickle_module=pickle_module,
                        weights_only=weights_only,
                        **pickle_load_args
                    )
                else:
                    torch.load(
                        f_arg,
                        map_location=map_location,
                        pickle_module=pickle_module,
                        weights_only=weights_only,
                        mmap=mmap,
                        **pickle_load_args
                    )
            else:
                kwargs = {}
                if fdp.ConsumeBool():
                    kwargs["map_location"] = map_location
                if fdp.ConsumeBool():
                    kwargs["pickle_module"] = pickle_module
                if fdp.ConsumeBool():
                    kwargs["weights_only"] = weights_only
                if fdp.ConsumeBool():
                    kwargs["mmap"] = mmap
                kwargs.update(pickle_load_args)
                torch.load(f_arg, **kwargs)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
