# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.conv_transpose3d
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.functional.conv_transpose3d.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _small_dim(fdp, min_v=1, max_v=6):
    return fdp.ConsumeIntInRange(min_v, max_v)


def _kernel_dim(fdp):
    return fdp.ConsumeIntInRange(1, 5)


def _make_tuple3_or_int(fdp, allow_zero=False, allow_large=False, special_for_output_padding=False):
    if special_for_output_padding:
        vals = [0, 1, 2]
    else:
        if allow_zero:
            vals = [0, 1, 2, 3]
        else:
            vals = [1, 2, 3]
        if allow_large:
            vals.append(4)

    if fdp.ConsumeBool():
        return fdp.PickValueInList(vals)
    return (
        fdp.PickValueInList(vals),
        fdp.PickValueInList(vals),
        fdp.PickValueInList(vals),
    )


def _expand3(v):
    if isinstance(v, int):
        return (v, v, v)
    return tuple(v)


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype):
    count = _numel(shape)
    if count == 0:
        return torch.empty(shape, dtype=dtype)
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(count, -2.0, 2.0)
    elif mode == 1:
        vals = fdp.ConsumeRegularFloatList(count)
    elif mode == 2:
        vals = [0.0] * count
    elif mode == 3:
        vals = [fdp.ConsumeFloatInRange(-0.1, 0.1) for _ in range(count)]
    else:
        vals = [float((i % 7) - 3) for i in range(count)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _choose_groups_and_channels(fdp):
    groups = fdp.ConsumeIntInRange(1, 4)
    cin_per_group = fdp.ConsumeIntInRange(1, 4)
    cout_per_group = fdp.ConsumeIntInRange(1, 4)
    c_in = groups * cin_per_group
    c_out = groups * cout_per_group
    return groups, c_in, c_out


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)

        n = _small_dim(fdp, 1, 3)
        groups, c_in, c_out = _choose_groups_and_channels(fdp)

        d = _small_dim(fdp, 1, 6)
        h = _small_dim(fdp, 1, 6)
        w = _small_dim(fdp, 1, 6)

        k_d = _kernel_dim(fdp)
        k_h = _kernel_dim(fdp)
        k_w = _kernel_dim(fdp)

        input_shape = (n, c_in, d, h, w)
        weight_shape = (c_in, c_out // groups, k_d, k_h, k_w)

        x = _make_tensor(fdp, input_shape, dtype)
        weight = _make_tensor(fdp, weight_shape, dtype)

        use_bias = fdp.ConsumeBool()
        bias = _make_tensor(fdp, (c_out,), dtype) if use_bias else None

        stride = _make_tuple3_or_int(fdp, allow_zero=False)
        dilation = _make_tuple3_or_int(fdp, allow_zero=False)
        stride_t = _expand3(stride)
        dilation_t = _expand3(dilation)

        max_pad = max(0, dilation_t[0] * (k_d - 1))
        max_pah = max(0, dilation_t[1] * (k_h - 1))
        max_paw = max(0, dilation_t[2] * (k_w - 1))

        if fdp.ConsumeBool():
            pad_d = fdp.ConsumeIntInRange(0, min(max_pad, 4))
            pad_h = fdp.ConsumeIntInRange(0, min(max_pah, 4))
            pad_w = fdp.ConsumeIntInRange(0, min(max_paw, 4))
            if fdp.ConsumeBool() and pad_d == pad_h == pad_w:
                padding = pad_d
            else:
                padding = (pad_d, pad_h, pad_w)
        else:
            padding = fdp.PickValueInList([0, 1, (0, 0, 0), (1, 1, 1)])

        padding_t = _expand3(padding)

        op_d_max = max(0, stride_t[0] - 1)
        op_h_max = max(0, stride_t[1] - 1)
        op_w_max = max(0, stride_t[2] - 1)

        out_pad_d = fdp.ConsumeIntInRange(0, min(op_d_max, 3))
        out_pad_h = fdp.ConsumeIntInRange(0, min(op_h_max, 3))
        out_pad_w = fdp.ConsumeIntInRange(0, min(op_w_max, 3))

        if fdp.ConsumeBool() and out_pad_d == out_pad_h == out_pad_w:
            output_padding = out_pad_d
        else:
            output_padding = (out_pad_d, out_pad_h, out_pad_w)

        call_mode = fdp.ConsumeIntInRange(0, 2)
        if call_mode == 0:
            y = F.conv_transpose3d(
                x,
                weight,
                bias,
                stride,
                padding,
                output_padding,
                groups,
                dilation,
            )
        elif call_mode == 1:
            y = F.conv_transpose3d(
                input=x,
                weight=weight,
                bias=bias,
                stride=stride,
                padding=padding,
                output_padding=output_padding,
                groups=groups,
                dilation=dilation,
            )
        else:
            y = F.conv_transpose3d(
                x,
                weight,
                bias=bias,
                stride=stride,
                padding=padding,
                output_padding=output_padding,
                groups=groups,
                dilation=dilation,
            )

        if fdp.ConsumeBool():
            _ = y.shape
        if fdp.ConsumeBool():
            _ = y.numel()
        if fdp.ConsumeBool():
            _ = y.sum()
        if fdp.ConsumeBool():
            _ = y.contiguous()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
