# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.quantization.convert
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.quantization.convert.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import copy
import torch
import torch.nn as nn
import torch.quantization as tq


class CustomObserved(nn.Module):
    def __init__(self, out_features=4):
        super().__init__()
        self.scale = 1.0
        self.zero_point = 0
        self.out_features = out_features

    def forward(self, x):
        return x

    def calculate_qparams(self):
        return torch.tensor([self.scale]), torch.tensor([self.zero_point], dtype=torch.int64)


class CustomQuantized(nn.Module):
    def __init__(self, out_features=4):
        super().__init__()
        self.out_features = out_features

    @classmethod
    def from_observed(cls, mod):
        out_features = getattr(mod, "out_features", 4)
        return cls(out_features=out_features)

    def forward(self, x):
        return x


class SmallModel(nn.Module):
    def __init__(self, fdp):
        super().__init__()
        in_ch = fdp.ConsumeIntInRange(1, 4)
        conv_out = fdp.ConsumeIntInRange(1, 4)
        lin_out = fdp.ConsumeIntInRange(1, 8)
        k = fdp.PickValueInList([1, 3])
        use_bn = fdp.ConsumeBool()
        use_relu = fdp.ConsumeBool()
        use_custom = fdp.ConsumeBool()
        self.quant = tq.QuantStub()
        self.conv = nn.Conv2d(in_ch, conv_out, kernel_size=k, stride=1, padding=k // 2)
        self.bn = nn.BatchNorm2d(conv_out) if use_bn else nn.Identity()
        self.relu = nn.ReLU() if use_relu else nn.Identity()
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(conv_out, lin_out)
        self.dequant = tq.DeQuantStub()
        self.custom = CustomObserved(lin_out) if use_custom else nn.Identity()

    def forward(self, x):
        x = self.quant(x)
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        x = self.pool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        x = self.custom(x)
        x = self.dequant(x)
        return x


def _set_qconfig_recursive(module, qconfig):
    for child in module.modules():
        child.qconfig = qconfig


def _maybe_fuse(model, fdp):
    if not fdp.ConsumeBool():
        return model
    fusion_candidates = []
    if isinstance(model.bn, nn.BatchNorm2d) and isinstance(model.relu, nn.ReLU):
        fusion_candidates.append(["conv", "bn", "relu"])
    elif isinstance(model.bn, nn.BatchNorm2d):
        fusion_candidates.append(["conv", "bn"])
    elif isinstance(model.relu, nn.ReLU):
        fusion_candidates.append(["conv", "relu"])
    if not fusion_candidates:
        return model
    try:
        return tq.fuse_modules(model, fusion_candidates, inplace=False)
    except Exception:
        return model


def _prepare_module(model, example, fdp):
    qconfig_name = fdp.PickValueInList(["fbgemm", "qnnpack", "default"])
    if qconfig_name == "default":
        qconfig = tq.default_qconfig
    else:
        qconfig = tq.get_default_qconfig(qconfig_name)
    _set_qconfig_recursive(model, qconfig)

    if fdp.ConsumeBool():
        prepared = tq.prepare(model, inplace=False)
    else:
        prepared = tq.prepare_qat(model, inplace=False)

    runs = fdp.ConsumeIntInRange(1, 3)
    prepared.eval()
    for _ in range(runs):
        prepared(example)
    return prepared


def _make_example_input(fdp, model):
    in_ch = model.conv.in_channels
    n = fdp.ConsumeIntInRange(1, 3)
    h = fdp.ConsumeIntInRange(1, 8)
    w = fdp.ConsumeIntInRange(1, 8)
    total = n * in_ch * h * w
    vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
    x = torch.tensor(vals, dtype=torch.float32).reshape(n, in_ch, h, w)
    return x


def _make_mapping(fdp):
    if not fdp.ConsumeBool():
        return None
    mappings = [
        {},
        dict(tq.get_default_static_quant_module_mappings()),
        dict(tq.get_default_qat_module_mappings()),
    ]
    mapping = fdp.PickValueInList(mappings)
    if fdp.ConsumeBool():
        mapping = dict(mapping)
        mapping[CustomObserved] = CustomQuantized
    return mapping


def _make_convert_custom_config_dict(fdp):
    if not fdp.ConsumeBool():
        return None
    cfg = {}
    if fdp.ConsumeBool():
        cfg["observed_to_quantized_custom_module_class"] = {
            CustomObserved: CustomQuantized
        }
    if fdp.ConsumeBool():
        cfg["non_traceable_module_class"] = [CustomObserved]
    return cfg


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        model = SmallModel(fdp)
        if fdp.ConsumeBool():
            model.train()
        else:
            model.eval()

        model = _maybe_fuse(model, fdp)
        example = _make_example_input(fdp, model)
        prepared = _prepare_module(model, example, fdp)

        mapping = _make_mapping(fdp)
        convert_custom_config_dict = _make_convert_custom_config_dict(fdp)

        call_style = fdp.ConsumeIntInRange(0, 2)

        if call_style == 0:
            torch.quantization.convert(prepared)
        elif call_style == 1:
            torch.quantization.convert(
                prepared,
                mapping=mapping,
                inplace=False,
                remove_qconfig=True,
                is_reference=False,
                convert_custom_config_dict=convert_custom_config_dict,
                use_precomputed_fake_quant=False,
            )
        else:
            prepared_copy = copy.deepcopy(prepared)
            torch.quantization.convert(
                prepared_copy,
                mapping,
                False,
                True,
                False,
                convert_custom_config_dict,
                False,
            )
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
