# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.quantization.propagate_qconfig_
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.quantization.propagate_qconfig_.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import copy

import torch
import torch.nn as nn

try:
    import torch.ao.quantization as ao_quantization
except Exception:
    ao_quantization = None


def _pick_dtype(fdp):
    return fdp.PickValueInList(
        [
            torch.float32,
            torch.float64,
            torch.float16,
        ]
    )


def _small_shape(fdp, min_rank=0, max_rank=3, min_dim=1, max_dim=4):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    return tuple(fdp.ConsumeIntInRange(min_dim, max_dim) for _ in range(rank))


def _tensor(fdp, min_rank=0, max_rank=3, min_dim=1, max_dim=4):
    dtype = _pick_dtype(fdp)
    shape = _small_shape(fdp, min_rank=min_rank, max_rank=max_rank, min_dim=min_dim, max_dim=max_dim)
    if len(shape) == 0:
        return torch.tensor(fdp.ConsumeFloatInRange(-10.0, 10.0), dtype=dtype)
    numel = 1
    for s in shape:
        numel *= s
    vals = [fdp.ConsumeFloatInRange(-10.0, 10.0) for _ in range(numel)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _make_qconfig(fdp):
    qconfigs = []
    if hasattr(torch.quantization, "default_qconfig"):
        qconfigs.append(torch.quantization.default_qconfig)
    if hasattr(torch.quantization, "default_dynamic_qconfig"):
        qconfigs.append(torch.quantization.default_dynamic_qconfig)
    if hasattr(torch.quantization, "float16_dynamic_qconfig"):
        qconfigs.append(torch.quantization.float16_dynamic_qconfig)
    if hasattr(torch.quantization, "default_per_channel_qconfig"):
        qconfigs.append(torch.quantization.default_per_channel_qconfig)
    if ao_quantization is not None:
        for name in [
            "default_qconfig",
            "default_dynamic_qconfig",
            "float16_dynamic_qconfig",
            "default_per_channel_qconfig",
        ]:
            if hasattr(ao_quantization, name):
                qconfigs.append(getattr(ao_quantization, name))
    qconfigs.append(None)
    return fdp.PickValueInList(qconfigs)


class LeafNoWeight(nn.Module):
    def __init__(self, fdp):
        super().__init__()
        self.scale = fdp.ConsumeFloatInRange(-3.0, 3.0)

    def forward(self, x):
        return x * self.scale


class DynamicSubmodule(nn.Module):
    def __init__(self, fdp):
        super().__init__()
        in_f = fdp.ConsumeIntInRange(1, 8)
        out_f = fdp.ConsumeIntInRange(1, 8)
        self.linear = nn.Linear(in_f, out_f, bias=fdp.ConsumeBool())
        self.relu = nn.ReLU(inplace=fdp.ConsumeBool())

    def forward(self, x):
        return self.relu(self.linear(x))


class FuzzModel(nn.Module):
    def __init__(self, fdp):
        super().__init__()
        c1 = fdp.ConsumeIntInRange(1, 4)
        c2 = fdp.ConsumeIntInRange(1, 4)
        k = fdp.ConsumeIntInRange(1, 3)
        self.conv = nn.Conv2d(c1, c2, kernel_size=k, bias=fdp.ConsumeBool())
        self.bn = nn.BatchNorm2d(c2)
        self.relu = nn.ReLU(inplace=fdp.ConsumeBool())
        self.iden = nn.Identity()
        self.leaf = LeafNoWeight(fdp)
        self.seq = nn.Sequential(
            nn.Linear(fdp.ConsumeIntInRange(1, 8), fdp.ConsumeIntInRange(1, 8), bias=fdp.ConsumeBool()),
            nn.ReLU(inplace=fdp.ConsumeBool()),
        )
        self.sub = DynamicSubmodule(fdp)
        self.register_buffer("buf", _tensor(fdp, min_rank=1, max_rank=2, min_dim=1, max_dim=4))

        if fdp.ConsumeBool():
            self.qconfig = _make_qconfig(fdp)

    def forward(self, x):
        return x


def _module_type_candidates(module):
    types = {type(module)}
    for m in module.modules():
        types.add(type(m))
    return list(types)


def _module_name_candidates(module):
    names = [""]
    for n, _m in module.named_modules():
        names.append(n)
    return list(dict.fromkeys(names))


def _make_qconfig_dict(fdp, module):
    mode = fdp.ConsumeIntInRange(0, 6)
    if mode == 0:
        return None

    qconfig_dict = {}

    if mode in (1, 2, 3, 4, 5, 6):
        if fdp.ConsumeBool():
            qconfig_dict[""] = _make_qconfig(fdp)

    if mode in (2, 4, 6):
        names = _module_name_candidates(module)
        count = fdp.ConsumeIntInRange(0, min(4, len(names)))
        for _ in range(count):
            key = fdp.PickValueInList(names)
            qconfig_dict[key] = _make_qconfig(fdp)

    if mode in (3, 5, 6):
        types_list = _module_type_candidates(module)
        count = fdp.ConsumeIntInRange(0, min(4, len(types_list)))
        for _ in range(count):
            key = fdp.PickValueInList(types_list)
            qconfig_dict[key] = _make_qconfig(fdp)

    return qconfig_dict


def _make_prepare_custom_config_dict(fdp, module):
    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        return None

    d = {}

    if mode in (1, 4, 5):
        non_traceable = []
        for t in _module_type_candidates(module):
            if t not in non_traceable and fdp.ConsumeBool():
                non_traceable.append(t)
        if non_traceable:
            d["non_traceable_module_class"] = non_traceable

    if mode in (2, 4, 5):
        names = _module_name_candidates(module)
        selected = []
        count = fdp.ConsumeIntInRange(0, min(4, len(names)))
        for _ in range(count):
            n = fdp.PickValueInList(names)
            if n not in selected:
                selected.append(n)
        if selected:
            d["non_traceable_module_name"] = selected

    if mode in (3, 5):
        standalone = []
        for t in _module_type_candidates(module):
            if fdp.ConsumeBool():
                standalone.append(t)
        if standalone:
            d["standalone_module_class"] = standalone

    return d


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        module = FuzzModel(fdp)

        if fdp.ConsumeBool():
            module = copy.deepcopy(module)

        qconfig_dict = _make_qconfig_dict(fdp, module)
        prepare_custom_config_dict = _make_prepare_custom_config_dict(fdp, module)

        call_style = fdp.ConsumeIntInRange(0, 3)
        if call_style == 0:
            torch.quantization.propagate_qconfig_(module)
        elif call_style == 1:
            torch.quantization.propagate_qconfig_(module, qconfig_dict)
        elif call_style == 2:
            torch.quantization.propagate_qconfig_(
                module,
                qconfig_dict=qconfig_dict,
            )
        else:
            torch.quantization.propagate_qconfig_(
                module,
                qconfig_dict=qconfig_dict,
                prepare_custom_config_dict=prepare_custom_config_dict,
            )

        if fdp.ConsumeBool():
            _ = hasattr(module, "qconfig")
            for _name, subm in module.named_modules():
                _ = getattr(subm, "qconfig", None)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
