# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.randn
# source_yaml_count=8
# source_api_txt=/root/api_txt/torch.randn.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _available_devices():
    devices = [torch.device("cpu")]
    if torch.cuda.is_available():
        try:
            devices.append(torch.device("cuda"))
        except Exception:
            pass
    return devices


def _pick_dtype(fdp):
    dtypes = [
        None,
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
        torch.complex64,
        torch.complex128,
    ]
    return fdp.PickValueInList(dtypes)


def _pick_layout(fdp):
    return fdp.PickValueInList([None, torch.strided])


def _make_generator(fdp, device):
    if not fdp.ConsumeBool():
        return None
    try:
        gen = torch.Generator(device=device.type)
    except Exception:
        gen = torch.Generator()
    try:
        seed = fdp.ConsumeUInt(8)
        gen.manual_seed(seed)
    except Exception:
        pass
    return gen


def _make_shape(fdp):
    rank = fdp.PickValueInList([0, 1, 2, 3, 4, 5])
    shape = []
    for _ in range(rank):
        shape.append(fdp.ConsumeIntInRange(0, 4))
    return tuple(shape)


def _make_names(fdp, rank):
    if not fdp.ConsumeBool():
        return None
    pool = [
        None,
        "N",
        "C",
        "L",
        "H",
        "W",
        "D",
        "batch",
        "channel",
        "length",
        "height",
        "width",
        "depth",
        "...",
    ]
    names = []
    for _ in range(rank):
        names.append(fdp.PickValueInList(pool))
    return tuple(names)


def _make_out_tensor(shape, fdp, device):
    dtype = fdp.PickValueInList([torch.float32, torch.float64])
    if fdp.ConsumeBool():
        out_shape = shape
    else:
        rank = len(shape)
        out_shape = list(shape)
        if rank == 0:
            out_shape = ()
        elif rank > 0:
            idx = fdp.ConsumeIntInRange(0, rank - 1)
            out_shape = list(out_shape)
            out_shape[idx] = fdp.ConsumeIntInRange(0, 4)
            out_shape = tuple(out_shape)
    return torch.empty(out_shape, dtype=dtype, device=device)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        device = fdp.PickValueInList(_available_devices())
        shape = _make_shape(fdp)
        rank = len(shape)
        names = _make_names(fdp, rank)
        dtype = _pick_dtype(fdp)
        layout = _pick_layout(fdp)
        pin_memory = fdp.ConsumeBool()
        requires_grad = fdp.ConsumeBool()
        generator = _make_generator(fdp, device)

        mode = fdp.ConsumeIntInRange(0, 5)

        kwargs = {}

        if generator is not None:
            kwargs["generator"] = generator

        if mode in (0, 1, 4, 5):
            kwargs["dtype"] = dtype
            kwargs["layout"] = layout
            kwargs["device"] = device
            kwargs["requires_grad"] = requires_grad
            if device.type == "cpu":
                kwargs["pin_memory"] = pin_memory

        if mode in (2, 3, 5):
            kwargs["out"] = _make_out_tensor(shape, fdp, device)

        if mode in (1, 3, 4, 5):
            kwargs["names"] = names

        call_style = fdp.ConsumeIntInRange(0, 1)

        if call_style == 0:
            torch.randn(shape, **kwargs)
        else:
            torch.randn(*shape, **kwargs)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
