# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.utils.data.random_split
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.utils.data.random_split.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
from torch.utils.data import Dataset, TensorDataset, random_split


class FuzzDataset(Dataset):
    def __init__(self, kind, size, payload=None):
        self.kind = kind
        self.size = max(0, int(size))
        self.payload = payload

    def __len__(self):
        return self.size

    def __getitem__(self, idx):
        if idx < 0 or idx >= self.size:
            raise IndexError("index out of range")
        if self.kind == 0:
            return idx
        if self.kind == 1:
            return {"idx": idx, "value": idx * 2}
        if self.kind == 2:
            return (idx, str(idx))
        if self.kind == 3 and self.payload is not None:
            return self.payload[idx % len(self.payload)]
        return idx


def _make_tensor(fdp, size):
    if size <= 0:
        return torch.empty((0,), dtype=torch.float32)
    dtype = fdp.PickValueInList(
        [torch.float32, torch.float64, torch.int64, torch.int32, torch.bool]
    )
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(size)]
        return torch.tensor(vals, dtype=dtype)
    if dtype in (torch.int64, torch.int32):
        vals = [fdp.ConsumeIntInRange(-16, 16) for _ in range(size)]
        return torch.tensor(vals, dtype=dtype)
    vals = [fdp.ConsumeFloatInRange(-100.0, 100.0) for _ in range(size)]
    return torch.tensor(vals, dtype=dtype)


def _make_dataset(fdp):
    size = fdp.ConsumeIntInRange(0, 32)
    choice = fdp.ConsumeIntInRange(0, 4)
    if choice == 0:
        return list(range(size))
    if choice == 1:
        return range(size)
    if choice == 2:
        t = _make_tensor(fdp, size)
        return TensorDataset(t)
    if choice == 3:
        payload = []
        for i in range(size):
            payload.append(
                (
                    fdp.ConsumeIntInRange(-32, 32),
                    fdp.ConsumeFloatInRange(-10.0, 10.0),
                    fdp.ConsumeBool(),
                    i,
                )
            )
        return FuzzDataset(3, size, payload)
    return FuzzDataset(fdp.ConsumeIntInRange(0, 2), size)


def _gen_lengths_ints(fdp, n, total_len):
    if n <= 0:
        return []
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        remaining = total_len
        out = []
        for i in range(n):
            if i == n - 1:
                out.append(remaining)
            else:
                v = fdp.ConsumeIntInRange(0, remaining)
                out.append(v)
                remaining -= v
        return out
    if mode == 1:
        out = [0] * n
        for _ in range(total_len):
            out[fdp.ConsumeIntInRange(0, n - 1)] += 1
        return out
    if mode == 2:
        if n == 1:
            return [total_len]
        out = [0] * n
        forced = min(total_len, fdp.ConsumeIntInRange(0, n - 1))
        out[forced] = total_len
        return out
    if mode == 3:
        base = total_len // n
        out = [base] * n
        rem = total_len - base * n
        for i in range(rem):
            out[i % n] += 1
        return out
    out = []
    remaining = total_len
    for i in range(n):
        if i == n - 1:
            out.append(remaining)
        else:
            max_take = min(remaining, 3)
            v = fdp.ConsumeIntInRange(0, max_take)
            out.append(v)
            remaining -= v
    return out


def _gen_lengths_fractions(fdp, n):
    if n <= 0:
        return []
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        raw = [fdp.ConsumeFloatInRange(0.0, 1.0) for _ in range(n)]
        s = sum(raw)
        if s == 0.0:
            return [1.0 / n] * n
        return [x / s for x in raw]
    if mode == 1:
        return [1.0 / n] * n
    if mode == 2:
        out = [0.0] * n
        out[fdp.ConsumeIntInRange(0, n - 1)] = 1.0
        return out
    if mode == 3:
        if n == 1:
            return [1.0]
        vals = [0.0] * n
        remaining = 1.0
        for i in range(n - 1):
            v = fdp.ConsumeFloatInRange(0.0, remaining)
            vals[i] = v
            remaining -= v
        vals[-1] = remaining
        return vals
    numerators = [fdp.ConsumeIntInRange(0, 8) for _ in range(n)]
    s = sum(numerators)
    if s == 0:
        return [1.0 / n] * n
    return [float(x) / float(s) for x in numerators]


def _make_generator(fdp):
    if fdp.ConsumeBool():
        return None
    g = torch.Generator()
    seed = fdp.ConsumeUInt(8)
    g.manual_seed(seed)
    return g


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dataset = _make_dataset(fdp)
        dataset_len = len(dataset)

        num_splits = fdp.ConsumeIntInRange(1, 8)
        use_fractions = fdp.ConsumeBool()

        if use_fractions:
            lengths = _gen_lengths_fractions(fdp, num_splits)
        else:
            if fdp.ConsumeBool():
                lengths = _gen_lengths_ints(fdp, num_splits, dataset_len)
            else:
                lengths = [fdp.ConsumeIntInRange(-1, 8) for _ in range(num_splits)]

        generator = _make_generator(fdp)

        call_style = fdp.ConsumeIntInRange(0, 2)
        if call_style == 0:
            result = random_split(dataset, lengths)
        elif call_style == 1:
            result = random_split(dataset, lengths, generator=generator)
        else:
            result = torch.utils.data.random_split(
                dataset=dataset, lengths=lengths, generator=generator
            )

        if isinstance(result, list):
            for subset in result:
                _ = len(subset)
                if len(subset) > 0 and fdp.ConsumeBool():
                    idx = fdp.ConsumeIntInRange(0, len(subset) - 1)
                    _ = subset[idx]

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
