# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.cumsum
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.cumsum.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    dtypes = [
        None,
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
        torch.int8,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
        torch.complex64,
        torch.complex128,
    ]
    return fdp.PickValueInList(dtypes)


def _pick_base_dtype(fdp):
    dtypes = [
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
        torch.int8,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
        torch.complex64,
        torch.complex128,
    ]
    return fdp.PickValueInList(dtypes)


def _gen_shape(fdp, rank):
    shape = []
    for _ in range(rank):
        choice = fdp.ConsumeIntInRange(0, 9)
        if choice == 0:
            dim = 0
        elif choice <= 6:
            dim = fdp.ConsumeIntInRange(1, 4)
        else:
            dim = fdp.ConsumeIntInRange(5, 8)
        shape.append(dim)
    return shape


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, shape, dtype):
    n = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (
        torch.int8,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.uint8,
    ):
        if dtype == torch.uint8:
            vals = [fdp.ConsumeIntInRange(0, 255) for _ in range(n)]
        else:
            vals = [fdp.ConsumeIntInRange(-1000, 1000) for _ in range(n)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.complex64, torch.complex128):
        vals = [
            complex(
                fdp.ConsumeFloatInRange(-1000.0, 1000.0),
                fdp.ConsumeFloatInRange(-1000.0, 1000.0),
            )
            for _ in range(n)
        ]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = [fdp.ConsumeFloatInRange(-1000.0, 1000.0) for _ in range(n)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _make_named_tensor(fdp, rank, dtype):
    shape = _gen_shape(fdp, rank)
    t = _make_tensor(fdp, shape, dtype)
    candidate_names = ["N", "C", "H", "W", "D", "T", "B", "L"]
    names = []
    used = set()
    for i in range(rank):
        if fdp.ConsumeBool() and len(used) < len(candidate_names):
            available = [x for x in candidate_names if x not in used]
            name = fdp.PickValueInList(available)
            used.add(name)
            names.append(name)
        else:
            names.append(None)
    try:
        t = t.rename(*names)
    except Exception:
        pass
    return t


def _normalize_dim(dim, rank):
    if rank <= 0:
        return 0
    if dim < 0:
        dim += rank
    if dim < 0:
        dim = 0
    if dim >= rank:
        dim = rank - 1
    return dim


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 3)

        if mode == 0:
            rank = fdp.PickValueInList([0, 1, 2, 3, 4, 5])
            base_dtype = _pick_base_dtype(fdp)
            shape = _gen_shape(fdp, rank)
            x = _make_tensor(fdp, shape, base_dtype)
            raw_dim = fdp.ConsumeIntInRange(-8, 8)
            dim = _normalize_dim(raw_dim, x.ndim if x.ndim > 0 else 1)
            if x.ndim == 0:
                dim = 0
            out_dtype = _pick_dtype(fdp)

            if fdp.ConsumeBool():
                torch.cumsum(x, dim)
            elif fdp.ConsumeBool():
                torch.cumsum(x, dim, dtype=out_dtype)
            else:
                torch.cumsum(input=x, dim=dim, dtype=out_dtype)

        elif mode == 1:
            rank = fdp.PickValueInList([0, 1, 2, 3, 4])
            base_dtype = _pick_base_dtype(fdp)
            shape = _gen_shape(fdp, rank)
            x = _make_tensor(fdp, shape, base_dtype)
            raw_dim = fdp.ConsumeIntInRange(-8, 8)
            dim = _normalize_dim(raw_dim, x.ndim if x.ndim > 0 else 1)
            if x.ndim == 0:
                dim = 0
            out_dtype = _pick_dtype(fdp)

            target_dtype = out_dtype if out_dtype is not None else x.dtype
            if fdp.ConsumeBool():
                out = torch.empty_like(x, dtype=target_dtype)
            else:
                out = torch.empty(x.shape, dtype=target_dtype)

            if fdp.ConsumeBool():
                torch.cumsum(x, dim, out=out)
            else:
                torch.cumsum(x, dim, dtype=out_dtype, out=out)

        elif mode == 2:
            rank = fdp.PickValueInList([1, 2, 3, 4])
            base_dtype = fdp.PickValueInList([torch.float32, torch.float64])
            x = _make_named_tensor(fdp, rank, base_dtype)
            present_names = [n for n in x.names if n is not None]
            if present_names:
                dimname = fdp.PickValueInList(present_names)
            else:
                dimname = fdp.PickValueInList(["N", "C", "H", "W"])
            out_dtype = _pick_dtype(fdp)

            if fdp.ConsumeBool():
                torch.cumsum(x, dimname)
            else:
                torch.cumsum(x, dimname, dtype=out_dtype)

        else:
            rank = fdp.PickValueInList([1, 2, 3, 4])
            base_dtype = fdp.PickValueInList([torch.float32, torch.float64])
            x = _make_named_tensor(fdp, rank, base_dtype)
            present_names = [n for n in x.names if n is not None]
            if present_names:
                dimname = fdp.PickValueInList(present_names)
            else:
                dimname = fdp.PickValueInList(["N", "C", "H", "W"])
            out_dtype = _pick_dtype(fdp)
            target_dtype = out_dtype if out_dtype is not None else x.dtype

            out = torch.empty(x.shape, dtype=target_dtype, names=x.names)

            if fdp.ConsumeBool():
                torch.cumsum(x, dimname, out=out)
            else:
                torch.cumsum(x, dimname, dtype=out_dtype, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
