# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.bincount
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.bincount.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _choose_input_dtype(fdp):
    return fdp.PickValueInList([torch.int8, torch.int16, torch.int32, torch.int64, torch.uint8])


def _choose_weight_dtype(fdp):
    return fdp.PickValueInList([torch.float16, torch.float32, torch.float64])


def _make_input_tensor(fdp):
    length = fdp.ConsumeIntInRange(0, 64)
    dtype = _choose_input_dtype(fdp)

    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        max_val = fdp.ConsumeIntInRange(0, 8)
        vals = fdp.ConsumeIntListInRange(length, 0, max_val)
    elif mode == 1:
        vals = fdp.ConsumeIntListInRange(length, 0, 64)
    elif mode == 2:
        vals = list(range(length))
    elif mode == 3:
        base = fdp.ConsumeIntInRange(0, 16)
        vals = [base] * length
    elif mode == 4:
        period = max(1, fdp.ConsumeIntInRange(1, 8))
        vals = [i % period for i in range(length)]
    else:
        vals = fdp.ConsumeIntListInRange(length, 0, 256)

    return torch.tensor(vals, dtype=dtype)


def _make_weights(fdp, length):
    if not fdp.ConsumeBool():
        return None

    dtype = _choose_weight_dtype(fdp)
    mode = fdp.ConsumeIntInRange(0, 5)

    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(length)
    elif mode == 1:
        vals = fdp.ConsumeFloatListInRange(length, -10.0, 10.0)
    elif mode == 2:
        vals = [0.0] * length
    elif mode == 3:
        vals = [1.0] * length
    elif mode == 4:
        vals = [float(i) for i in range(length)]
    else:
        vals = [fdp.ConsumeFloat() for _ in range(length)]

    return torch.tensor(vals, dtype=dtype)


def _make_out_tensor(fdp, dtype):
    out_len = fdp.ConsumeIntInRange(0, 64)
    mode = fdp.ConsumeIntInRange(0, 3)
    if mode == 0:
        vals = [0.0] * out_len
    elif mode == 1:
        vals = fdp.ConsumeFloatListInRange(out_len, -1.0, 1.0)
    elif mode == 2:
        vals = fdp.ConsumeRegularFloatList(out_len)
    else:
        vals = [float(i) for i in range(out_len)]
    return torch.tensor(vals, dtype=dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        inp = _make_input_tensor(fdp)
        weights = _make_weights(fdp, int(inp.numel()))

        minlength_mode = fdp.ConsumeIntInRange(0, 4)
        if minlength_mode == 0:
            minlength = 0
        elif minlength_mode == 1:
            minlength = fdp.ConsumeIntInRange(0, 8)
        elif minlength_mode == 2:
            minlength = fdp.ConsumeIntInRange(0, 64)
        elif minlength_mode == 3:
            minlength = int(inp.numel())
        else:
            minlength = max(0, fdp.ConsumeIntInRange(-1, 16))

        call_mode = fdp.ConsumeIntInRange(0, 2)

        if call_mode == 0:
            torch.bincount(inp, weights=weights, minlength=minlength)
        elif call_mode == 1:
            torch.bincount(inp, weights, minlength)
        else:
            out_dtype = weights.dtype if weights is not None else fdp.PickValueInList([torch.int64, torch.float32, torch.float64])
            out = _make_out_tensor(fdp, out_dtype)
            torch.bincount(inp, weights=weights, minlength=minlength, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
