# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.remove_spectral_norm
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.remove_spectral_norm.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys

import torch
import torch.nn as nn
from torch.nn.utils import spectral_norm, remove_spectral_norm


def _pick_module_kind(fdp):
    return fdp.PickValueInList(
        [
            "linear",
            "conv1d",
            "conv2d",
            "conv3d",
            "conv_transpose1d",
            "conv_transpose2d",
            "conv_transpose3d",
            "embedding",
            "bilinear",
        ]
    )


def _small_pos_int(fdp, low=1, high=8):
    return fdp.ConsumeIntInRange(low, high)


def _make_module(fdp):
    kind = _pick_module_kind(fdp)

    if kind == "linear":
        in_features = _small_pos_int(fdp, 1, 16)
        out_features = _small_pos_int(fdp, 1, 16)
        bias = fdp.ConsumeBool()
        return nn.Linear(in_features, out_features, bias=bias)

    if kind == "conv1d":
        in_channels = _small_pos_int(fdp, 1, 8)
        out_channels = _small_pos_int(fdp, 1, 8)
        kernel_size = _small_pos_int(fdp, 1, 5)
        stride = _small_pos_int(fdp, 1, 3)
        padding = fdp.ConsumeIntInRange(0, 3)
        dilation = _small_pos_int(fdp, 1, 3)
        groups_choices = [g for g in range(1, in_channels + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_choices)
        bias = fdp.ConsumeBool()
        return nn.Conv1d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=groups,
            bias=bias,
        )

    if kind == "conv2d":
        in_channels = _small_pos_int(fdp, 1, 8)
        out_channels = _small_pos_int(fdp, 1, 8)
        kernel_size = (
            _small_pos_int(fdp, 1, 5),
            _small_pos_int(fdp, 1, 5),
        )
        stride = (
            _small_pos_int(fdp, 1, 3),
            _small_pos_int(fdp, 1, 3),
        )
        padding = (
            fdp.ConsumeIntInRange(0, 3),
            fdp.ConsumeIntInRange(0, 3),
        )
        dilation = (
            _small_pos_int(fdp, 1, 3),
            _small_pos_int(fdp, 1, 3),
        )
        groups_choices = [g for g in range(1, in_channels + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_choices)
        bias = fdp.ConsumeBool()
        return nn.Conv2d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=groups,
            bias=bias,
        )

    if kind == "conv3d":
        in_channels = _small_pos_int(fdp, 1, 6)
        out_channels = _small_pos_int(fdp, 1, 6)
        kernel_size = (
            _small_pos_int(fdp, 1, 4),
            _small_pos_int(fdp, 1, 4),
            _small_pos_int(fdp, 1, 4),
        )
        stride = (
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
        )
        padding = (
            fdp.ConsumeIntInRange(0, 2),
            fdp.ConsumeIntInRange(0, 2),
            fdp.ConsumeIntInRange(0, 2),
        )
        dilation = (
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
        )
        groups_choices = [g for g in range(1, in_channels + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_choices)
        bias = fdp.ConsumeBool()
        return nn.Conv3d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=groups,
            bias=bias,
        )

    if kind == "conv_transpose1d":
        in_channels = _small_pos_int(fdp, 1, 8)
        out_channels = _small_pos_int(fdp, 1, 8)
        kernel_size = _small_pos_int(fdp, 1, 5)
        stride = _small_pos_int(fdp, 1, 3)
        padding = fdp.ConsumeIntInRange(0, 2)
        output_padding = fdp.ConsumeIntInRange(0, max(0, stride - 1))
        groups_choices = [g for g in range(1, min(in_channels, out_channels) + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_choices)
        bias = fdp.ConsumeBool()
        dilation = _small_pos_int(fdp, 1, 2)
        return nn.ConvTranspose1d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            output_padding=output_padding,
            groups=groups,
            bias=bias,
            dilation=dilation,
        )

    if kind == "conv_transpose2d":
        in_channels = _small_pos_int(fdp, 1, 8)
        out_channels = _small_pos_int(fdp, 1, 8)
        kernel_size = (
            _small_pos_int(fdp, 1, 4),
            _small_pos_int(fdp, 1, 4),
        )
        stride = (
            _small_pos_int(fdp, 1, 3),
            _small_pos_int(fdp, 1, 3),
        )
        padding = (
            fdp.ConsumeIntInRange(0, 2),
            fdp.ConsumeIntInRange(0, 2),
        )
        output_padding = (
            fdp.ConsumeIntInRange(0, max(0, stride[0] - 1)),
            fdp.ConsumeIntInRange(0, max(0, stride[1] - 1)),
        )
        groups_choices = [g for g in range(1, min(in_channels, out_channels) + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_choices)
        bias = fdp.ConsumeBool()
        dilation = (
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
        )
        return nn.ConvTranspose2d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            output_padding=output_padding,
            groups=groups,
            bias=bias,
            dilation=dilation,
        )

    if kind == "conv_transpose3d":
        in_channels = _small_pos_int(fdp, 1, 6)
        out_channels = _small_pos_int(fdp, 1, 6)
        kernel_size = (
            _small_pos_int(fdp, 1, 3),
            _small_pos_int(fdp, 1, 3),
            _small_pos_int(fdp, 1, 3),
        )
        stride = (
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
        )
        padding = (
            fdp.ConsumeIntInRange(0, 1),
            fdp.ConsumeIntInRange(0, 1),
            fdp.ConsumeIntInRange(0, 1),
        )
        output_padding = (
            fdp.ConsumeIntInRange(0, max(0, stride[0] - 1)),
            fdp.ConsumeIntInRange(0, max(0, stride[1] - 1)),
            fdp.ConsumeIntInRange(0, max(0, stride[2] - 1)),
        )
        groups_choices = [g for g in range(1, min(in_channels, out_channels) + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_choices)
        bias = fdp.ConsumeBool()
        dilation = (
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
            _small_pos_int(fdp, 1, 2),
        )
        return nn.ConvTranspose3d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            output_padding=output_padding,
            groups=groups,
            bias=bias,
            dilation=dilation,
        )

    if kind == "embedding":
        num_embeddings = _small_pos_int(fdp, 1, 32)
        embedding_dim = _small_pos_int(fdp, 1, 16)
        padding_idx = fdp.ConsumeIntInRange(-1, num_embeddings - 1)
        max_norm = None if fdp.ConsumeBool() else fdp.ConsumeFloatInRange(0.1, 5.0)
        norm_type = fdp.ConsumeFloatInRange(1.0, 3.0)
        scale_grad_by_freq = fdp.ConsumeBool()
        sparse = fdp.ConsumeBool()
        return nn.Embedding(
            num_embeddings,
            embedding_dim,
            padding_idx=padding_idx,
            max_norm=max_norm,
            norm_type=norm_type,
            scale_grad_by_freq=scale_grad_by_freq,
            sparse=sparse,
        )

    if kind == "bilinear":
        in1_features = _small_pos_int(fdp, 1, 8)
        in2_features = _small_pos_int(fdp, 1, 8)
        out_features = _small_pos_int(fdp, 1, 8)
        bias = fdp.ConsumeBool()
        return nn.Bilinear(in1_features, in2_features, out_features, bias=bias)

    return nn.Linear(1, 1)


def _maybe_apply_spectral_norm(fdp, module):
    weight_names = [name for name, _ in module.named_parameters(recurse=False)]
    candidate_names = []
    if "weight" in weight_names:
        candidate_names.append("weight")
    candidate_names.extend([n for n in weight_names if n != "weight"])

    if not candidate_names:
        return module, fdp.PickValueInList(["weight", "bias", ""])

    valid_name = fdp.PickValueInList(candidate_names)

    if fdp.ConsumeBool():
        module = spectral_norm(module, name=valid_name)
        chosen_remove_name = valid_name
    else:
        chosen_remove_name = fdp.PickValueInList(
            [valid_name, "weight", "bias", "", "not_a_parameter"]
        )

    return module, chosen_remove_name


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        module = _make_module(fdp)

        if fdp.ConsumeBool():
            module.train()
        else:
            module.eval()

        if fdp.ConsumeBool():
            module = module.to(dtype=torch.float32)

        module, remove_name = _maybe_apply_spectral_norm(fdp, module)

        if fdp.ConsumeBool():
            remove_spectral_norm(module)
        else:
            remove_spectral_norm(module, name=remove_name)

        if fdp.ConsumeBool():
            try:
                if fdp.ConsumeBool():
                    remove_spectral_norm(module)
                else:
                    remove_spectral_norm(module, name=remove_name)
            except (
                RuntimeError,
                TypeError,
                ValueError,
                IndexError,
                AssertionError,
                NotImplementedError,
            ):
                return
            except Exception:
                return

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
