# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.mm
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.mm.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    # Favor YAML dtypes, but include doc-mentioned low-precision types for out_dtype coverage.
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
    ])


def _pick_input_dtype(fdp):
    # Validity-biased toward YAML and common supported CPU dtypes.
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.int32,
        torch.int64,
        torch.float16,
        torch.bfloat16,
    ])


def _consume_dim(fdp, low, high):
    specials = [0, 1, 2, 3, 4, 7, 8, 16, 31, 32, 63, 64]
    if fdp.ConsumeBool():
        return fdp.PickValueInList([x for x in specials if low <= x <= high])
    return fdp.ConsumeIntInRange(low, high)


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype):
    total = _numel(shape)
    if dtype.is_floating_point:
        mode = fdp.ConsumeIntInRange(0, 5)
        if mode == 0:
            vals = [0.0] * total
        elif mode == 1:
            vals = [1.0] * total
        elif mode == 2:
            vals = fdp.ConsumeFloatListInRange(total, -8.0, 8.0)
        elif mode == 3:
            vals = [float(x) for x in fdp.ConsumeIntListInRange(total, -3, 3)]
        elif mode == 4:
            vals = []
            for _ in range(total):
                vals.append(fdp.PickValueInList([-0.0, 0.0, 1.0, -1.0, 2.0, -2.0, 0.5, -0.5]))
        else:
            vals = fdp.ConsumeRegularFloatList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    else:
        mode = fdp.ConsumeIntInRange(0, 3)
        if mode == 0:
            vals = [0] * total
        elif mode == 1:
            vals = [1] * total
        elif mode == 2:
            vals = fdp.ConsumeIntListInRange(total, -16, 16)
        else:
            vals = []
            for _ in range(total):
                vals.append(fdp.PickValueInList([-2, -1, 0, 1, 2, 7, 8]))
        return torch.tensor(vals, dtype=dtype).reshape(shape)


def _maybe_noncontiguous_2d(fdp, t):
    if t.ndim != 2:
        return t
    choice = fdp.ConsumeIntInRange(0, 4)
    if choice == 0:
        return t
    if choice == 1:
        return t.t().t()
    if choice == 2:
        if t.shape[0] > 0 and t.shape[1] > 0:
            big = torch.empty((t.shape[0] * 2 + 1, t.shape[1] * 2 + 1), dtype=t.dtype)
            big[: t.shape[0], : t.shape[1]] = t
            return big[: t.shape[0], : t.shape[1]:2].repeat_interleave(2, dim=1)[:, : t.shape[1]]
        return t
    if choice == 3:
        return t[:, :]
    return t.contiguous() if fdp.ConsumeBool() else t


def _make_compatible_matrices(fdp):
    n = _consume_dim(fdp, 0, 8)
    m = _consume_dim(fdp, 0, 64)
    p = _consume_dim(fdp, 0, 64)

    same_dtype = fdp.ConsumeBool()
    dtype1 = _pick_input_dtype(fdp)
    dtype2 = dtype1 if same_dtype else _pick_input_dtype(fdp)

    a = _make_tensor(fdp, (n, m), dtype1)
    b = _make_tensor(fdp, (m, p), dtype2)

    if fdp.ConsumeBool():
        a = _maybe_noncontiguous_2d(fdp, a)
    if fdp.ConsumeBool():
        b = _maybe_noncontiguous_2d(fdp, b)

    return a, b, n, p


def _make_out_tensor(fdp, shape, base_dtype, out_dtype):
    use_out_dtype = fdp.ConsumeBool()
    dtype = out_dtype if (out_dtype is not None and use_out_dtype) else base_dtype
    if fdp.ConsumeBool():
        return torch.empty(shape, dtype=dtype)
    return _make_tensor(fdp, shape, dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mat1, mat2, n, p = _make_compatible_matrices(fdp)

        use_out_dtype = fdp.ConsumeBool()
        out_dtype = _pick_dtype(fdp) if use_out_dtype else None

        use_out = fdp.ConsumeBool()
        kwargs = {}

        if use_out:
            if fdp.ConsumeBool():
                out_shape = (n, p)
            else:
                out_shape = (
                    _consume_dim(fdp, 0, 8),
                    _consume_dim(fdp, 0, 64),
                )
            out = _make_out_tensor(
                fdp,
                out_shape,
                mat1.dtype if mat1.dtype == mat2.dtype else _pick_input_dtype(fdp),
                out_dtype,
            )
            kwargs["out"] = out

        # Exercise different calling styles while always reaching torch.mm.
        call_style = fdp.ConsumeIntInRange(0, 3)
        if call_style == 0:
            if out_dtype is None:
                torch.mm(mat1, mat2, **kwargs)
            else:
                torch.mm(mat1, mat2, out_dtype=out_dtype, **kwargs)
        elif call_style == 1:
            if out_dtype is None:
                torch.mm(input=mat1, mat2=mat2, **kwargs)
            else:
                torch.mm(input=mat1, mat2=mat2, out_dtype=out_dtype, **kwargs)
        elif call_style == 2:
            if out_dtype is None:
                torch.mm(mat2=mat2, input=mat1, **kwargs)
            else:
                torch.mm(mat2=mat2, input=mat1, out_dtype=out_dtype, **kwargs)
        else:
            # Make a second call with slightly altered tensor views when possible.
            res = torch.mm(mat1, mat2, out_dtype=out_dtype, **kwargs) if out_dtype is not None else torch.mm(mat1, mat2, **kwargs)
            if isinstance(res, torch.Tensor) and res.ndim == 2 and res.numel() >= 0:
                mat1b = mat1.contiguous() if fdp.ConsumeBool() else mat1
                mat2b = mat2.contiguous() if fdp.ConsumeBool() else mat2
                if out_dtype is None:
                    torch.mm(mat1b, mat2b)
                else:
                    torch.mm(mat1b, mat2b, out_dtype=out_dtype)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
