# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.prod
# source_yaml_count=6
# source_api_txt=/root/api_txt/torch.prod.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys

import torch


DTYPES = [
    None,
    torch.float32,
    torch.float64,
    torch.int32,
    torch.int64,
    torch.bool,
]

BASE_DTYPES = [
    torch.float32,
    torch.float64,
    torch.int32,
    torch.int64,
    torch.bool,
]

DIMNAMES_BY_RANK = {
    1: ["N"],
    2: ["N", "C"],
    3: ["N", "C", "L"],
    4: ["N", "C", "H", "W"],
    5: ["N", "C", "D", "H", "W"],
}


def _consume_shape(fdp, min_rank=1, max_rank=5):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    shape = []
    for _ in range(rank):
        if fdp.ConsumeBool():
            dim = fdp.PickValueInList([0, 1, 2, 3, 4, 8])
        else:
            dim = fdp.ConsumeIntInRange(0, 8)
        shape.append(dim)
    return tuple(shape)


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, shape, dtype):
    n = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.int32, torch.int64):
        vals = []
        for _ in range(n):
            if fdp.ConsumeBool():
                vals.append(fdp.PickValueInList([-3, -2, -1, 0, 1, 2, 3]))
            else:
                vals.append(fdp.ConsumeIntInRange(-8, 8))
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    vals = []
    for _ in range(n):
        if fdp.ConsumeBool():
            vals.append(fdp.PickValueInList([0.0, 1.0, -1.0, 2.0, -2.0, 0.5, -0.5]))
        else:
            vals.append(fdp.ConsumeFloatInRange(-4.0, 4.0))
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _normalize_dim(dim, rank):
    if rank <= 0:
        return 0
    if -rank <= dim < rank:
        return dim
    return dim % rank


def _reduced_shape(shape, dim, keepdim):
    rank = len(shape)
    dim = _normalize_dim(dim, rank)
    if keepdim:
        out_shape = list(shape)
        out_shape[dim] = 1
        return tuple(out_shape)
    return tuple(shape[i] for i in range(rank) if i != dim)


def _make_out_tensor(fdp, shape, dtype):
    n = _numel(shape)
    if n == 0:
        return torch.empty(shape, dtype=dtype)
    return _make_tensor(fdp, shape, dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 5)

        base_dtype = fdp.PickValueInList(BASE_DTYPES)
        if mode == 2:
            shape = _consume_shape(fdp, 2, 5)
        elif mode == 4:
            shape = _consume_shape(fdp, 1, 4)
        else:
            shape = _consume_shape(fdp, 1, 5)

        x = _make_tensor(fdp, shape, base_dtype)
        dtype = fdp.PickValueInList(DTYPES)

        if mode == 0:
            if fdp.ConsumeBool():
                torch.prod(x)
            else:
                torch.prod(x, dtype=dtype)

        elif mode == 1:
            rank = x.ndim
            if rank == 0:
                return
            dim = _normalize_dim(fdp.ConsumeIntInRange(-max(1, rank + 2), max(1, rank + 2)), rank)
            keepdim = fdp.ConsumeBool()
            if fdp.ConsumeBool():
                torch.prod(x, dim=dim, keepdim=keepdim)
            else:
                torch.prod(x, dim=dim, keepdim=keepdim, dtype=dtype)

        elif mode == 2:
            rank = x.ndim
            if rank == 0:
                return
            dimname = fdp.PickValueInList(DIMNAMES_BY_RANK[rank])
            named_x = x.refine_names(*DIMNAMES_BY_RANK[rank])
            keepdim = fdp.ConsumeBool()
            if fdp.ConsumeBool():
                torch.prod(named_x, dim=dimname, keepdim=keepdim)
            else:
                torch.prod(named_x, dim=dimname, keepdim=keepdim, dtype=dtype)

        elif mode == 3:
            out_dtype = dtype if dtype is not None else x.dtype
            out_shape = ()
            out = _make_out_tensor(fdp, out_shape, out_dtype)
            if fdp.ConsumeBool():
                torch.prod(x, out=out)
            else:
                torch.prod(x, dtype=dtype, out=out)

        elif mode == 4:
            rank = x.ndim
            if rank == 0:
                return
            dim = _normalize_dim(fdp.ConsumeIntInRange(-max(1, rank + 2), max(1, rank + 2)), rank)
            keepdim = fdp.ConsumeBool()
            out_dtype = dtype if dtype is not None else x.dtype
            out_shape = _reduced_shape(tuple(x.shape), dim, keepdim)
            out = _make_out_tensor(fdp, out_shape, out_dtype)
            if fdp.ConsumeBool():
                torch.prod(x, dim=dim, keepdim=keepdim, out=out)
            else:
                torch.prod(x, dim=dim, keepdim=keepdim, dtype=dtype, out=out)

        else:
            rank = x.ndim
            if rank == 0:
                return
            dimname = fdp.PickValueInList(DIMNAMES_BY_RANK[rank])
            named_x = x.refine_names(*DIMNAMES_BY_RANK[rank])
            dim_index = DIMNAMES_BY_RANK[rank].index(dimname)
            keepdim = fdp.ConsumeBool()
            out_dtype = dtype if dtype is not None else named_x.dtype
            out_shape = _reduced_shape(tuple(named_x.shape), dim_index, keepdim)
            out = _make_out_tensor(fdp, out_shape, out_dtype)
            if fdp.ConsumeBool():
                torch.prod(named_x, dim=dimname, keepdim=keepdim, out=out)
            else:
                torch.prod(named_x, dim=dimname, keepdim=keepdim, dtype=dtype, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
