# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.prune.ln_structured
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.prune.ln_structured.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch
import torch.nn as nn
import torch.nn.utils.prune as prune


def _pick_shape_for_rank(fdp, rank):
    if rank == 2:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
        ]
    if rank == 3:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
            fdp.ConsumeIntInRange(1, 16),
        ]
    if rank == 4:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        ]
    return [
        fdp.ConsumeIntInRange(1, 4),
        fdp.ConsumeIntInRange(1, 8),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
    ]


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, shape, dtype):
    numel = _numel(shape)
    if dtype.is_floating_point:
        vals = []
        mode = fdp.ConsumeIntInRange(0, 4)
        for _ in range(numel):
            if mode == 0:
                vals.append(fdp.ConsumeFloatInRange(-1.0, 1.0))
            elif mode == 1:
                vals.append(fdp.ConsumeFloatInRange(-10.0, 10.0))
            elif mode == 2:
                vals.append(float(fdp.ConsumeIntInRange(-3, 3)))
            elif mode == 3:
                vals.append(0.0 if fdp.ConsumeBool() else 1.0)
            else:
                vals.append(fdp.ConsumeRegularFloat())
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = [fdp.ConsumeIntInRange(-8, 8) for _ in range(numel)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


class ParamModule(nn.Module):
    def __init__(self, tensor, param_name):
        super().__init__()
        self.register_parameter(param_name, nn.Parameter(tensor))


def _choose_name(fdp):
    names = ["weight", "bias", "param", "kernel", "proj"]
    return fdp.PickValueInList(names)


def _choose_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.float16,
    ])


def _choose_n(fdp):
    choices = [
        0,
        1,
        2,
        3,
        -1,
        float("inf"),
        float("-inf"),
        "fro",
        "nuc",
    ]
    return fdp.PickValueInList(choices)


def _choose_amount(fdp, channels):
    if fdp.ConsumeBool():
        return fdp.ConsumeIntInRange(0, max(0, channels + 2))
    return fdp.ConsumeFloatInRange(0.0, 1.5)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        rank = fdp.PickValueInList([2, 3, 4, 5])
        shape = _pick_shape_for_rank(fdp, rank)
        dtype = _choose_dtype(fdp)
        name = _choose_name(fdp)

        tensor = _make_tensor(fdp, shape, dtype)
        module = ParamModule(tensor, name)

        dim = fdp.ConsumeIntInRange(-rank, rank - 1)
        dim_norm = dim if dim >= 0 else rank + dim
        channels = shape[dim_norm]

        amount = _choose_amount(fdp, channels)
        n = _choose_n(fdp)

        use_importance = fdp.ConsumeBool()
        importance_scores = None
        if use_importance:
            if fdp.ConsumeBool():
                importance_scores = _make_tensor(fdp, shape, dtype)
            else:
                alt_dtype = fdp.PickValueInList([torch.float32, torch.float64, torch.float16])
                importance_scores = _make_tensor(fdp, shape, alt_dtype)

        if fdp.ConsumeBool():
            prune.ln_structured(
                module=module,
                name=name,
                amount=amount,
                n=n,
                dim=dim,
                importance_scores=importance_scores,
            )
        else:
            prune.ln_structured(module, name, amount, n, dim, importance_scores)

        if hasattr(module, name):
            _ = getattr(module, name)
        if hasattr(module, name + "_mask"):
            _ = getattr(module, name + "_mask")
        if hasattr(module, name + "_orig"):
            _ = getattr(module, name + "_orig")

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
