# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.broadcast_tensors
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.broadcast_tensors.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _make_base_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 10)
    shape = []
    for _ in range(rank):
        shape.append(fdp.ConsumeIntInRange(1, 4))
    return tuple(shape)


def _broadcastable_shape_from_base(fdp, base_shape):
    rank_delta = fdp.ConsumeIntInRange(0, 3)
    target_rank = max(0, len(base_shape) - rank_delta)
    aligned = base_shape[-target_rank:] if target_rank > 0 else []
    out = []
    for dim in aligned:
        mode = fdp.ConsumeIntInRange(0, 4)
        if mode == 0:
            out.append(1)
        elif mode == 1:
            out.append(dim)
        elif mode == 2 and dim > 1:
            out.append(1)
        else:
            out.append(dim)
    return tuple(out)


def _numel(shape):
    n = 1
    for d in shape:
        n *= int(d)
    return n


def _make_tensor(fdp, shape, dtype):
    numel = _numel(shape)
    if numel == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 6)

    if mode == 0:
        data = fdp.ConsumeFloatListInRange(numel, -10.0, 10.0)
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if mode == 1:
        val = fdp.ConsumeFloatInRange(-10.0, 10.0)
        return torch.full(shape, val, dtype=dtype)
    if mode == 2:
        if numel == 1:
            data = [fdp.ConsumeFloatInRange(-1.0, 1.0)]
        else:
            start = fdp.ConsumeFloatInRange(-5.0, 5.0)
            step = fdp.ConsumeFloatInRange(-3.0, 3.0)
            data = [start + step * i for i in range(numel)]
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if mode == 3:
        data = [0.0] * numel
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if mode == 4:
        data = [1.0] * numel
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if mode == 5:
        data = []
        for _ in range(numel):
            choice = fdp.ConsumeIntInRange(0, 4)
            if choice == 0:
                data.append(0.0)
            elif choice == 1:
                data.append(1.0)
            elif choice == 2:
                data.append(-1.0)
            elif choice == 3:
                data.append(2.0)
            else:
                data.append(fdp.ConsumeFloatInRange(-100.0, 100.0))
        return torch.tensor(data, dtype=dtype).reshape(shape)

    return torch.randn(shape, dtype=dtype)


def _make_tensor_list(fdp):
    if fdp.ConsumeBool():
        count = 10
    else:
        count = fdp.ConsumeIntInRange(0, 12)

    dtype = _pick_dtype(fdp)
    base_shape = _make_base_shape(fdp)
    tensors = []

    for _ in range(count):
        if fdp.ConsumeBool():
            shape = base_shape
        else:
            shape = _broadcastable_shape_from_base(fdp, base_shape)
        tensors.append(_make_tensor(fdp, shape, dtype))

    return tensors


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        tensors = _make_tensor_list(fdp)

        if fdp.ConsumeBool():
            result = torch.broadcast_tensors(*tensors)
        else:
            result = torch.broadcast_tensors(*tuple(tensors))

        if isinstance(result, (list, tuple)):
            for t in result:
                _ = t.size()
                _ = t.stride()
                _ = t.numel()
                if t.numel() > 0 and fdp.ConsumeBool():
                    _ = t.reshape(-1)[: min(t.numel(), 4)].sum()
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
