# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.roll
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.roll.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.int32,
        torch.int64,
        torch.bool,
    ])


def _make_shape(fdp, force_2d=False):
    if force_2d:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        ]
    rank = fdp.ConsumeIntInRange(0, 4)
    shape = []
    for _ in range(rank):
        shape.append(fdp.ConsumeIntInRange(0, 6))
    return shape


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_tensor(fdp, shape=None, dtype=None, force_2d=False):
    if dtype is None:
        dtype = _pick_dtype(fdp)
    if shape is None:
        shape = _make_shape(fdp, force_2d=force_2d)

    n = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        t = torch.tensor(vals, dtype=dtype)
    elif dtype.is_floating_point:
        mode = fdp.ConsumeIntInRange(0, 3)
        if mode == 0:
            vals = [float(i % 7 - 3) for i in range(n)]
        elif mode == 1:
            vals = fdp.ConsumeRegularFloatList(n)
        elif mode == 2:
            vals = fdp.ConsumeFloatListInRange(n, -10.0, 10.0)
        else:
            vals = [0.0] * n
        t = torch.tensor(vals, dtype=dtype)
    else:
        vals = [fdp.ConsumeIntInRange(-16, 16) for _ in range(n)]
        t = torch.tensor(vals, dtype=dtype)

    return t.reshape(shape)


def _make_dims_and_shifts(fdp, ndim):
    if fdp.ConsumeBool():
        return None, fdp.ConsumeIntInRange(-8, 8)

    if ndim == 0:
        return [], [fdp.ConsumeIntInRange(-8, 8)]

    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        dim = fdp.ConsumeIntInRange(-ndim, ndim - 1)
        shift = fdp.ConsumeIntInRange(-16, 16)
        return dim, shift

    max_len = min(3, ndim)
    count = fdp.ConsumeIntInRange(1, max_len)
    dims = []
    for _ in range(count):
        dims.append(fdp.ConsumeIntInRange(-ndim, ndim - 1))
    shifts = [fdp.ConsumeIntInRange(-16, 16) for _ in range(count)]

    if mode == 1:
        return tuple(dims), tuple(shifts)
    if mode == 2:
        return dims, shifts
    if mode == 3:
        return tuple(dims), shifts
    return dims, tuple(shifts)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        use_out_variant = fdp.ConsumeBool()

        if use_out_variant:
            dtype = fdp.PickValueInList([torch.float32, torch.float64])
            shape = _make_shape(fdp, force_2d=True)
            x = _make_tensor(fdp, shape=shape, dtype=dtype, force_2d=True)
            dims, shifts = _make_dims_and_shifts(fdp, x.ndim)

            out_dtype = dtype if fdp.ConsumeBool() else fdp.PickValueInList([torch.float32, torch.float64])
            if fdp.ConsumeBool():
                out_shape = list(shape)
            else:
                out_shape = _make_shape(fdp, force_2d=fdp.ConsumeBool())

            out = _make_tensor(fdp, shape=out_shape, dtype=out_dtype, force_2d=(len(out_shape) == 2 and fdp.ConsumeBool()))

            if dims is None:
                torch.roll(x, shifts=shifts, out=out)
            else:
                torch.roll(x, shifts=shifts, dims=dims, out=out)
        else:
            x = _make_tensor(fdp)
            dims, shifts = _make_dims_and_shifts(fdp, x.ndim)

            call_style = fdp.ConsumeIntInRange(0, 3)
            if dims is None:
                if call_style == 0:
                    torch.roll(x, shifts)
                else:
                    torch.roll(input=x, shifts=shifts)
            else:
                if call_style == 0:
                    torch.roll(x, shifts, dims)
                elif call_style == 1:
                    torch.roll(input=x, shifts=shifts, dims=dims)
                elif call_style == 2:
                    torch.roll(x, shifts=shifts, dims=dims)
                else:
                    torch.roll(input=x, dims=dims, shifts=shifts)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
