# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.distributed.scatter
# source_yaml_count=10
# source_api_txt=/root/api_txt/torch.distributed.scatter.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.distributed as dist


def _pick_dtype(fdp):
    return fdp.PickValueInList(
        [
            torch.float32,
            torch.float64,
            torch.complex64,
            torch.complex128,
        ]
    )


def _shape_1d(fdp):
    return [fdp.ConsumeIntInRange(0, 8)]


def _make_numeric_tensor(fdp, shape, dtype):
    n = 1
    for d in shape:
        n *= d

    if dtype in (torch.float32, torch.float64):
        vals = fdp.ConsumeRegularFloatList(n)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.complex64, torch.complex128):
        vals_r = fdp.ConsumeRegularFloatList(n)
        vals_i = fdp.ConsumeRegularFloatList(n)
        vals = [complex(r, i) for r, i in zip(vals_r, vals_i)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    return torch.zeros(shape, dtype=dtype)


def _make_output_tensor(fdp, shape, dtype):
    if fdp.ConsumeBool():
        return torch.empty(shape, dtype=dtype)
    return _make_numeric_tensor(fdp, shape, dtype)


def _make_scatter_list(fdp, world_size, shape, dtype):
    same_size = fdp.ConsumeBool()
    out = []
    for _ in range(world_size):
        if same_size:
            item_shape = list(shape)
        else:
            item_shape = [fdp.ConsumeIntInRange(0, 8)]
        out.append(_make_numeric_tensor(fdp, item_shape, dtype))
    return out


def _safe_get_default_group():
    try:
        if dist.is_available() and dist.is_initialized():
            return dist.group.WORLD
    except Exception:
        return None
    return None


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        shape = _shape_1d(fdp)
        dtype = _pick_dtype(fdp)
        tensor = _make_output_tensor(fdp, shape, dtype)

        group = None
        if fdp.ConsumeBool():
            group = _safe_get_default_group()

        async_op = fdp.ConsumeBool()

        world_size = fdp.ConsumeIntInRange(1, 4)

        use_scatter_list = fdp.ConsumeBool()
        scatter_list = None
        if use_scatter_list:
            scatter_list = _make_scatter_list(fdp, world_size, shape, dtype)

        src = None
        group_src = None
        mode = fdp.ConsumeIntInRange(0, 3)
        if mode == 0:
            pass
        elif mode == 1:
            src = fdp.ConsumeIntInRange(-2, 4)
        elif mode == 2:
            group_src = fdp.ConsumeIntInRange(-2, 4)
        else:
            src = fdp.ConsumeIntInRange(-2, 4)
            group_src = fdp.ConsumeIntInRange(-2, 4)

        if fdp.ConsumeBool():
            dist.scatter(
                tensor,
                scatter_list=scatter_list,
                src=src,
                group=group,
                async_op=async_op,
                group_src=group_src,
            )
        else:
            args = [tensor]
            if fdp.ConsumeBool() or scatter_list is not None:
                args.append(scatter_list)
            kwargs = {}
            if src is not None:
                kwargs["src"] = src
            if group is not None:
                kwargs["group"] = group
            if async_op:
                kwargs["async_op"] = async_op
            if group_src is not None:
                kwargs["group_src"] = group_src
            dist.scatter(*args, **kwargs)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
