# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.div
# source_yaml_count=12
# source_api_txt=/root/api_txt/torch.div.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


DTYPES = [
    torch.float32,
    torch.float64,
    torch.int8,
    torch.uint8,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.bool,
    torch.complex64,
    torch.complex128,
]

ROUNDING_MODES = [None, "trunc", "floor"]


def _consume_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 5)
    dims = []
    for _ in range(rank):
        dims.append(fdp.ConsumeIntInRange(0, 4))
    return tuple(dims)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _safe_nonzero_scalar_for_dtype(fdp, dtype):
    if dtype == torch.bool:
        return True
    if dtype in (torch.complex64, torch.complex128):
        real = fdp.ConsumeFloatInRange(-8.0, 8.0)
        imag = fdp.ConsumeFloatInRange(-8.0, 8.0)
        if real == 0.0 and imag == 0.0:
            real = 1.0
        return complex(real, imag)
    if dtype.is_floating_point:
        v = fdp.ConsumeRegularFloat()
        if v == 0.0:
            v = 1.0
        return v
    v = fdp.ConsumeIntInRange(-8, 8)
    if v == 0:
        v = 1
    return v


def _scalar_for_dtype(fdp, dtype):
    special = fdp.ConsumeIntInRange(0, 7)
    if dtype == torch.bool:
        return fdp.ConsumeBool()
    if dtype in (torch.complex64, torch.complex128):
        if special == 0:
            return 0j
        return complex(
            fdp.ConsumeFloatInRange(-8.0, 8.0),
            fdp.ConsumeFloatInRange(-8.0, 8.0),
        )
    if dtype.is_floating_point:
        if special == 0:
            return 0.0
        if special == 1:
            return 1.0
        if special == 2:
            return -1.0
        return fdp.ConsumeFloatInRange(-32.0, 32.0)
    if special == 0:
        return 0
    if special == 1:
        return 1
    if special == 2:
        return -1
    return fdp.ConsumeIntInRange(-32, 32)


def _make_tensor_from_values(shape, dtype, values):
    if len(shape) == 0:
        if dtype == torch.bool:
            return torch.tensor(bool(values[0]), dtype=dtype)
        return torch.tensor(values[0], dtype=dtype)
    return torch.tensor(values, dtype=dtype).reshape(shape)


def _gen_values_for_dtype(fdp, count, dtype, avoid_zero=False):
    out = []
    for _ in range(count):
        if dtype == torch.bool:
            v = fdp.ConsumeBool()
            if avoid_zero and not v:
                v = True
            out.append(v)
        elif dtype in (torch.complex64, torch.complex128):
            mode = fdp.ConsumeIntInRange(0, 5)
            if mode == 0:
                v = 0j
            elif mode == 1:
                v = 1 + 0j
            elif mode == 2:
                v = -1 + 0j
            else:
                real = fdp.ConsumeFloatInRange(-8.0, 8.0)
                imag = fdp.ConsumeFloatInRange(-8.0, 8.0)
                v = complex(real, imag)
            if avoid_zero and v == 0:
                v = 1 + 0j
            out.append(v)
        elif dtype.is_floating_point:
            mode = fdp.ConsumeIntInRange(0, 7)
            if mode == 0:
                v = 0.0
            elif mode == 1:
                v = 1.0
            elif mode == 2:
                v = -1.0
            elif mode == 3:
                v = 0.5
            elif mode == 4:
                v = -0.5
            else:
                v = fdp.ConsumeFloatInRange(-32.0, 32.0)
            if avoid_zero and v == 0.0:
                v = 1.0
            out.append(v)
        else:
            mode = fdp.ConsumeIntInRange(0, 7)
            if mode == 0:
                v = 0
            elif mode == 1:
                v = 1
            elif mode == 2:
                v = -1
            else:
                v = fdp.ConsumeIntInRange(-16, 16)
            if avoid_zero and v == 0:
                v = 1
            out.append(v)
    return out


def _make_tensor(fdp, shape=None, dtype=None, avoid_zero=False):
    if dtype is None:
        dtype = fdp.PickValueInList(DTYPES)
    if shape is None:
        shape = _consume_shape(fdp)
    count = _numel(shape)
    values = _gen_values_for_dtype(fdp, count if count > 0 else 1, dtype, avoid_zero=avoid_zero)
    return _make_tensor_from_values(shape, dtype, values)


def _broadcastable_shape(fdp, base_shape):
    if fdp.ConsumeBool():
        return base_shape
    if len(base_shape) == 0:
        return () if fdp.ConsumeBool() else (1,)
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return ()
    if mode == 1:
        return tuple(1 for _ in base_shape)
    if mode == 2:
        dims = list(base_shape)
        for i in range(len(dims)):
            if fdp.ConsumeBool():
                dims[i] = 1
        return tuple(dims)
    if mode == 3:
        suffix_len = fdp.ConsumeIntInRange(0, len(base_shape))
        suffix = list(base_shape[-suffix_len:]) if suffix_len > 0 else []
        for i in range(len(suffix)):
            if fdp.ConsumeBool():
                suffix[i] = 1
        return tuple(suffix)
    return base_shape


def _make_out_tensor(fdp, ref_shape, ref_dtype):
    if fdp.ConsumeBool():
        out_shape = ref_shape
    else:
        out_shape = _broadcastable_shape(fdp, ref_shape)
    if fdp.ConsumeBool():
        out_dtype = ref_dtype
    else:
        promotable = [torch.float32, torch.float64, torch.complex64, torch.complex128, torch.int32, torch.int64, torch.bool]
        out_dtype = fdp.PickValueInList(promotable)
    return _make_tensor(fdp, shape=out_shape, dtype=out_dtype, avoid_zero=False)


def _scalar_number(fdp):
    kind = fdp.ConsumeIntInRange(0, 4)
    if kind == 0:
        return fdp.ConsumeIntInRange(-32, 32)
    if kind == 1:
        return fdp.ConsumeFloatInRange(-32.0, 32.0)
    if kind == 2:
        return complex(
            fdp.ConsumeFloatInRange(-8.0, 8.0),
            fdp.ConsumeFloatInRange(-8.0, 8.0),
        )
    if kind == 3:
        return fdp.ConsumeBool()
    return 0


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 11)

        if mode == 0:
            a = _scalar_number(fdp)
            b = _scalar_number(fdp)
            torch.div(a, b)

        elif mode == 1:
            a = fdp.ConsumeFloatInRange(-1.0, 1.0)
            b = fdp.ConsumeFloatInRange(-1.0, 1.0)
            if b == 0.0:
                b = 1.0
            torch.div(a, b)

        elif mode == 2:
            a = fdp.ConsumeIntInRange(-1, 8)
            b = fdp.ConsumeIntInRange(-1, 8)
            torch.div(a, b)

        elif mode == 3:
            a = complex(
                fdp.ConsumeFloatInRange(-8.0, 8.0),
                fdp.ConsumeFloatInRange(-8.0, 8.0),
            )
            b = complex(
                fdp.ConsumeFloatInRange(-8.0, 8.0),
                fdp.ConsumeFloatInRange(-8.0, 8.0),
            )
            torch.div(a, b)

        elif mode == 4:
            dtype = fdp.PickValueInList(DTYPES)
            self_t = _make_tensor(fdp, dtype=dtype)
            other = _scalar_for_dtype(fdp, dtype)
            torch.div(self_t, other)

        elif mode == 5:
            dtype = fdp.PickValueInList(DTYPES)
            self_t = _make_tensor(fdp, dtype=dtype)
            other = _scalar_for_dtype(fdp, dtype)
            rounding_mode = fdp.PickValueInList(ROUNDING_MODES)
            torch.div(self_t, other, rounding_mode=rounding_mode)

        elif mode == 6:
            dtype = fdp.PickValueInList(DTYPES)
            self_t = _make_tensor(fdp, dtype=dtype)
            other = _scalar_for_dtype(fdp, dtype)
            out = _make_out_tensor(fdp, self_t.shape, self_t.dtype)
            torch.div(self_t, other, out=out)

        elif mode == 7:
            dtype = fdp.PickValueInList(DTYPES)
            self_t = _make_tensor(fdp, dtype=dtype)
            other = _scalar_for_dtype(fdp, dtype)
            rounding_mode = fdp.PickValueInList(ROUNDING_MODES)
            out = _make_out_tensor(fdp, self_t.shape, self_t.dtype)
            torch.div(self_t, other, rounding_mode=rounding_mode, out=out)

        elif mode == 8:
            dtype = fdp.PickValueInList(DTYPES)
            self_shape = _consume_shape(fdp)
            self_t = _make_tensor(fdp, shape=self_shape, dtype=dtype)
            other_shape = _broadcastable_shape(fdp, self_shape)
            avoid_zero = fdp.ConsumeBool()
            other_t = _make_tensor(fdp, shape=other_shape, dtype=dtype, avoid_zero=avoid_zero)
            torch.div(self_t, other_t)

        elif mode == 9:
            dtype = fdp.PickValueInList(DTYPES)
            self_shape = _consume_shape(fdp)
            self_t = _make_tensor(fdp, shape=self_shape, dtype=dtype)
            other_shape = _broadcastable_shape(fdp, self_shape)
            avoid_zero = fdp.ConsumeBool()
            other_t = _make_tensor(fdp, shape=other_shape, dtype=dtype, avoid_zero=avoid_zero)
            rounding_mode = fdp.PickValueInList(ROUNDING_MODES)
            torch.div(self_t, other_t, rounding_mode=rounding_mode)

        elif mode == 10:
            dtype = fdp.PickValueInList(DTYPES)
            self_shape = _consume_shape(fdp)
            self_t = _make_tensor(fdp, shape=self_shape, dtype=dtype)
            other_shape = _broadcastable_shape(fdp, self_shape)
            avoid_zero = fdp.ConsumeBool()
            other_t = _make_tensor(fdp, shape=other_shape, dtype=dtype, avoid_zero=avoid_zero)
            ref = torch.broadcast_shapes(self_t.shape, other_t.shape)
            out = _make_out_tensor(fdp, ref, torch.result_type(self_t, other_t))
            torch.div(self_t, other_t, out=out)

        else:
            dtype = fdp.PickValueInList(DTYPES)
            self_shape = _consume_shape(fdp)
            self_t = _make_tensor(fdp, shape=self_shape, dtype=dtype)
            other_shape = _broadcastable_shape(fdp, self_shape)
            avoid_zero = fdp.ConsumeBool()
            other_t = _make_tensor(fdp, shape=other_shape, dtype=dtype, avoid_zero=avoid_zero)
            rounding_mode = fdp.PickValueInList(ROUNDING_MODES)
            ref = torch.broadcast_shapes(self_t.shape, other_t.shape)
            out = _make_out_tensor(fdp, ref, torch.result_type(self_t, other_t))
            torch.div(self_t, other_t, rounding_mode=rounding_mode, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
