# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.quantization.fuse_modules
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.quantization.fuse_modules.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import copy
import torch
import torch.nn as nn


class SubBlock(nn.Module):
    def __init__(self, in_ch, out_ch, linear_in, linear_out, include_bn1d):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, kernel_size=3, stride=1, padding=1, bias=True)
        if include_bn1d:
            self.bn = nn.BatchNorm1d(linear_out)
        else:
            self.bn = nn.BatchNorm2d(out_ch)
        self.relu = nn.ReLU(inplace=False)
        self.linear = nn.Linear(linear_in, linear_out)

    def forward(self, x2d, x1d):
        y = self.conv(x2d)
        if isinstance(self.bn, nn.BatchNorm2d):
            y = self.bn(y)
        y = self.relu(y)
        z = self.linear(x1d)
        if isinstance(self.bn, nn.BatchNorm1d):
            z = self.bn(z)
        z = self.relu(z)
        return y, z


class FuseModel(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        c_in = cfg["c_in"]
        c_mid = cfg["c_mid"]
        c_out = cfg["c_out"]
        lin_in = cfg["lin_in"]
        lin_mid = cfg["lin_mid"]
        lin_out = cfg["lin_out"]

        self.conv1 = nn.Conv2d(c_in, c_mid, kernel_size=3, stride=1, padding=1, bias=cfg["bias1"])
        self.bn1 = nn.BatchNorm2d(c_mid)
        self.relu1 = nn.ReLU(inplace=cfg["relu1_inplace"])

        self.conv2 = nn.Conv2d(c_mid, c_out, kernel_size=1, stride=1, padding=0, bias=cfg["bias2"])
        self.relu2 = nn.ReLU(inplace=cfg["relu2_inplace"])

        self.linear1 = nn.Linear(lin_in, lin_mid, bias=cfg["linear_bias1"])
        self.relu3 = nn.ReLU(inplace=cfg["relu3_inplace"])

        self.bn2 = nn.BatchNorm2d(c_out)
        self.relu4 = nn.ReLU(inplace=cfg["relu4_inplace"])

        self.bn3 = nn.BatchNorm1d(lin_mid)
        self.relu5 = nn.ReLU(inplace=cfg["relu5_inplace"])

        self.submodule = SubBlock(
            c_out,
            c_out,
            lin_mid,
            lin_out,
            include_bn1d=cfg["sub_bn1d"],
        )

    def forward(self, x2d, x1d):
        y = self.relu1(self.bn1(self.conv1(x2d)))
        y = self.relu2(self.conv2(y))
        y = self.relu4(self.bn2(y))
        z = self.relu3(self.linear1(x1d))
        z = self.relu5(self.bn3(z))
        sy, sz = self.submodule(y, z)
        return sy, sz


def _build_model(fdp):
    cfg = {
        "c_in": fdp.PickValueInList([1, 2, 3, 4]),
        "c_mid": fdp.PickValueInList([1, 2, 4, 8]),
        "c_out": fdp.PickValueInList([1, 2, 4, 8]),
        "lin_in": fdp.PickValueInList([1, 2, 4, 8, 16]),
        "lin_mid": fdp.PickValueInList([1, 2, 4, 8, 16]),
        "lin_out": fdp.PickValueInList([1, 2, 4, 8, 16]),
        "bias1": fdp.ConsumeBool(),
        "bias2": fdp.ConsumeBool(),
        "linear_bias1": fdp.ConsumeBool(),
        "relu1_inplace": fdp.ConsumeBool(),
        "relu2_inplace": fdp.ConsumeBool(),
        "relu3_inplace": fdp.ConsumeBool(),
        "relu4_inplace": fdp.ConsumeBool(),
        "relu5_inplace": fdp.ConsumeBool(),
        "sub_bn1d": fdp.ConsumeBool(),
    }
    model = FuseModel(cfg)
    model.eval()
    return model


def _possible_groups():
    return [
        ["conv1", "bn1"],
        ["conv1", "bn1", "relu1"],
        ["conv2", "relu2"],
        ["linear1", "relu3"],
        ["bn2", "relu4"],
        ["bn3", "relu5"],
        ["submodule.conv", "submodule.bn"],
        ["submodule.conv", "submodule.bn", "submodule.relu"],
        ["submodule.conv", "submodule.relu"],
        ["submodule.linear", "submodule.relu"],
        ["submodule.bn", "submodule.relu"],
        ["conv1"],
        ["relu1"],
        ["conv1", "relu2"],
        ["bn1", "linear1"],
        ["missing.module"],
        ["submodule.missing", "submodule.relu"],
        ["conv1", "bn1", "relu1", "extra"],
    ]


def _build_modules_to_fuse(fdp):
    candidates = _possible_groups()
    count = fdp.ConsumeIntInRange(1, 5)
    chosen = [candidates[fdp.ConsumeIntInRange(0, len(candidates) - 1)] for _ in range(count)]

    if fdp.ConsumeBool():
        if fdp.ConsumeBool():
            return list(chosen[0])
        return chosen[0][0] if chosen[0] else []
    return chosen


def _custom_fuser_identity(mod_list):
    result = []
    for idx, mod in enumerate(mod_list):
        if idx == 0:
            result.append(mod)
        else:
            result.append(nn.Identity())
    return result


def _maybe_custom_config(fdp):
    mode = fdp.ConsumeIntInRange(0, 3)
    if mode == 0:
        return None
    if mode == 1:
        return {}
    if mode == 2:
        return {"additional_fuser_method_mapping": {}}
    return {
        "additional_fuser_method_mapping": {
            (nn.Conv2d, nn.BatchNorm2d): _custom_fuser_identity,
            (nn.Conv2d, nn.BatchNorm2d, nn.ReLU): _custom_fuser_identity,
            (nn.Conv2d, nn.ReLU): _custom_fuser_identity,
            (nn.Linear, nn.ReLU): _custom_fuser_identity,
            (nn.BatchNorm2d, nn.ReLU): _custom_fuser_identity,
            (nn.BatchNorm1d, nn.ReLU): _custom_fuser_identity,
        }
    }


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        model = _build_model(fdp)
        modules_to_fuse = _build_modules_to_fuse(fdp)
        inplace = fdp.ConsumeBool()

        fuser_mode = fdp.ConsumeIntInRange(0, 2)
        if fuser_mode == 0:
            fuser_func = torch.ao.quantization.fuse_known_modules
        elif fuser_mode == 1:
            fuser_func = _custom_fuser_identity
        else:
            fuser_func = torch.quantization.fuse_known_modules

        fuse_custom_config_dict = _maybe_custom_config(fdp)

        if fdp.ConsumeBool():
            target_model = model
        else:
            target_model = copy.deepcopy(model)

        if fdp.ConsumeBool():
            fused = torch.quantization.fuse_modules(
                target_model,
                modules_to_fuse,
                inplace=inplace,
                fuser_func=fuser_func,
                fuse_custom_config_dict=fuse_custom_config_dict,
            )
        else:
            if fdp.ConsumeBool():
                fused = torch.quantization.fuse_modules(
                    target_model,
                    modules_to_fuse,
                    inplace=inplace,
                )
            else:
                fused = torch.quantization.fuse_modules(
                    model=target_model,
                    modules_to_fuse=modules_to_fuse,
                    inplace=inplace,
                    fuser_func=fuser_func,
                    fuse_custom_config_dict=fuse_custom_config_dict,
                )

        if isinstance(fused, nn.Module) and fdp.ConsumeBool():
            fused.eval()
            n = fdp.PickValueInList([1, 2])
            h = fdp.PickValueInList([1, 2, 4, 8])
            w = fdp.PickValueInList([1, 2, 4, 8])
            x2d = torch.randn(n, model.conv1.in_channels, h, w)
            x1d = torch.randn(n, model.linear1.in_features)
            try:
                fused(x2d, x1d)
            except Exception:
                pass

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
