# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.conv3d
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.nn.functional.conv3d.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64, torch.complex64, torch.complex128])


def _small_dim(fdp, min_v=1, max_v=6):
    return fdp.ConsumeIntInRange(min_v, max_v)


def _make_triple_or_int(fdp, allow_zero=False):
    lo = 0 if allow_zero else 1
    choices = [
        0 if allow_zero else 1,
        1,
        2,
        3,
        (lo, lo, lo),
        (1, 1, 1),
        (2, 2, 2),
        (3, 3, 3),
    ]
    if allow_zero:
        choices.append((0, 0, 0))
    if fdp.ConsumeBool():
        return fdp.PickValueInList(choices)
    vals = [fdp.ConsumeIntInRange(lo, 3) for _ in range(3)]
    if fdp.ConsumeBool():
        return vals[0]
    return tuple(vals)


def _expand3(x):
    if isinstance(x, int):
        return (x, x, x)
    return tuple(x)


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype):
    numel = _numel(shape)
    if dtype.is_complex:
        real = torch.tensor(
            fdp.ConsumeFloatListInRange(numel, -10.0, 10.0), dtype=torch.float32
        ).reshape(shape)
        imag = torch.tensor(
            fdp.ConsumeFloatListInRange(numel, -10.0, 10.0), dtype=torch.float32
        ).reshape(shape)
        out = torch.complex(real, imag)
        if dtype == torch.complex128:
            out = out.to(torch.complex128)
        else:
            out = out.to(torch.complex64)
        return out
    vals = fdp.ConsumeFloatListInRange(numel, -10.0, 10.0)
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _choose_groups(fdp, cin, cout):
    divisors = [g for g in range(1, min(cin, 8) + 1) if cin % g == 0 and cout % g == 0]
    if not divisors:
        return 1
    return fdp.PickValueInList(divisors)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)

        n = _small_dim(fdp, 1, 3)
        cin = _small_dim(fdp, 1, 8)
        cout = _small_dim(fdp, 1, 8)

        groups = _choose_groups(fdp, cin, cout)
        cin_per_group = cin // groups

        stride = _make_triple_or_int(fdp, allow_zero=False)
        dilation = _make_triple_or_int(fdp, allow_zero=False)
        stride3 = _expand3(stride)
        dilation3 = _expand3(dilation)

        use_string_padding = fdp.ConsumeBool()
        if use_string_padding:
            padding = fdp.PickValueInList(["valid", "same"])
            if padding == "same":
                stride = 1 if fdp.ConsumeBool() else (1, 1, 1)
                stride3 = (1, 1, 1)
        else:
            padding = _make_triple_or_int(fdp, allow_zero=True)
        pad3 = _expand3(padding) if not isinstance(padding, str) else None

        kernel_sizes = []
        input_sizes = []
        for i in range(3):
            d = dilation3[i]
            s = stride3[i]
            if isinstance(padding, str):
                if padding == "same":
                    k = fdp.ConsumeIntInRange(1, 5)
                    inp = fdp.ConsumeIntInRange(1, 8)
                else:
                    k = fdp.ConsumeIntInRange(1, 5)
                    min_inp = d * (k - 1) + 1
                    max_inp = max(min_inp, min_inp + 6)
                    inp = fdp.ConsumeIntInRange(min_inp, max_inp)
            else:
                p = pad3[i]
                k = fdp.ConsumeIntInRange(1, 5)
                min_inp = max(1, d * (k - 1) + 1 - 2 * p)
                max_inp = max(min_inp, min_inp + s + 6)
                inp = fdp.ConsumeIntInRange(min_inp, max_inp)
            kernel_sizes.append(k)
            input_sizes.append(inp)

        in_shape = (n, cin, input_sizes[0], input_sizes[1], input_sizes[2])
        weight_shape = (cout, cin_per_group, kernel_sizes[0], kernel_sizes[1], kernel_sizes[2])

        input_tensor = _make_tensor(fdp, in_shape, dtype)
        weight_tensor = _make_tensor(fdp, weight_shape, dtype)

        if fdp.ConsumeBool():
            bias = None
        else:
            bias = _make_tensor(fdp, (cout,), dtype)

        if fdp.ConsumeBool():
            out = F.conv3d(
                input_tensor,
                weight_tensor,
                bias=bias,
                stride=stride,
                padding=padding,
                dilation=dilation,
                groups=groups,
            )
        else:
            out = F.conv3d(
                input=input_tensor,
                weight=weight_tensor,
                bias=bias,
                stride=stride,
                padding=padding,
                dilation=dilation,
                groups=groups,
            )

        if fdp.ConsumeBool():
            _ = out.shape
        if fdp.ConsumeBool():
            _ = out.numel()
        if fdp.ConsumeBool() and out.numel() > 0:
            _ = out.flatten()[0].item()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
