# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.logspace
# source_yaml_count=8
# source_api_txt=/root/api_txt/torch.logspace.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


REAL_DTYPES = [
    None,
    torch.float16,
    torch.bfloat16,
    torch.float32,
    torch.float64,
]
COMPLEX_DTYPES = [
    torch.complex64,
    torch.complex128,
]
ALL_DTYPES = REAL_DTYPES + COMPLEX_DTYPES


def _pick_scalar_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _pick_result_dtype(fdp, allow_complex):
    choices = list(REAL_DTYPES)
    if allow_complex:
        choices += COMPLEX_DTYPES
    return fdp.PickValueInList(choices)


def _small_steps(fdp):
    if fdp.ConsumeBool():
        return fdp.ConsumeIntInRange(1, 8)
    return fdp.PickValueInList([1, 2, 3, 4, 5, 8, 16, 32])


def _base_value(fdp):
    if fdp.ConsumeBool():
        return fdp.ConsumeFloatInRange(-1.0, 1.0)
    return fdp.PickValueInList([
        -10.0, -2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0, 10.0
    ])


def _scalar_value(fdp):
    if fdp.ConsumeBool():
        return fdp.ConsumeFloatInRange(-10.0, 10.0)
    return fdp.PickValueInList([
        -100.0, -10.0, -2.0, -1.0, -0.1, 0.0, 0.1, 1.0, 2.0, 10.0, 100.0
    ])


def _maybe_complex_scalar(fdp):
    if fdp.ConsumeBool():
        return _scalar_value(fdp)
    real = _scalar_value(fdp)
    imag = _scalar_value(fdp)
    return complex(real, imag)


def _make_0d_tensor(fdp, allow_complex=False):
    dtype = _pick_scalar_dtype(fdp)
    if allow_complex and fdp.ConsumeBool():
        val = _maybe_complex_scalar(fdp)
        t = torch.tensor(val)
        if t.is_complex():
            target_dtype = fdp.PickValueInList(COMPLEX_DTYPES)
            return t.to(dtype=target_dtype)
        return t.to(dtype=dtype)
    val = _scalar_value(fdp)
    return torch.tensor(val, dtype=dtype)


def _make_out_tensor(fdp, steps, allow_complex=False):
    dtype = _pick_result_dtype(fdp, allow_complex)
    if dtype is None:
        dtype = torch.get_default_dtype()
    shape = [steps]
    if allow_complex and dtype in COMPLEX_DTYPES:
        real = torch.tensor(
            fdp.ConsumeRegularFloatList(steps),
            dtype=torch.float32 if dtype == torch.complex64 else torch.float64,
        )
        imag = torch.tensor(
            fdp.ConsumeRegularFloatList(steps),
            dtype=torch.float32 if dtype == torch.complex64 else torch.float64,
        )
        return torch.complex(real, imag).to(dtype=dtype)
    vals = fdp.ConsumeRegularFloatList(steps)
    return torch.tensor(vals, dtype=dtype)


def _call_default_overload(fdp):
    allow_complex = fdp.ConsumeBool()
    start = _maybe_complex_scalar(fdp) if allow_complex else _scalar_value(fdp)
    end = _maybe_complex_scalar(fdp) if allow_complex else _scalar_value(fdp)
    steps = _small_steps(fdp)
    base = _base_value(fdp)
    kwargs = {}

    dtype = _pick_result_dtype(fdp, allow_complex)
    if dtype is not None:
        kwargs["dtype"] = dtype

    if fdp.ConsumeBool():
        kwargs["layout"] = torch.strided
    if fdp.ConsumeBool():
        kwargs["device"] = torch.device("cpu")
    if fdp.ConsumeBool():
        kwargs["requires_grad"] = fdp.ConsumeBool()

    return torch.logspace(start, end, steps, base=base, **kwargs)


def _call_out_overload(fdp):
    allow_complex = fdp.ConsumeBool()
    start = _maybe_complex_scalar(fdp) if allow_complex else _scalar_value(fdp)
    end = _maybe_complex_scalar(fdp) if allow_complex else _scalar_value(fdp)
    steps = _small_steps(fdp)
    base = _base_value(fdp)
    out = _make_out_tensor(fdp, steps, allow_complex=allow_complex)
    return torch.logspace(start, end, steps, base=base, out=out)


def _call_tensor_scalar(fdp, use_out):
    end = _scalar_value(fdp)
    steps = _small_steps(fdp)
    base = _base_value(fdp)
    start = _make_0d_tensor(fdp, allow_complex=False)

    if use_out:
        out = _make_out_tensor(fdp, steps, allow_complex=False)
        return torch.logspace(start, end, steps, base=base, out=out)

    kwargs = {}
    dtype = _pick_result_dtype(fdp, allow_complex=False)
    if dtype is not None:
        kwargs["dtype"] = dtype
    if fdp.ConsumeBool():
        kwargs["layout"] = torch.strided
    if fdp.ConsumeBool():
        kwargs["device"] = torch.device("cpu")
    if fdp.ConsumeBool():
        kwargs["requires_grad"] = fdp.ConsumeBool()
    return torch.logspace(start, end, steps, base=base, **kwargs)


def _call_scalar_tensor(fdp, use_out):
    start = _scalar_value(fdp)
    steps = _small_steps(fdp)
    base = _base_value(fdp)
    end = _make_0d_tensor(fdp, allow_complex=False)

    if use_out:
        out = _make_out_tensor(fdp, steps, allow_complex=False)
        return torch.logspace(start, end, steps, base=base, out=out)

    kwargs = {}
    dtype = _pick_result_dtype(fdp, allow_complex=False)
    if dtype is not None:
        kwargs["dtype"] = dtype
    if fdp.ConsumeBool():
        kwargs["layout"] = torch.strided
    if fdp.ConsumeBool():
        kwargs["device"] = torch.device("cpu")
    if fdp.ConsumeBool():
        kwargs["requires_grad"] = fdp.ConsumeBool()
    return torch.logspace(start, end, steps, base=base, **kwargs)


def _call_tensor_tensor(fdp, use_out):
    steps = _small_steps(fdp)
    base = _base_value(fdp)
    allow_complex = fdp.ConsumeBool()
    start = _make_0d_tensor(fdp, allow_complex=allow_complex)
    end = _make_0d_tensor(fdp, allow_complex=allow_complex)

    if use_out:
        out = _make_out_tensor(fdp, steps, allow_complex=allow_complex)
        return torch.logspace(start, end, steps, base=base, out=out)

    kwargs = {}
    dtype = _pick_result_dtype(fdp, allow_complex)
    if dtype is not None:
        kwargs["dtype"] = dtype
    if fdp.ConsumeBool():
        kwargs["layout"] = torch.strided
    if fdp.ConsumeBool():
        kwargs["device"] = torch.device("cpu")
    if fdp.ConsumeBool():
        kwargs["requires_grad"] = fdp.ConsumeBool()
    return torch.logspace(start, end, steps, base=base, **kwargs)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 5)
        if mode == 0:
            result = _call_default_overload(fdp)
        elif mode == 1:
            result = _call_out_overload(fdp)
        elif mode == 2:
            result = _call_tensor_scalar(fdp, use_out=False)
        elif mode == 3:
            result = _call_tensor_scalar(fdp, use_out=True)
        elif mode == 4:
            result = _call_scalar_tensor(fdp, use_out=fdp.ConsumeBool())
        else:
            result = _call_tensor_tensor(fdp, use_out=fdp.ConsumeBool())

        if isinstance(result, torch.Tensor):
            _ = result.numel()
            if result.numel() > 0:
                _ = result.reshape(-1)[0].item()
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
