# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.conj
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.conj.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_rank(fdp):
    return fdp.PickValueInList([0, 1, 2, 3, 4, 5])


def _make_shape_for_rank(fdp, rank):
    if rank == 0:
        return ()
    ranges = [
        [0, 1, 2, 3, 4, 8],
        [0, 1, 2, 4, 8, 16],
        [0, 1, 2, 4, 8, 16],
        [0, 1, 2, 4, 8, 16],
        [0, 1, 2, 4, 8, 16],
    ]
    shape = []
    for i in range(rank):
        shape.append(fdp.PickValueInList(ranges[min(i, len(ranges) - 1)]))
    return tuple(shape)


def _pick_dtype(fdp):
    return fdp.PickValueInList(
        [
            torch.float32,
            torch.float64,
            torch.complex64,
            torch.complex128,
            torch.int32,
            torch.int64,
            torch.bool,
        ]
    )


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_tensor(fdp, dtype, shape):
    n = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.int32, torch.int64):
        vals = []
        for _ in range(n):
            vals.append(
                fdp.PickValueInList(
                    [
                        -2,
                        -1,
                        0,
                        1,
                        2,
                        fdp.ConsumeIntInRange(-32, 32),
                    ]
                )
            )
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.float32, torch.float64):
        vals = []
        for _ in range(n):
            if fdp.ConsumeBool():
                vals.append(fdp.PickValueInList([-0.0, 0.0, 1.0, -1.0, 3.14159265]))
            else:
                vals.append(fdp.ConsumeFloatInRange(-100.0, 100.0))
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.complex64, torch.complex128):
        vals = []
        for _ in range(n):
            if fdp.ConsumeBool():
                re = fdp.PickValueInList([-0.0, 0.0, 1.0, -1.0, 2.5])
                im = fdp.PickValueInList([-0.0, 0.0, 1.0, -1.0, -2.5])
            else:
                re = fdp.ConsumeFloatInRange(-50.0, 50.0)
                im = fdp.ConsumeFloatInRange(-50.0, 50.0)
            vals.append(complex(re, im))
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    return torch.zeros(shape, dtype=torch.float32)


def _maybe_transform_input(fdp, t):
    if t.numel() == 0:
        return t
    choice = fdp.ConsumeIntInRange(0, 5)
    if choice == 0:
        return t
    if choice == 1:
        return t.transpose(0, 0)
    if choice == 2 and t.ndim >= 1:
        return t.unsqueeze(0).squeeze(0)
    if choice == 3 and t.ndim >= 1:
        return t.narrow(0, 0, t.shape[0])
    if choice == 4:
        return t.contiguous()
    return t.clone()


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        rank = _pick_rank(fdp)
        shape = _make_shape_for_rank(fdp, rank)
        dtype = _pick_dtype(fdp)

        x = _make_tensor(fdp, dtype, shape)
        x = _maybe_transform_input(fdp, x)

        if fdp.ConsumeBool() and x.dtype.is_complex:
            x = torch.resolve_conj(x)

        if fdp.ConsumeBool():
            y = torch.conj(x)
        else:
            y = torch.conj(input=x)

        if fdp.ConsumeBool():
            _ = y.is_conj()
        if fdp.ConsumeBool():
            _ = y.dtype
        if fdp.ConsumeBool():
            _ = y.shape
        if fdp.ConsumeBool():
            _ = torch.resolve_conj(y)
        if fdp.ConsumeBool():
            _ = torch.conj(y)
        if fdp.ConsumeBool():
            _ = torch.conj(torch.resolve_conj(y))

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
