# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.var
# source_yaml_count=9
# source_api_txt=/root/api_txt/torch.var.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape(fdp, min_rank=0, max_rank=4, min_dim=0, max_dim=5):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    return [fdp.ConsumeIntInRange(min_dim, max_dim) for _ in range(rank)]


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor_from_shape(fdp, shape, dtype):
    n = _numel(shape)
    if n == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(n, -10.0, 10.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 1:
        vals = [float(x) for x in fdp.ConsumeIntListInRange(n, -8, 8)]
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 2:
        base = fdp.ConsumeFloatInRange(-5.0, 5.0)
        step = fdp.ConsumeFloatInRange(-2.0, 2.0)
        vals = [base + step * i for i in range(n)]
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 3:
        vals = [0.0] * n
        if n > 0:
            vals[fdp.ConsumeIntInRange(0, n - 1)] = fdp.ConsumeFloatInRange(-100.0, 100.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 4:
        vals = []
        for _ in range(n):
            vals.append(fdp.PickValueInList([-1.0, 0.0, 1.0, 2.0, -2.0, 3.5]))
        t = torch.tensor(vals, dtype=dtype)
    else:
        vals = fdp.ConsumeFloatList(n)
        cleaned = []
        for v in vals:
            if v != v:
                cleaned.append(0.0)
            elif v == float("inf"):
                cleaned.append(1e6)
            elif v == float("-inf"):
                cleaned.append(-1e6)
            else:
                cleaned.append(v)
        t = torch.tensor(cleaned, dtype=dtype)

    return t.reshape(shape)


def _make_tensor(fdp, min_rank=0, max_rank=4):
    dtype = _pick_dtype(fdp)
    shape = _consume_shape(fdp, min_rank=min_rank, max_rank=max_rank, min_dim=0, max_dim=5)
    return _make_tensor_from_shape(fdp, shape, dtype)


def _make_named_tensor(fdp):
    rank = fdp.ConsumeIntInRange(1, 4)
    shape = [fdp.ConsumeIntInRange(0, 5) for _ in range(rank)]
    dtype = _pick_dtype(fdp)
    t = _make_tensor_from_shape(fdp, shape, dtype)
    all_names = ["N", "C", "H", "W", "D", "T"]
    names = all_names[:rank]
    return t.refine_names(*names), names


def _consume_dim(fdp, ndim):
    if fdp.ConsumeBool():
        return None

    if ndim == 0:
        return None

    mode = fdp.ConsumeIntInRange(0, 2)
    dims = list(range(-ndim, ndim))
    if mode == 0:
        return fdp.PickValueInList(dims)
    elif mode == 1:
        k = fdp.ConsumeIntInRange(1, ndim)
        chosen = []
        while len(chosen) < k:
            d = fdp.PickValueInList(dims)
            norm = d % ndim
            if norm not in [x % ndim for x in chosen]:
                chosen.append(d)
        return tuple(chosen)
    else:
        k = 1
        return (fdp.PickValueInList(dims),) if k == 1 else tuple()


def _reduced_shape(shape, dim, keepdim):
    ndim = len(shape)
    if dim is None:
        return tuple([1] * ndim) if keepdim else tuple()

    if isinstance(dim, int):
        dims = [dim]
    else:
        dims = list(dim)

    norm_dims = sorted({d % ndim for d in dims})
    if keepdim:
        out = list(shape)
        for d in norm_dims:
            out[d] = 1
        return tuple(out)

    out = [shape[i] for i in range(ndim) if i not in norm_dims]
    return tuple(out)


def _consume_correction(fdp):
    if fdp.ConsumeBool():
        return None
    return fdp.PickValueInList([-3, -1, 0, 1, 2, 3, 7])


def _consume_unbiased(fdp):
    return fdp.ConsumeBool()


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        branch = fdp.ConsumeIntInRange(0, 7)

        if branch == 0:
            size = fdp.ConsumeIntInRange(0, 8)
            dtype = _pick_dtype(fdp)
            x = _make_tensor_from_shape(fdp, [size], dtype)
            unbiased = _consume_unbiased(fdp)
            torch.var(x, unbiased)

        elif branch == 1:
            x = _make_tensor(fdp, min_rank=0, max_rank=4)
            dim = _consume_dim(fdp, x.ndim)
            unbiased = _consume_unbiased(fdp)
            keepdim = fdp.ConsumeBool()
            torch.var(x, dim, unbiased, keepdim)

        elif branch == 2:
            rank = fdp.ConsumeIntInRange(0, 4)
            shape = [fdp.ConsumeIntInRange(0, 5) for _ in range(rank)]
            dtype = _pick_dtype(fdp)
            x = _make_tensor_from_shape(fdp, shape, dtype)
            dim = _consume_dim(fdp, x.ndim)
            unbiased = _consume_unbiased(fdp)
            keepdim = fdp.ConsumeBool()
            out_shape = _reduced_shape(tuple(shape), dim, keepdim)
            out = torch.empty(out_shape, dtype=dtype)
            torch.var(x, dim, unbiased, keepdim, out=out)

        elif branch == 3:
            x = _make_tensor(fdp, min_rank=0, max_rank=4)
            dim = _consume_dim(fdp, x.ndim)
            correction = _consume_correction(fdp)
            keepdim = fdp.ConsumeBool()
            if fdp.ConsumeBool():
                torch.var(x, dim=dim, correction=correction, keepdim=keepdim)
            else:
                if dim is None:
                    torch.var(x, correction=correction, keepdim=keepdim)
                else:
                    torch.var(x, dim, correction=correction, keepdim=keepdim)

        elif branch == 4:
            rank = fdp.ConsumeIntInRange(0, 4)
            shape = [fdp.ConsumeIntInRange(0, 5) for _ in range(rank)]
            dtype = _pick_dtype(fdp)
            x = _make_tensor_from_shape(fdp, shape, dtype)
            dim = _consume_dim(fdp, x.ndim)
            correction = _consume_correction(fdp)
            keepdim = fdp.ConsumeBool()
            out_shape = _reduced_shape(tuple(shape), dim, keepdim)
            out = torch.empty(out_shape, dtype=dtype)
            torch.var(x, dim=dim, correction=correction, keepdim=keepdim, out=out)

        elif branch == 5:
            x, names = _make_named_tensor(fdp)
            dim_name = fdp.PickValueInList(names)
            unbiased = _consume_unbiased(fdp)
            keepdim = fdp.ConsumeBool()
            torch.var(x, dim_name, unbiased, keepdim)

        elif branch == 6:
            x, names = _make_named_tensor(fdp)
            dim_name = fdp.PickValueInList(names)
            correction = _consume_correction(fdp)
            keepdim = fdp.ConsumeBool()
            torch.var(x, dim_name, correction=correction, keepdim=keepdim)

        else:
            x, names = _make_named_tensor(fdp)
            dim_name = fdp.PickValueInList(names)
            use_correction = fdp.ConsumeBool()
            keepdim = fdp.ConsumeBool()
            reduced_rank = x.ndim if keepdim else max(0, x.ndim - 1)
            if keepdim:
                out_shape = tuple(1 if n == dim_name else s for n, s in zip(names, x.shape))
            else:
                out_shape = tuple(s for n, s in zip(names, x.shape) if n != dim_name)
            out = torch.empty(out_shape, dtype=x.dtype)
            if use_correction:
                correction = _consume_correction(fdp)
                torch.var(x, dim_name, correction=correction, keepdim=keepdim, out=out)
            else:
                unbiased = _consume_unbiased(fdp)
                torch.var(x, dim_name, unbiased, keepdim, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
