# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.hub.load_state_dict_from_url
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.hub.load_state_dict_from_url.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import os
import io
import hashlib
import tempfile
import urllib.parse
import urllib.request

import torch


def _consume_small_text(fdp, max_len=32):
    return fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, max_len))


def _safe_name(text, default="f"):
    filtered = "".join(ch for ch in text if ch.isalnum() or ch in ("-", "_", "."))
    filtered = filtered.strip(".")
    return filtered or default


def _make_state_obj(fdp):
    mode = fdp.ConsumeIntInRange(0, 5)
    n = fdp.ConsumeIntInRange(0, 6)

    if mode == 0:
        obj = {}
        for i in range(n):
            key = "k" + str(i) + "_" + _safe_name(_consume_small_text(fdp, 12), "x")
            length = fdp.ConsumeIntInRange(0, 8)
            vals = fdp.ConsumeFloatListInRange(length, -100.0, 100.0)
            obj[key] = torch.tensor(vals, dtype=torch.float32)
        return obj

    if mode == 1:
        obj = {}
        for i in range(n):
            key = "i" + str(i) + "_" + _safe_name(_consume_small_text(fdp, 12), "y")
            obj[key] = fdp.ConsumeIntInRange(-100000, 100000)
        return obj

    if mode == 2:
        obj = {}
        for i in range(n):
            key = "m" + str(i) + "_" + _safe_name(_consume_small_text(fdp, 12), "z")
            inner = {}
            inner_count = fdp.ConsumeIntInRange(0, 4)
            for j in range(inner_count):
                ik = "inner" + str(j)
                length = fdp.ConsumeIntInRange(0, 5)
                vals = fdp.ConsumeFloatListInRange(length, -10.0, 10.0)
                inner[ik] = torch.tensor(vals, dtype=torch.float32)
            obj[key] = inner
        return obj

    if mode == 3:
        state = {}
        keys = ["weight", "bias", "running_mean", "running_var"]
        for i in range(n):
            key = f"layer{i}.{fdp.PickValueInList(keys)}"
            dims = fdp.ConsumeIntInRange(0, 3)
            shape = [fdp.ConsumeIntInRange(0, 4) for _ in range(dims)]
            numel = 1
            for s in shape:
                numel *= max(s, 1)
            vals = fdp.ConsumeFloatListInRange(min(numel, 32), -5.0, 5.0)
            if len(shape) == 0:
                state[key] = torch.tensor(fdp.ConsumeFloatInRange(-5.0, 5.0), dtype=torch.float32)
            else:
                target_numel = 1
                for s in shape:
                    target_numel *= s
                if target_numel == 0:
                    state[key] = torch.empty(shape, dtype=torch.float32)
                else:
                    if len(vals) < target_numel:
                        vals.extend([0.0] * (target_numel - len(vals)))
                    else:
                        vals = vals[:target_numel]
                    state[key] = torch.tensor(vals, dtype=torch.float32).reshape(shape)
        return state

    if mode == 4:
        return {
            "tensor": torch.tensor(
                fdp.ConsumeFloatListInRange(fdp.ConsumeIntInRange(0, 8), -1.0, 1.0),
                dtype=torch.float32,
            ),
            "flag": fdp.ConsumeBool(),
            "name": _consume_small_text(fdp, 16),
            "count": fdp.ConsumeIntInRange(-100, 100),
        }

    return {"bytes": fdp.ConsumeBytes(fdp.ConsumeIntInRange(0, 64))}


def _serialize_obj(obj, use_zip):
    buf = io.BytesIO()
    torch.save(obj, buf, _use_new_zipfile_serialization=use_zip)
    return buf.getvalue()


def _make_file_and_url(fdp, root_dir):
    obj = _make_state_obj(fdp)
    use_zip = fdp.ConsumeBool()
    payload = _serialize_obj(obj, use_zip=use_zip)

    need_hash_name = fdp.ConsumeBool()
    ext = fdp.PickValueInList([".pth", ".pt", ".bin", ".ckpt", ".dat"])
    stem = _safe_name(_consume_small_text(fdp, 20), "model")
    actual_name = stem + ext

    if need_hash_name:
        digest_len = fdp.ConsumeIntInRange(8, 16)
        digest = hashlib.sha256(payload).hexdigest()[:digest_len]
        actual_name = f"{stem}-{digest}{ext}"

    file_dir = os.path.join(root_dir, "src")
    os.makedirs(file_dir, exist_ok=True)
    actual_path = os.path.join(file_dir, actual_name)
    with open(actual_path, "wb") as f:
        f.write(payload)

    url_style = fdp.ConsumeIntInRange(0, 3)
    if url_style == 0:
        url = urllib.parse.urljoin("file:", urllib.request.pathname2url(actual_path))
    elif url_style == 1:
        quoted = urllib.request.pathname2url(actual_path)
        url = "file://" + quoted
    elif url_style == 2:
        url = "file://localhost" + urllib.request.pathname2url(actual_path)
    else:
        url = urllib.parse.urljoin("file:", urllib.request.pathname2url(actual_path))
        tail = _consume_small_text(fdp, 8)
        if tail:
            url += "?" + urllib.parse.quote(tail)

    return url, actual_name


def _make_model_dir(fdp, root_dir):
    choice = fdp.ConsumeIntInRange(0, 3)
    if choice == 0:
        return None
    if choice == 1:
        d = os.path.join(root_dir, "model_" + _safe_name(_consume_small_text(fdp, 12), "a"))
        os.makedirs(d, exist_ok=True)
        return d
    if choice == 2:
        nested = os.path.join(
            root_dir,
            "nested",
            _safe_name(_consume_small_text(fdp, 8), "b"),
            _safe_name(_consume_small_text(fdp, 8), "c"),
        )
        os.makedirs(nested, exist_ok=True)
        return nested
    return ""


def _make_map_location(fdp):
    choice = fdp.ConsumeIntInRange(0, 7)
    if choice == 0:
        return None
    if choice == 1:
        return "cpu"
    if choice == 2:
        return torch.device("cpu")
    if choice == 3:
        return {"cpu": "cpu"}
    if choice == 4:
        return {"cuda:0": "cpu"}
    if choice == 5:
        return {}
    if choice == 6:
        def identity(storage, loc):
            return storage
        return identity

    def maybe_none(storage, loc):
        if isinstance(loc, str) and "cuda" in loc:
            return storage
        return None
    return maybe_none


def _make_file_name(fdp, actual_name):
    choice = fdp.ConsumeIntInRange(0, 4)
    if choice == 0:
        return None
    if choice == 1:
        return actual_name
    if choice == 2:
        stem, ext = os.path.splitext(actual_name)
        return stem + "_alt" + ext
    if choice == 3:
        return ""
    return _safe_name(_consume_small_text(fdp, 24), "custom") + os.path.splitext(actual_name)[1]


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            url, actual_name = _make_file_and_url(fdp, tmpdir)
            model_dir = _make_model_dir(fdp, tmpdir)
            map_location = _make_map_location(fdp)
            progress = fdp.ConsumeBool()
            check_hash = fdp.ConsumeBool()
            file_name = _make_file_name(fdp, actual_name)
            weights_only = fdp.ConsumeBool()

            call_style = fdp.ConsumeIntInRange(0, 2)
            if call_style == 0:
                torch.hub.load_state_dict_from_url(
                    url,
                    model_dir=model_dir,
                    map_location=map_location,
                    progress=progress,
                    check_hash=check_hash,
                    file_name=file_name,
                    weights_only=weights_only,
                )
            elif call_style == 1:
                torch.hub.load_state_dict_from_url(
                    url,
                    model_dir,
                    map_location,
                    progress,
                    check_hash,
                    file_name,
                    weights_only,
                )
            else:
                kwargs = {}
                if fdp.ConsumeBool():
                    kwargs["model_dir"] = model_dir
                if fdp.ConsumeBool():
                    kwargs["map_location"] = map_location
                if fdp.ConsumeBool():
                    kwargs["progress"] = progress
                if fdp.ConsumeBool():
                    kwargs["check_hash"] = check_hash
                if fdp.ConsumeBool():
                    kwargs["file_name"] = file_name
                if fdp.ConsumeBool():
                    kwargs["weights_only"] = weights_only
                torch.hub.load_state_dict_from_url(url, **kwargs)
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
