# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.autograd.functional.vhp
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.autograd.functional.vhp.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_float_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _small_shape_for_rank(fdp, rank):
    if rank <= 0:
        return ()
    dims = []
    for _ in range(rank):
        dims.append(fdp.ConsumeIntInRange(1, 4))
    return tuple(dims)


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor_from_shape(fdp, shape, dtype, requires_grad=True):
    total = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(total, -3.0, 3.0)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 1:
        vals = fdp.ConsumeRegularFloatList(total)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 2:
        vals = [float(x) for x in fdp.ConsumeIntListInRange(total, -5, 5)]
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 3:
        base = fdp.ConsumeFloatInRange(-2.0, 2.0)
        step = fdp.ConsumeFloatInRange(-1.0, 1.0)
        vals = [base + step * i for i in range(total)]
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 4:
        t = torch.zeros(shape, dtype=dtype)
        if total > 0:
            idx = fdp.ConsumeIntInRange(0, total - 1)
            flat = t.reshape(-1)
            flat[idx] = fdp.ConsumeFloatInRange(-10.0, 10.0)
    else:
        t = torch.ones(shape, dtype=dtype) * fdp.ConsumeFloatInRange(-2.0, 2.0)

    t.requires_grad_(requires_grad)
    return t


def _unary_func_factory(fdp):
    mode = fdp.ConsumeIntInRange(0, 11)
    c1 = fdp.ConsumeFloatInRange(-3.0, 3.0)
    c2 = fdp.ConsumeFloatInRange(-3.0, 3.0)

    def func(x):
        if mode == 0:
            y = x.pow(2).sum()
        elif mode == 1:
            y = x.pow(3).sum()
        elif mode == 2:
            y = (torch.sin(x) + x.pow(2)).sum()
        elif mode == 3:
            y = (torch.exp(x.clamp(-5, 5)) + c1 * x).sum()
        elif mode == 4:
            y = (torch.log1p(x.abs()) + x.pow(2)).sum()
        elif mode == 5:
            y = (torch.tanh(x) * x).sum()
        elif mode == 6:
            y = (torch.relu(x) + x.pow(2)).sum()
        elif mode == 7:
            y = ((x + c1).pow(2) + (x * c2).cos()).sum()
        elif mode == 8:
            y = (x.flatten().matmul(x.flatten()) + x.sum() * c1)
        elif mode == 9:
            y = (x.mean() + x.pow(2).sum())
        elif mode == 10:
            y = (x * 0).sum()
        else:
            y = (x.reshape(-1)[: max(1, x.numel() // 2)].pow(2).sum())
        return y.reshape(())

    return func


def _binary_func_factory(fdp):
    mode = fdp.ConsumeIntInRange(0, 11)
    c1 = fdp.ConsumeFloatInRange(-3.0, 3.0)
    c2 = fdp.ConsumeFloatInRange(-3.0, 3.0)

    def func(x, y):
        if mode == 0:
            out = (2.0 * x.pow(2) + 3.0 * y.pow(2)).sum()
        elif mode == 1:
            out = (x * y + x.pow(2) - y.pow(3)).sum()
        elif mode == 2:
            out = (torch.sin(x) + torch.cos(y) + x * y).sum()
        elif mode == 3:
            out = (torch.exp(x.clamp(-5, 5)) + torch.log1p(y.abs()) + x * c1).sum()
        elif mode == 4:
            out = ((x + y).pow(2) + c2 * (x - y)).sum()
        elif mode == 5:
            out = (torch.tanh(x * y) + x.pow(2)).sum()
        elif mode == 6:
            out = (x.sum() * y.sum() + x.pow(2).sum() + y.pow(2).sum())
        elif mode == 7:
            out = ((x.flatten() * y.flatten()).sum() + x.mean() * c1 + y.mean() * c2)
        elif mode == 8:
            out = (x.pow(2).sum())
        elif mode == 9:
            out = (y.pow(2).sum())
        elif mode == 10:
            out = ((x * 0) + (y * 0)).sum()
        else:
            out = (torch.relu(x) + torch.sigmoid(y) + x * y).sum()
        return out.reshape(())

    return func


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        create_graph = fdp.ConsumeBool()
        strict = fdp.ConsumeBool()
        use_tuple_inputs = fdp.ConsumeBool()

        if use_tuple_inputs:
            tuple_len = fdp.ConsumeIntInRange(2, 3)
            dtype = _pick_float_dtype(fdp)
            inputs = []
            v = []
            for _ in range(tuple_len):
                rank = fdp.ConsumeIntInRange(1, 5)
                shape = _small_shape_for_rank(fdp, rank)
                inp = _make_tensor_from_shape(fdp, shape, dtype, requires_grad=True)
                inputs.append(inp)

                v_mode = fdp.ConsumeIntInRange(0, 4)
                if v_mode == 0:
                    vv = torch.zeros_like(inp)
                elif v_mode == 1:
                    vv = torch.ones_like(inp)
                elif v_mode == 2:
                    vv = _make_tensor_from_shape(fdp, shape, dtype, requires_grad=False)
                elif v_mode == 3:
                    vv = inp.detach().clone()
                else:
                    vv = torch.full_like(inp, fdp.ConsumeFloatInRange(-2.0, 2.0))
                v.append(vv)

            func = _binary_func_factory(fdp) if tuple_len == 2 else (
                lambda a, b, c: (a.pow(2).sum() + b.pow(3).sum() + (a * b).sum() + c.pow(2).sum()).reshape(())
            )

            inputs_arg = tuple(inputs)
            v_arg = None if fdp.ConsumeBool() else tuple(v)

            if v_arg is None:
                torch.autograd.functional.vhp(
                    func,
                    inputs_arg,
                    create_graph=create_graph,
                    strict=strict,
                )
            else:
                if fdp.ConsumeBool():
                    torch.autograd.functional.vhp(
                        func,
                        inputs_arg,
                        v=v_arg,
                        create_graph=create_graph,
                        strict=strict,
                    )
                else:
                    torch.autograd.functional.vhp(func, inputs_arg, v_arg, create_graph, strict)
        else:
            rank = fdp.ConsumeIntInRange(1, 5)
            shape = _small_shape_for_rank(fdp, rank)
            dtype = _pick_float_dtype(fdp)
            inp = _make_tensor_from_shape(fdp, shape, dtype, requires_grad=True)
            func = _unary_func_factory(fdp)

            can_omit_v = inp.numel() == 1
            omit_v = can_omit_v and fdp.ConsumeBool()

            if omit_v:
                if fdp.ConsumeBool():
                    torch.autograd.functional.vhp(
                        func,
                        inp,
                        create_graph=create_graph,
                        strict=strict,
                    )
                else:
                    torch.autograd.functional.vhp(func, inp, None, create_graph, strict)
            else:
                v_mode = fdp.ConsumeIntInRange(0, 4)
                if v_mode == 0:
                    vv = torch.zeros_like(inp)
                elif v_mode == 1:
                    vv = torch.ones_like(inp)
                elif v_mode == 2:
                    vv = _make_tensor_from_shape(fdp, shape, dtype, requires_grad=False)
                elif v_mode == 3:
                    vv = inp.detach().clone()
                else:
                    vv = torch.full_like(inp, fdp.ConsumeFloatInRange(-2.0, 2.0))

                if fdp.ConsumeBool():
                    torch.autograd.functional.vhp(
                        func,
                        inp,
                        v=vv,
                        create_graph=create_graph,
                        strict=strict,
                    )
                else:
                    torch.autograd.functional.vhp(func, inp, vv, create_graph, strict)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
