# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.prune.identity
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.prune.identity.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import copy
import torch
import torch.nn as nn
import torch.nn.utils.prune as prune


def _consume_shape(fdp, min_rank=0, max_rank=4, min_dim=0, max_dim=6):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    return [fdp.ConsumeIntInRange(min_dim, max_dim) for _ in range(rank)]


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _tensor_from_shape(fdp, shape, dtype):
    if dtype.is_floating_point:
        total = max(1, _numel(shape))
        vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
        t = torch.tensor(vals, dtype=dtype)
        if len(shape) == 0:
            return t.reshape(())
        return t.reshape(shape)
    if dtype == torch.bool:
        total = max(1, _numel(shape))
        vals = [fdp.ConsumeBool() for _ in range(total)]
        t = torch.tensor(vals, dtype=dtype)
        if len(shape) == 0:
            return t.reshape(())
        return t.reshape(shape)
    total = max(1, _numel(shape))
    vals = fdp.ConsumeIntListInRange(total, -20, 20)
    t = torch.tensor(vals, dtype=dtype)
    if len(shape) == 0:
        return t.reshape(())
    return t.reshape(shape)


class FuzzModule(nn.Module):
    def __init__(self, fdp):
        super().__init__()
        self._param_names = []

        # Common realistic module parameters
        if fdp.ConsumeBool():
            in_features = fdp.ConsumeIntInRange(1, 8)
            out_features = fdp.ConsumeIntInRange(1, 8)
            bias = fdp.ConsumeBool()
            self.linear = nn.Linear(in_features, out_features, bias=bias)
            self._param_names.extend(["linear.weight"])
            if bias:
                self._param_names.extend(["linear.bias"])

        if fdp.ConsumeBool():
            num_embeddings = fdp.ConsumeIntInRange(1, 16)
            embedding_dim = fdp.ConsumeIntInRange(1, 8)
            self.embedding = nn.Embedding(num_embeddings, embedding_dim)
            self._param_names.extend(["embedding.weight"])

        if fdp.ConsumeBool():
            num_features = fdp.ConsumeIntInRange(1, 8)
            affine = fdp.ConsumeBool()
            self.bn1 = nn.BatchNorm1d(num_features, affine=affine)
            if affine:
                self._param_names.extend(["bn1.weight", "bn1.bias"])

        # Custom direct parameters of varied shapes/dtypes
        extra_count = fdp.ConsumeIntInRange(0, 4)
        for i in range(extra_count):
            pname = f"p{i}"
            shape = _consume_shape(fdp, min_rank=0, max_rank=4, min_dim=0, max_dim=5)
            if _numel(shape) > 128:
                shape = shape[:2]
                while _numel(shape) > 128 and shape:
                    shape[-1] = max(0, min(shape[-1], 4))
            dtype = fdp.PickValueInList([
                torch.float32,
                torch.float64,
                torch.float16,
                torch.int64,
                torch.int32,
                torch.bool,
            ])
            tensor = _tensor_from_shape(fdp, shape, dtype)
            self.register_parameter(pname, nn.Parameter(tensor, requires_grad=tensor.is_floating_point()))
            self._param_names.append(pname)

        # Ensure at least one parameter exists
        if not self._param_names:
            in_features = fdp.ConsumeIntInRange(1, 8)
            out_features = fdp.ConsumeIntInRange(1, 8)
            bias = fdp.ConsumeBool()
            self.linear = nn.Linear(in_features, out_features, bias=bias)
            self._param_names.extend(["linear.weight"])
            if bias:
                self._param_names.extend(["linear.bias"])


def _candidate_names(module):
    names = [name for name, _ in module.named_parameters(recurse=True)]
    extra = []
    for n in names:
        extra.extend([
            "",
            n + "_orig",
            n + "_mask",
            n + ".bad",
            "weight",
            "bias",
            "nonexistent",
        ])
    return names + extra


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        module = FuzzModule(fdp)

        if fdp.ConsumeBool():
            candidates = _candidate_names(module)
            name = fdp.PickValueInList(candidates if candidates else ["weight"])
        else:
            name = fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 16))

        # Sometimes prune a copy first to exercise repeated-pruning paths
        if fdp.ConsumeBool():
            module2 = copy.deepcopy(module)
            names2 = [n for n, _ in module2.named_parameters(recurse=True)]
            if names2:
                try:
                    prune.identity(module2, fdp.PickValueInList(names2))
                except (
                    RuntimeError,
                    TypeError,
                    ValueError,
                    IndexError,
                    AssertionError,
                    NotImplementedError,
                ):
                    pass
                except Exception:
                    pass

        if fdp.ConsumeBool():
            result = prune.identity(module=module, name=name)
        else:
            result = prune.identity(module, name)

        if isinstance(result, nn.Module):
            # Touch resulting attributes to exercise post-pruning object state
            attr_variants = [name, name + "_orig", name + "_mask"]
            for attr in attr_variants:
                parts = attr.split(".")
                obj = result
                ok = True
                for part in parts:
                    if not hasattr(obj, part):
                        ok = False
                        break
                    obj = getattr(obj, part)
                if ok and torch.is_tensor(obj):
                    _ = obj.shape
                    _ = obj.numel()

            # Optionally prune again on available remaining parameters
            if fdp.ConsumeBool():
                names_after = [n for n, _ in result.named_parameters(recurse=True)]
                if names_after:
                    prune.identity(result, fdp.PickValueInList(names_after))

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
