# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.manual_seed
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.manual_seed.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


INT64_MIN = -(1 << 63)
UINT64_MAX = (1 << 64) - 1


def _consume_seed(fdp):
    mode = fdp.ConsumeIntInRange(0, 7)
    if mode == 0:
        return fdp.ConsumeIntInRange(-1, 8)
    if mode == 1:
        return fdp.PickValueInList([
            INT64_MIN,
            INT64_MIN + 1,
            -1,
            0,
            1,
            2,
            7,
            8,
            9,
            (1 << 31) - 1,
            1 << 31,
            (1 << 32) - 1,
            1 << 32,
            (1 << 63) - 1,
            UINT64_MAX - 1,
            UINT64_MAX,
        ])
    if mode == 2:
        return fdp.ConsumeInt(8)
    if mode == 3:
        return fdp.ConsumeUInt(8)
    if mode == 4:
        return int(fdp.ConsumeInt(4))
    if mode == 5:
        return int(fdp.ConsumeUInt(4))
    if mode == 6:
        base = fdp.PickValueInList([0, 1, -1, INT64_MIN, UINT64_MAX])
        delta = fdp.ConsumeIntInRange(-16, 16)
        return base + delta
    return fdp.ConsumeIntInRange(INT64_MIN, min(INT64_MIN + 4096, UINT64_MAX))


def _make_generator(fdp):
    device = "cpu"
    if hasattr(torch, "cuda") and torch.cuda.is_available() and fdp.ConsumeBool():
        try:
            count = torch.cuda.device_count()
            if count > 0:
                idx = fdp.ConsumeIntInRange(0, count - 1)
                device = f"cuda:{idx}"
        except Exception:
            device = "cpu"
    return torch.Generator(device=device)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        seed = _consume_seed(fdp)

        if fdp.ConsumeBool():
            gen = torch.manual_seed(seed)
        else:
            gen = _make_generator(fdp)
            if fdp.ConsumeBool():
                gen = gen.manual_seed(seed)
            else:
                gen.manual_seed(seed)

        if fdp.ConsumeBool():
            shape_rank = fdp.ConsumeIntInRange(0, 4)
            shape = [fdp.ConsumeIntInRange(0, 4) for _ in range(shape_rank)]
            if fdp.ConsumeBool():
                torch.rand(shape, generator=gen)
            else:
                out = torch.empty(shape)
                torch.rand(shape, generator=gen, out=out)

        if fdp.ConsumeBool():
            seed2 = _consume_seed(fdp)
            if fdp.ConsumeBool():
                torch.manual_seed(seed2)
            else:
                gen2 = _make_generator(fdp)
                gen2.manual_seed(seed2)
                if fdp.ConsumeBool():
                    torch.randint(
                        low=0,
                        high=max(1, fdp.ConsumeIntInRange(1, 8)),
                        size=(fdp.ConsumeIntInRange(0, 3),),
                        generator=gen2,
                    )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
