# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.hardshrink
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.nn.hardshrink.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _make_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 5)
    shape = []
    for _ in range(rank):
        if fdp.ConsumeBool():
            dim = fdp.ConsumeIntInRange(0, 4)
        else:
            dim = fdp.PickValueInList([0, 1, 2, 3, 4, 8])
        shape.append(dim)
    return tuple(shape)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _special_values(dtype):
    vals = [
        -10.0,
        -1.0,
        -0.500001,
        -0.5,
        -0.499999,
        -0.0,
        0.0,
        0.499999,
        0.5,
        0.500001,
        1.0,
        10.0,
    ]
    return torch.tensor(vals, dtype=dtype)


def _make_tensor(fdp, dtype, shape):
    n = _numel(shape)
    if n == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 4)

    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(n, -5.0, 5.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    if mode == 1:
        vals = []
        for _ in range(n):
            if fdp.ConsumeBool():
                vals.append(fdp.PickValueInList([-1.0, -0.5, 0.0, 0.5, 1.0]))
            else:
                vals.append(fdp.ConsumeFloatInRange(-1.0, 1.0))
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    if mode == 2:
        base = _special_values(dtype)
        idx = torch.tensor([fdp.ConsumeIntInRange(0, base.numel() - 1) for _ in range(n)], dtype=torch.long)
        return base.index_select(0, idx).reshape(shape)

    if mode == 3:
        if n == 1:
            return torch.tensor([fdp.ConsumeFloatInRange(-100.0, 100.0)], dtype=dtype).reshape(shape)
        start = fdp.ConsumeFloatInRange(-10.0, 0.0)
        end = fdp.ConsumeFloatInRange(0.0, 10.0)
        return torch.linspace(start, end, steps=n, dtype=dtype).reshape(shape)

    vals = []
    for _ in range(n):
        choice = fdp.ConsumeIntInRange(0, 6)
        if choice == 0:
            vals.append(0.5)
        elif choice == 1:
            vals.append(-0.5)
        elif choice == 2:
            vals.append(0.0)
        elif choice == 3:
            vals.append(1e-6)
        elif choice == 4:
            vals.append(-1e-6)
        elif choice == 5:
            vals.append(fdp.ConsumeFloatInRange(-1e-3, 1e-3))
        else:
            vals.append(fdp.ConsumeFloatInRange(-50.0, 50.0))
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _make_lambda(fdp):
    if fdp.ConsumeBool():
        return 0.5
    choice = fdp.ConsumeIntInRange(0, 9)
    if choice == 0:
        return 0.0
    if choice == 1:
        return 1e-12
    if choice == 2:
        return 1e-6
    if choice == 3:
        return 0.499999
    if choice == 4:
        return 0.500001
    if choice == 5:
        return 1.0
    if choice == 6:
        return 2.0
    if choice == 7:
        return 10.0
    if choice == 8:
        return -0.5
    return fdp.ConsumeFloatInRange(-10.0, 10.0)


def _make_out_tensor(fdp, dtype, shape):
    if fdp.ConsumeBool():
        return torch.empty(shape, dtype=dtype)

    if fdp.ConsumeBool():
        return _make_tensor(fdp, dtype, shape)

    alt_shape = _make_shape(fdp)
    return _make_tensor(fdp, dtype, alt_shape)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)
        shape = _make_shape(fdp)
        x = _make_tensor(fdp, dtype, shape)
        lambd = _make_lambda(fdp)

        branch = fdp.ConsumeIntInRange(0, 5)

        if branch == 0:
            torch.nn.hardshrink(x, lambd)
        elif branch == 1:
            torch.nn.hardshrink(x)
        elif branch == 2:
            torch.nn.functional.hardshrink(x, lambd=lambd)
        elif branch == 3:
            module = torch.nn.Hardshrink(lambd=lambd)
            module(x)
        elif branch == 4:
            out = _make_out_tensor(fdp, dtype, shape)
            torch.ops.aten.hardshrink.out(x, lambd, out=out)
        else:
            out = _make_out_tensor(fdp, dtype, shape)
            torch.ops.aten.hardshrink.out(x, lambd=lambd, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
