# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.init.constant_
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.init.constant_.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList(
        [
            torch.float32,
            torch.float64,
            torch.float16,
            torch.bfloat16,
            torch.int8,
            torch.int16,
            torch.int32,
            torch.int64,
            torch.uint8,
            torch.bool,
            torch.complex64,
            torch.complex128,
        ]
    )


def _pick_device(fdp):
    devices = ["cpu"]
    if torch.cuda.is_available():
        devices.append("cuda")
    return fdp.PickValueInList(devices)


def _consume_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 8)
    if rank == 0:
        return ()
    shape = []
    for _ in range(rank):
        if fdp.ConsumeBool():
            dim = fdp.ConsumeIntInRange(0, 8)
        else:
            dim = fdp.PickValueInList([0, 1, 2, 3, 4, 5, 7, 8, 16, 32, 64, 128])
        shape.append(dim)
    return tuple(shape)


def _make_fill_value(fdp, dtype):
    mode = fdp.ConsumeIntInRange(0, 7)

    if dtype == torch.bool:
        return fdp.ConsumeBool()

    if dtype in (torch.complex64, torch.complex128):
        if mode == 0:
            return 0j
        if mode == 1:
            return 1 + 0j
        if mode == 2:
            return -1 + 0j
        if mode == 3:
            return complex(fdp.ConsumeFloatInRange(-1.0, 1.0), fdp.ConsumeFloatInRange(-1.0, 1.0))
        if mode == 4:
            return complex(fdp.ConsumeIntInRange(-8, 8), fdp.ConsumeIntInRange(-8, 8))
        if mode == 5:
            return complex(0.0, 1.0)
        if mode == 6:
            return complex(1.0, -1.0)
        return complex(fdp.ConsumeRegularFloat(), 0.0)

    if dtype.is_floating_point:
        if mode == 0:
            return 0.0
        if mode == 1:
            return 1.0
        if mode == 2:
            return -1.0
        if mode == 3:
            return fdp.ConsumeFloatInRange(-1.0, 1.0)
        if mode == 4:
            return fdp.ConsumeFloatInRange(-1000.0, 1000.0)
        if mode == 5:
            return float(fdp.ConsumeIntInRange(-16, 16))
        if mode == 6:
            return math.pi
        return fdp.ConsumeRegularFloat()

    if dtype in (torch.int8, torch.int16, torch.int32, torch.int64, torch.uint8):
        if mode == 0:
            return 0
        if mode == 1:
            return 1
        if mode == 2:
            return -1
        if mode == 3:
            return fdp.ConsumeIntInRange(-8, 8)
        if mode == 4:
            return fdp.ConsumeIntInRange(-1024, 1024)
        if mode == 5:
            return fdp.PickValueInList([127, 128, 255, 256, -128, -129])
        if mode == 6:
            return int(fdp.ConsumeFloatInRange(-100.0, 100.0))
        return fdp.ConsumeIntInRange(-2**31, 2**31 - 1)

    return fdp.ConsumeFloatInRange(-1.0, 1.0)


def _make_tensor(fdp):
    dtype = _pick_dtype(fdp)
    device = _pick_device(fdp)
    shape = _consume_shape(fdp)

    create_mode = fdp.ConsumeIntInRange(0, 5)

    if create_mode == 0:
        t = torch.empty(shape, dtype=dtype, device=device)
    elif create_mode == 1:
        t = torch.zeros(shape, dtype=dtype, device=device)
    elif create_mode == 2:
        t = torch.ones(shape, dtype=dtype, device=device)
    elif create_mode == 3:
        if dtype == torch.bool:
            t = torch.randint(0, 2, shape, dtype=dtype, device=device)
        elif dtype in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64):
            low = fdp.ConsumeIntInRange(-8, 0)
            high = fdp.ConsumeIntInRange(1, 9)
            t = torch.randint(low, high, shape, dtype=dtype, device=device)
        elif dtype in (torch.complex64, torch.complex128):
            real_dtype = torch.float32 if dtype == torch.complex64 else torch.float64
            real = torch.randn(shape, dtype=real_dtype, device=device)
            imag = torch.randn(shape, dtype=real_dtype, device=device)
            t = torch.complex(real, imag)
        else:
            t = torch.randn(shape, dtype=dtype, device=device)
    elif create_mode == 4:
        numel = 1
        for d in shape:
            numel *= d
        if dtype == torch.bool:
            data = [fdp.ConsumeBool() for _ in range(numel)]
        elif dtype in (torch.complex64, torch.complex128):
            data = [
                complex(
                    fdp.ConsumeFloatInRange(-2.0, 2.0),
                    fdp.ConsumeFloatInRange(-2.0, 2.0),
                )
                for _ in range(numel)
            ]
        elif dtype.is_floating_point:
            data = fdp.ConsumeFloatListInRange(numel, -2.0, 2.0)
        else:
            data = [fdp.ConsumeIntInRange(-16, 16) for _ in range(numel)]
        t = torch.tensor(data, dtype=dtype, device=device).reshape(shape)
    else:
        base_shape = shape if len(shape) > 0 else (1,)
        if dtype == torch.bool:
            base = torch.randint(0, 2, base_shape, dtype=dtype, device=device)
        elif dtype in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64):
            base = torch.randint(-4, 5, base_shape, dtype=dtype, device=device)
        elif dtype in (torch.complex64, torch.complex128):
            real_dtype = torch.float32 if dtype == torch.complex64 else torch.float64
            base = torch.complex(
                torch.randn(base_shape, dtype=real_dtype, device=device),
                torch.randn(base_shape, dtype=real_dtype, device=device),
            )
        else:
            base = torch.randn(base_shape, dtype=dtype, device=device)
        t = base.as_strided(base_shape, base.stride())

    if fdp.ConsumeBool() and t.ndim > 0 and t.numel() > 0:
        idx_dim = fdp.ConsumeIntInRange(0, t.ndim - 1)
        if t.shape[idx_dim] > 1:
            slices = [slice(None)] * t.ndim
            step = fdp.PickValueInList([1, 2])
            slices[idx_dim] = slice(None, None, step)
            t = t[tuple(slices)]

    if fdp.ConsumeBool() and t.ndim >= 2:
        dim0 = fdp.ConsumeIntInRange(0, t.ndim - 1)
        dim1 = fdp.ConsumeIntInRange(0, t.ndim - 1)
        t = t.transpose(dim0, dim1)

    return t


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        tensor = _make_tensor(fdp)
        val = _make_fill_value(fdp, tensor.dtype)

        if fdp.ConsumeBool():
            out = torch.nn.init.constant_(tensor, val)
        else:
            out = torch.nn.init.constant_(tensor=tensor, val=val)

        if isinstance(out, torch.Tensor) and out.numel() > 0:
            _ = out.shape
            if out.dtype == torch.bool:
                _ = bool(out.reshape(-1)[0].item())
            elif out.dtype in (torch.complex64, torch.complex128):
                _ = out.reshape(-1)[0].item()
            else:
                _ = float(out.reshape(-1)[0].item()) if out.numel() > 0 else 0.0

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
