# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.linspace
# source_yaml_count=8
# source_api_txt=/root/api_txt/torch.linspace.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_scalar_value(fdp):
    mode = fdp.ConsumeIntInRange(0, 7)
    if mode == 0:
        return 0.0
    if mode == 1:
        return 1.0
    if mode == 2:
        return -1.0
    if mode == 3:
        return float(fdp.ConsumeIntInRange(-8, 8))
    if mode == 4:
        return fdp.ConsumeFloatInRange(-100.0, 100.0)
    if mode == 5:
        return fdp.ConsumeRegularFloat()
    if mode == 6:
        return 1e-12 if fdp.ConsumeBool() else -1e-12
    return 1e6 if fdp.ConsumeBool() else -1e6


def _pick_tensor_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _pick_result_dtype(fdp):
    dtypes = [
        None,
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
        torch.complex64,
        torch.complex128,
    ]
    return fdp.PickValueInList(dtypes)


def _make_scalar_tensor(fdp, dtype=None):
    if dtype is None:
        dtype = _pick_tensor_dtype(fdp)
    value = _pick_scalar_value(fdp)
    return torch.tensor(value, dtype=dtype)


def _make_out_tensor(fdp, steps):
    out_dtype = _pick_tensor_dtype(fdp)
    if fdp.ConsumeBool():
        return torch.empty(steps, dtype=out_dtype)
    values = [_pick_scalar_value(fdp) for _ in range(steps)]
    return torch.tensor(values, dtype=out_dtype)


def _maybe_kwargs(fdp):
    kwargs = {}
    if fdp.ConsumeBool():
        dtype = _pick_result_dtype(fdp)
        if dtype is not None:
            kwargs["dtype"] = dtype
    if fdp.ConsumeBool():
        kwargs["layout"] = torch.strided
    if fdp.ConsumeBool():
        kwargs["device"] = torch.device("cpu")
    if fdp.ConsumeBool():
        kwargs["requires_grad"] = fdp.ConsumeBool()
    return kwargs


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        steps = fdp.ConsumeIntInRange(1, 8)
        overload = fdp.ConsumeIntInRange(0, 7)

        if overload == 0:
            start = _pick_scalar_value(fdp)
            end = _pick_scalar_value(fdp)
            result = torch.linspace(start, end, steps, **_maybe_kwargs(fdp))
        elif overload == 1:
            start = _pick_scalar_value(fdp)
            end = _pick_scalar_value(fdp)
            out = _make_out_tensor(fdp, steps)
            result = torch.linspace(start, end, steps, out=out)
        elif overload == 2:
            start = _pick_scalar_value(fdp)
            end = _make_scalar_tensor(fdp)
            result = torch.linspace(start, end, steps, **_maybe_kwargs(fdp))
        elif overload == 3:
            start = _pick_scalar_value(fdp)
            end = _make_scalar_tensor(fdp)
            out = _make_out_tensor(fdp, steps)
            result = torch.linspace(start, end, steps, out=out)
        elif overload == 4:
            start = _make_scalar_tensor(fdp)
            end = _pick_scalar_value(fdp)
            result = torch.linspace(start, end, steps, **_maybe_kwargs(fdp))
        elif overload == 5:
            start = _make_scalar_tensor(fdp)
            end = _pick_scalar_value(fdp)
            out = _make_out_tensor(fdp, steps)
            result = torch.linspace(start, end, steps, out=out)
        elif overload == 6:
            start = _make_scalar_tensor(fdp)
            end = _make_scalar_tensor(fdp)
            result = torch.linspace(start, end, steps, **_maybe_kwargs(fdp))
        else:
            start = _make_scalar_tensor(fdp)
            end = _make_scalar_tensor(fdp)
            out = _make_out_tensor(fdp, steps)
            result = torch.linspace(start, end, steps, out=out)

        if isinstance(result, torch.Tensor):
            _ = result.numel()
            if result.numel() > 0:
                _ = result[0].item()
                _ = result[-1].item()
            _ = result.dtype
            _ = result.device
            _ = result.requires_grad

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
