# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.arange
# source_yaml_count=5
# source_api_txt=/root/api_txt/torch.arange.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


def _available_devices():
    devices = [None, torch.device("cpu"), "cpu"]
    if torch.cuda.is_available():
        devices.extend([torch.device("cuda"), "cuda"])
    return devices


def _pick_layout(fdp):
    layouts = [torch.strided, None]
    return fdp.PickValueInList(layouts)


def _pick_device(fdp):
    return fdp.PickValueInList(_available_devices())


def _pick_dtype(fdp):
    dtypes = [
        None,
        torch.int64,
        torch.int32,
        torch.int16,
        torch.int8,
        torch.uint8,
        torch.float64,
        torch.float32,
        torch.float16,
        torch.bfloat16,
        torch.bool,
    ]
    if hasattr(torch, "complex64"):
        dtypes.extend([torch.complex64, torch.complex128])
    return fdp.PickValueInList(dtypes)


def _consume_scalar(fdp):
    mode = fdp.ConsumeIntInRange(0, 7)
    if mode == 0:
        return fdp.ConsumeIntInRange(-32, 32)
    if mode == 1:
        return fdp.ConsumeIntInRange(-1024, 1024)
    if mode == 2:
        return fdp.ConsumeFloatInRange(-32.0, 32.0)
    if mode == 3:
        return fdp.ConsumeFloatInRange(-1024.0, 1024.0)
    if mode == 4:
        return fdp.PickValueInList([0, 1, -1, 2, -2, 5, -5, 10, -10])
    if mode == 5:
        return fdp.PickValueInList([0.0, 0.5, -0.5, 1.0, -1.0, 2.5, -2.5, 10.0, -10.0])
    if mode == 6:
        return bool(fdp.ConsumeBool())
    return fdp.ConsumeRegularFloat()


def _consume_step(fdp):
    mode = fdp.ConsumeIntInRange(0, 6)
    if mode == 0:
        return fdp.PickValueInList([-5, -2, -1, 1, 2, 5])
    if mode == 1:
        return fdp.PickValueInList([-2.5, -1.0, -0.5, 0.5, 1.0, 2.5])
    if mode == 2:
        return fdp.ConsumeIntInRange(-16, 16) or 1
    if mode == 3:
        x = fdp.ConsumeFloatInRange(-8.0, 8.0)
        return x if x != 0.0 else 1.0
    if mode == 4:
        return -1 if fdp.ConsumeBool() else 1
    if mode == 5:
        return -0.5 if fdp.ConsumeBool() else 0.5
    x = _consume_scalar(fdp)
    if x == 0 or x == 0.0:
        return 1
    return x


def _expected_len(start, end, step):
    if isinstance(start, bool):
        start = int(start)
    if isinstance(end, bool):
        end = int(end)
    if isinstance(step, bool):
        step = int(step)
    if step == 0 or step == 0.0:
        return None
    try:
        if isinstance(start, int) and isinstance(end, int) and isinstance(step, int):
            if step > 0:
                if start >= end:
                    return 0
                return (end - start + step - 1) // step
            else:
                if start <= end:
                    return 0
                return (start - end + (-step) - 1) // (-step)
        n = math.ceil((end - start) / step)
        if n < 0:
            n = 0
        if n > 256:
            n = 256
        return int(n)
    except Exception:
        return None


def _make_out_tensor(fdp, length_hint=None):
    dtype = fdp.PickValueInList([torch.float32, torch.float64])
    if length_hint is None or length_hint < 0:
        length = fdp.ConsumeIntInRange(0, 128)
    else:
        if fdp.ConsumeBool():
            length = min(max(length_hint, 0), 128)
        else:
            delta = fdp.ConsumeIntInRange(-3, 3)
            length = min(max(length_hint + delta, 0), 128)
    device = _pick_device(fdp)
    return torch.empty((length,), dtype=dtype, device=device)


def _call_and_touch(result, fdp):
    if isinstance(result, torch.Tensor):
        _ = result.numel()
        _ = result.dtype
        if result.numel() > 0:
            idx = fdp.ConsumeIntInRange(0, result.numel() - 1)
            _ = result.flatten()[idx].item()
        _ = result.clone()


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        overload = fdp.ConsumeIntInRange(0, 4)

        if overload == 0:
            end = _consume_scalar(fdp)
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["dtype"] = _pick_dtype(fdp)
            if fdp.ConsumeBool():
                kwargs["layout"] = _pick_layout(fdp)
            if fdp.ConsumeBool():
                kwargs["device"] = _pick_device(fdp)
            if fdp.ConsumeBool():
                kwargs["requires_grad"] = fdp.ConsumeBool()
            result = torch.arange(end, **kwargs)
            _call_and_touch(result, fdp)

        elif overload == 1:
            start = _consume_scalar(fdp)
            end = _consume_scalar(fdp)
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["dtype"] = _pick_dtype(fdp)
            if fdp.ConsumeBool():
                kwargs["layout"] = _pick_layout(fdp)
            if fdp.ConsumeBool():
                kwargs["device"] = _pick_device(fdp)
            if fdp.ConsumeBool():
                kwargs["requires_grad"] = fdp.ConsumeBool()
            result = torch.arange(start, end, **kwargs)
            _call_and_touch(result, fdp)

        elif overload == 2:
            start = _consume_scalar(fdp)
            end = _consume_scalar(fdp)
            step = _consume_step(fdp)
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["dtype"] = _pick_dtype(fdp)
            if fdp.ConsumeBool():
                kwargs["layout"] = _pick_layout(fdp)
            if fdp.ConsumeBool():
                kwargs["device"] = _pick_device(fdp)
            if fdp.ConsumeBool():
                kwargs["requires_grad"] = fdp.ConsumeBool()
            result = torch.arange(start, end, step, **kwargs)
            _call_and_touch(result, fdp)

        elif overload == 3:
            end = _consume_scalar(fdp)
            out = _make_out_tensor(fdp, _expected_len(0, end, 1))
            result = torch.arange(end, out=out)
            _call_and_touch(result, fdp)
            _call_and_touch(out, fdp)

        else:
            start = _consume_scalar(fdp)
            end = _consume_scalar(fdp)
            step = _consume_step(fdp)
            out = _make_out_tensor(fdp, _expected_len(start, end, step))
            if fdp.ConsumeBool():
                result = torch.arange(start, end, out=out)
            else:
                result = torch.arange(start, end, step, out=out)
            _call_and_touch(result, fdp)
            _call_and_touch(out, fdp)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
