# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.gumbel_softmax
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.functional.gumbel_softmax.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _consume_shape(fdp, rank):
    if rank == 2:
        mins_maxs = [(1, 8), (2, 64)]
    elif rank == 3:
        mins_maxs = [(1, 8), (2, 64), (2, 32)]
    elif rank == 4:
        mins_maxs = [(1, 4), (2, 32), (2, 16), (2, 16)]
    else:
        mins_maxs = [(1, 2), (2, 16), (2, 8), (2, 8), (2, 8)]

    shape = []
    for lo, hi in mins_maxs:
        shape.append(fdp.ConsumeIntInRange(lo, hi))
    return tuple(shape)


def _consume_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _make_logits(fdp):
    rank = fdp.PickValueInList([2, 3, 4, 5])
    shape = _consume_shape(fdp, rank)
    dtype = _consume_dtype(fdp)

    numel = 1
    for s in shape:
        numel *= s

    mode = fdp.ConsumeIntInRange(0, 5)

    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(numel, -20.0, 20.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 1:
        vals = fdp.ConsumeRegularFloatList(numel)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 2:
        vals = fdp.ConsumeFloatListInRange(numel, -1e-6, 1e-6)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 3:
        vals = fdp.ConsumeFloatListInRange(numel, -100.0, 100.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 4:
        base = fdp.ConsumeFloatInRange(-10.0, 10.0)
        step = fdp.ConsumeFloatInRange(-2.0, 2.0)
        vals = [base + step * i for i in range(numel)]
        t = torch.tensor(vals, dtype=dtype)
    else:
        t = torch.randn(shape, dtype=dtype)
        if fdp.ConsumeBool():
            t = t * fdp.ConsumeFloatInRange(0.0, 50.0)
        if fdp.ConsumeBool():
            t = t + fdp.ConsumeFloatInRange(-10.0, 10.0)
        return t

    return t.reshape(shape)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        logits = _make_logits(fdp)
        ndim = logits.ndim

        hard = fdp.ConsumeBool()

        tau_mode = fdp.ConsumeIntInRange(0, 5)
        if tau_mode == 0:
            tau = 0.0
        elif tau_mode == 1:
            tau = fdp.ConsumeFloatInRange(1e-12, 1e-6)
        elif tau_mode == 2:
            tau = fdp.ConsumeFloatInRange(1e-6, 0.5)
        elif tau_mode == 3:
            tau = fdp.ConsumeFloatInRange(0.5, 1.0)
        elif tau_mode == 4:
            tau = fdp.ConsumeFloatInRange(1.0, 10.0)
        else:
            tau = fdp.ConsumeFloatInRange(10.0, 100.0)

        eps_mode = fdp.ConsumeIntInRange(0, 5)
        if eps_mode == 0:
            eps = 1e-10
        elif eps_mode == 1:
            eps = fdp.ConsumeFloatInRange(1e-12, 1e-10)
        elif eps_mode == 2:
            eps = fdp.ConsumeFloatInRange(1e-10, 1e-6)
        elif eps_mode == 3:
            eps = fdp.ConsumeFloatInRange(1e-6, 1e-3)
        elif eps_mode == 4:
            eps = fdp.ConsumeFloatInRange(1e-3, 1e-1)
        else:
            eps = 0.0

        dim_choices = list(range(-ndim, ndim))
        if -1 not in dim_choices:
            dim_choices.append(-1)
        if 0 not in dim_choices:
            dim_choices.append(0)
        dim = fdp.PickValueInList(dim_choices)

        call_style = fdp.ConsumeIntInRange(0, 2)
        if call_style == 0:
            out = F.gumbel_softmax(logits, tau=tau, hard=hard, eps=eps, dim=dim)
        elif call_style == 1:
            out = F.gumbel_softmax(logits, tau, hard, eps, dim)
        else:
            out = F.gumbel_softmax(logits=logits, tau=tau, hard=hard, eps=eps, dim=dim)

        if fdp.ConsumeBool():
            _ = out.sum()
        if fdp.ConsumeBool():
            _ = out.argmax(dim=dim)
        if fdp.ConsumeBool():
            _ = torch.isfinite(out).all()
        if fdp.ConsumeBool():
            _ = out.shape

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
