# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.cartesian_prod
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.cartesian_prod.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.int32,
        torch.int64,
        torch.bool,
    ])


def _num_tensors(fdp):
    # Vary between no inputs, single input, and multiple inputs.
    return fdp.ConsumeIntInRange(0, 5)


def _length_for_tensor(fdp):
    # Keep sizes small to avoid explosive cartesian products, but include zero.
    return fdp.ConsumeIntInRange(0, 8)


def _make_values(fdp, length, dtype):
    if dtype == torch.bool:
        return [fdp.ConsumeBool() for _ in range(length)]
    if dtype.is_floating_point:
        mode = fdp.ConsumeIntInRange(0, 2)
        if mode == 0:
            return fdp.ConsumeFloatListInRange(length, -100.0, 100.0)
        elif mode == 1:
            return [float(x) for x in fdp.ConsumeIntListInRange(length, -8, 8)]
        else:
            vals = []
            for _ in range(length):
                if fdp.ConsumeBool():
                    vals.append(fdp.ConsumeRegularFloat())
                else:
                    vals.append(float(fdp.ConsumeIntInRange(-1000, 1000)))
            return vals
    return [int(x) for x in fdp.ConsumeIntListInRange(length, -100, 100)]


def _make_1d_tensor(fdp):
    dtype = _pick_dtype(fdp)
    length = _length_for_tensor(fdp)
    values = _make_values(fdp, length, dtype)
    return torch.tensor(values, dtype=dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        tensors = []
        n = _num_tensors(fdp)
        for _ in range(n):
            tensors.append(_make_1d_tensor(fdp))

        # Exercise both direct varargs API and unpacked-list style.
        if fdp.ConsumeBool():
            out = torch.cartesian_prod(*tensors)
        else:
            out = torch.cartesian_prod(*list(tensors))

        # Lightly use result to ensure materialization and additional paths.
        if isinstance(out, torch.Tensor):
            _ = out.numel()
            _ = out.shape
            if out.numel() > 0 and fdp.ConsumeBool():
                _ = out.flatten()[0].item()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
