# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.dropout2d
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.functional.dropout2d.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape_4d(fdp):
    shape_mode = fdp.ConsumeIntInRange(0, 4)
    if shape_mode == 0:
        return [1, 1, 1, 1]
    if shape_mode == 1:
        return [
            fdp.ConsumeIntInRange(1, 2),
            fdp.ConsumeIntInRange(1, 2),
            fdp.ConsumeIntInRange(1, 2),
            fdp.ConsumeIntInRange(1, 2),
        ]
    if shape_mode == 2:
        return [
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 4),
        ]
    if shape_mode == 3:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        ]
    return [
        fdp.PickValueInList([1, 2, 3, 4, 8]),
        fdp.PickValueInList([1, 2, 3, 4, 8]),
        fdp.PickValueInList([1, 2, 3, 4, 8]),
        fdp.PickValueInList([1, 2, 3, 4, 8]),
    ]


def _make_tensor(fdp, dtype, shape):
    numel = 1
    for dim in shape:
        numel *= dim

    value_mode = fdp.ConsumeIntInRange(0, 5)
    if value_mode == 0:
        t = torch.zeros(shape, dtype=dtype)
    elif value_mode == 1:
        t = torch.ones(shape, dtype=dtype)
    elif value_mode == 2:
        vals = fdp.ConsumeRegularFloatList(numel)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif value_mode == 3:
        vals = [float(fdp.ConsumeIntInRange(-3, 3)) for _ in range(numel)]
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif value_mode == 4:
        t = torch.arange(numel, dtype=dtype).reshape(shape)
        scale = fdp.ConsumeFloatInRange(-2.0, 2.0)
        bias = fdp.ConsumeFloatInRange(-2.0, 2.0)
        t = t * scale + bias
    else:
        vals = []
        for _ in range(numel):
            vals.append(fdp.PickValueInList([0.0, -0.0, 1.0, -1.0, 0.5, -0.5, 2.0, -2.0]))
        t = torch.tensor(vals, dtype=dtype).reshape(shape)

    if fdp.ConsumeBool():
        t = t.contiguous()
    else:
        t = t.clone()

    return t


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)
        shape = _consume_shape_4d(fdp)
        input_tensor = _make_tensor(fdp, dtype, shape)

        p_mode = fdp.ConsumeIntInRange(0, 4)
        if p_mode == 0:
            p = 0.0
        elif p_mode == 1:
            p = 1.0
        elif p_mode == 2:
            p = 0.5
        elif p_mode == 3:
            p = fdp.ConsumeProbability()
        else:
            p = fdp.PickValueInList([0.0, 0.01, 0.25, 0.5, 0.75, 0.99, 1.0])

        training = fdp.ConsumeBool()
        inplace = fdp.ConsumeBool()

        if inplace:
            input_tensor = input_tensor.clone()

        call_mode = fdp.ConsumeIntInRange(0, 3)
        if call_mode == 0:
            out = F.dropout2d(input_tensor, p, training, inplace)
        elif call_mode == 1:
            out = F.dropout2d(input=input_tensor, p=p, training=training, inplace=inplace)
        elif call_mode == 2:
            out = F.dropout2d(input_tensor, p=p, training=training, inplace=inplace)
        else:
            out = F.dropout2d(input=input_tensor, p=p, training=training, inplace=inplace)

        if isinstance(out, torch.Tensor):
            _ = out.shape
            _ = out.dtype
            _ = out.numel()
            if out.numel() > 0:
                _ = torch.sum(out)
                _ = torch.count_nonzero(out)
                _ = torch.isfinite(out).all()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
