# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.parallel.data_parallel
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.parallel.data_parallel.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn as nn
import torch.nn.parallel


def _consume_shape(fdp, rank):
    shape = []
    limits = [8, 16, 16, 16]
    for i in range(rank):
        shape.append(fdp.ConsumeIntInRange(1, limits[min(i, len(limits) - 1)]))
    return tuple(shape)


def _pick_dtype(fdp):
    dtypes = [
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
        torch.int8,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
    ]
    return fdp.PickValueInList(dtypes)


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype):
    total = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(total)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64):
        vals = fdp.ConsumeIntListInRange(total, -16, 16)
        if dtype == torch.uint8:
            vals = [abs(v) % 256 for v in vals]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
    return torch.tensor(vals, dtype=dtype).reshape(shape)


class IdentityModule(nn.Module):
    def forward(self, x):
        return x


class UnaryPointwiseModule(nn.Module):
    def __init__(self, op_kind):
        super().__init__()
        self.op_kind = op_kind

    def forward(self, x):
        if self.op_kind == 0:
            if x.is_floating_point():
                return torch.relu(x)
            return x
        if self.op_kind == 1:
            if x.is_floating_point():
                return torch.sigmoid(x)
            return x
        if self.op_kind == 2:
            if x.is_floating_point():
                return torch.tanh(x)
            return x
        if self.op_kind == 3:
            return x + 1
        if self.op_kind == 4:
            return x * 2
        return x.contiguous()


class ReduceExpandModule(nn.Module):
    def __init__(self, reduce_dim, keepdim):
        super().__init__()
        self.reduce_dim = reduce_dim
        self.keepdim = keepdim

    def forward(self, x):
        if x.ndim == 0:
            return x
        dim = self.reduce_dim
        if dim < 0:
            dim += x.ndim
        dim %= max(1, x.ndim)
        if x.is_floating_point() or x.dtype in (
            torch.int8,
            torch.int16,
            torch.int32,
            torch.int64,
            torch.uint8,
            torch.bool,
        ):
            y = x.sum(dim=dim, keepdim=self.keepdim)
            return y
        return x


class KwargModule(nn.Module):
    def forward(self, x, scale=1.0, bias=0.0, use_relu=False):
        y = x
        if y.is_floating_point():
            y = y * scale + bias
            if use_relu:
                y = torch.relu(y)
        else:
            if int(scale) != 0:
                y = y * int(scale)
            y = y + int(bias)
            if use_relu:
                y = torch.clamp_min(y, 0)
        return y


def _make_module(fdp, rank):
    kind = fdp.ConsumeIntInRange(0, 3)
    if kind == 0:
        return IdentityModule(), False
    if kind == 1:
        return UnaryPointwiseModule(fdp.ConsumeIntInRange(0, 5)), False
    if kind == 2:
        reduce_dim = fdp.ConsumeIntInRange(-4, 4)
        keepdim = fdp.ConsumeBool()
        return ReduceExpandModule(reduce_dim, keepdim), False
    return KwargModule(), True


def _device_obj_from_int(v):
    if v == -1:
        return -1
    return v


def _make_device_ids(fdp):
    mode = fdp.ConsumeIntInRange(0, 3)
    if mode == 0:
        return None
    count = fdp.ConsumeIntInRange(0, 4)
    ids = []
    for _ in range(count):
        raw = fdp.ConsumeIntInRange(-1, 8)
        as_device = fdp.ConsumeBool()
        if as_device:
            if raw == -1:
                ids.append(torch.device("cpu"))
            else:
                ids.append(torch.device("cuda", raw))
        else:
            ids.append(_device_obj_from_int(raw))
    return ids


def _make_output_device(fdp):
    if fdp.ConsumeBool():
        return None
    raw = fdp.ConsumeIntInRange(-1, 8)
    if fdp.ConsumeBool():
        if raw == -1:
            return torch.device("cpu")
        return torch.device("cuda", raw)
    return _device_obj_from_int(raw)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        rank = fdp.ConsumeIntInRange(1, 4)
        shape = _consume_shape(fdp, rank)
        dtype = _pick_dtype(fdp)
        x = _make_tensor(fdp, shape, dtype)

        module, supports_kwargs = _make_module(fdp, rank)
        module.eval()

        device_ids = _make_device_ids(fdp)
        output_device = _make_output_device(fdp)
        dim = fdp.ConsumeIntInRange(-4, 4)

        module_kwargs = None
        if supports_kwargs and fdp.ConsumeBool():
            module_kwargs = {
                "scale": fdp.ConsumeFloatInRange(-4.0, 4.0),
                "bias": fdp.ConsumeFloatInRange(-4.0, 4.0),
                "use_relu": fdp.ConsumeBool(),
            }

        call_style = fdp.ConsumeIntInRange(0, 2)
        if call_style == 0:
            torch.nn.parallel.data_parallel(
                module,
                x,
                device_ids=device_ids,
                output_device=output_device,
                dim=dim,
                module_kwargs=module_kwargs,
            )
        elif call_style == 1:
            kwargs = {
                "module": module,
                "inputs": x,
                "device_ids": device_ids,
                "output_device": output_device,
                "dim": dim,
            }
            if module_kwargs is not None:
                kwargs["module_kwargs"] = module_kwargs
            torch.nn.parallel.data_parallel(**kwargs)
        else:
            if module_kwargs is None:
                torch.nn.parallel.data_parallel(module, x, device_ids, output_device, dim)
            else:
                torch.nn.parallel.data_parallel(
                    module, x, device_ids, output_device, dim, module_kwargs
                )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
