# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.flip
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.flip.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _consume_shape(fdp, force_rank=None):
    if force_rank is not None:
        rank = force_rank
    else:
        rank = fdp.ConsumeIntInRange(0, 6)
    shape = []
    for _ in range(rank):
        if fdp.ConsumeBool():
            dim = fdp.ConsumeIntInRange(0, 4)
        else:
            dim = fdp.ConsumeIntInRange(0, 8)
        shape.append(dim)
    return shape


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _choose_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _make_tensor(fdp, shape, dtype):
    n = _numel(shape)
    if n == 0:
        return torch.empty(shape, dtype=dtype)

    strategy = fdp.ConsumeIntInRange(0, 5)

    if strategy == 0:
        vals = fdp.ConsumeFloatListInRange(n, -10.0, 10.0)
        t = torch.tensor(vals, dtype=dtype)
    elif strategy == 1:
        vals = fdp.ConsumeRegularFloatList(n)
        t = torch.tensor(vals, dtype=dtype)
    elif strategy == 2:
        vals = [float(fdp.ConsumeIntInRange(-16, 16)) for _ in range(n)]
        t = torch.tensor(vals, dtype=dtype)
    elif strategy == 3:
        start = fdp.ConsumeFloatInRange(-5.0, 5.0)
        step = fdp.ConsumeFloatInRange(-3.0, 3.0)
        vals = [start + step * i for i in range(n)]
        t = torch.tensor(vals, dtype=dtype)
    elif strategy == 4:
        vals = [0.0] * n
        if n > 0:
            idx = fdp.ConsumeIntInRange(0, n - 1)
            vals[idx] = fdp.ConsumeFloatInRange(-100.0, 100.0)
        t = torch.tensor(vals, dtype=dtype)
    else:
        t = torch.randn(shape, dtype=dtype)
        if fdp.ConsumeBool():
            t = t * fdp.ConsumeFloatInRange(0.0, 10.0)
        return t

    return t.reshape(shape)


def _consume_dims(fdp, rank):
    if rank == 0:
        return []

    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        count = fdp.ConsumeIntInRange(1, min(3, rank))
        dims = fdp.ConsumeIntListInRange(count, 0, rank - 1)
        return dims
    if mode == 1:
        count = fdp.ConsumeIntInRange(1, min(3, rank))
        chosen = []
        available = list(range(rank))
        for _ in range(count):
            if not available:
                break
            idx = fdp.ConsumeIntInRange(0, len(available) - 1)
            chosen.append(available.pop(idx))
        return chosen
    if mode == 2:
        if rank == 1:
            return [0]
        return list(range(rank))
    if mode == 3:
        count = fdp.ConsumeIntInRange(1, min(3, rank))
        return [fdp.ConsumeIntInRange(0, rank - 1) for _ in range(count)]
    return [fdp.ConsumeIntInRange(0, rank - 1)]


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        use_out_variant = fdp.ConsumeBool()

        if use_out_variant:
            shape = _consume_shape(fdp, force_rank=5)
            dtype = _choose_dtype(fdp)
            x = _make_tensor(fdp, shape, dtype)
            dims = _consume_dims(fdp, x.ndim)

            if fdp.ConsumeBool():
                out_dtype = dtype
            else:
                out_dtype = _choose_dtype(fdp)

            if fdp.ConsumeBool():
                out_shape = list(shape)
            else:
                out_shape = _consume_shape(fdp, force_rank=5)

            out = _make_tensor(fdp, out_shape, out_dtype)

            if fdp.ConsumeBool():
                result = torch.flip(x, dims, out=out)
            else:
                result = torch.ops.aten.flip.out(x, dims, out=out)

            _ = result.shape
        else:
            shape = _consume_shape(fdp)
            dtype = _choose_dtype(fdp)
            x = _make_tensor(fdp, shape, dtype)
            dims = _consume_dims(fdp, x.ndim)

            if fdp.ConsumeBool():
                result = torch.flip(x, dims)
            else:
                result = torch.ops.aten.flip.default(x, dims)

            _ = result.shape
            if x.ndim > 0 and fdp.ConsumeBool():
                valid_dims = []
                for d in dims:
                    if 0 <= d < x.ndim and d not in valid_dims:
                        valid_dims.append(d)
                if valid_dims:
                    again = torch.flip(result, tuple(valid_dims))
                    _ = again.shape

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
