# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.sqrt
# source_yaml_count=6
# source_api_txt=/root/api_txt/torch.sqrt.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


DTYPES = [
    torch.float32,
    torch.float64,
    torch.float16,
    torch.bfloat16,
    torch.complex64,
    torch.complex128,
    torch.int32,
    torch.int64,
    torch.bool,
]


def _pick_shape_1d(fdp):
    n = fdp.ConsumeIntInRange(0, 8)
    return (n,)


def _make_base_values(fdp, numel):
    mode = fdp.ConsumeIntInRange(0, 6)
    vals = []
    for _ in range(numel):
        if mode == 0:
            vals.append(fdp.ConsumeFloatInRange(-1.0, 1.0))
        elif mode == 1:
            vals.append(fdp.ConsumeFloatInRange(0.0, 100.0))
        elif mode == 2:
            vals.append(fdp.ConsumeFloatInRange(-100.0, 100.0))
        elif mode == 3:
            vals.append(fdp.PickValueInList([0.0, -0.0, 1.0, 2.0, 4.0, 9.0, -1.0, -4.0]))
        elif mode == 4:
            vals.append(fdp.ConsumeRegularFloat())
        elif mode == 5:
            vals.append(float(fdp.ConsumeIntInRange(-8, 8)))
        else:
            vals.append(fdp.PickValueInList([1e-12, 1e-6, 0.5, 1.5, 16.0, 1e6, -1e-12, -16.0]))
    return vals


def _make_tensor(fdp, dtype=None, shape=None):
    if dtype is None:
        dtype = fdp.PickValueInList(DTYPES)
    if shape is None:
        shape = _pick_shape_1d(fdp)

    numel = 1
    for d in shape:
        numel *= d

    if dtype in (torch.float16, torch.bfloat16, torch.float32, torch.float64):
        vals = _make_base_values(fdp, numel)
        t = torch.tensor(vals, dtype=torch.float64).reshape(shape).to(dtype=dtype)
        return t

    if dtype in (torch.complex64, torch.complex128):
        real_vals = _make_base_values(fdp, numel)
        imag_vals = _make_base_values(fdp, numel)
        complex_vals = [complex(r, i) for r, i in zip(real_vals, imag_vals)]
        return torch.tensor(complex_vals, dtype=dtype).reshape(shape)

    if dtype in (torch.int32, torch.int64):
        mode = fdp.ConsumeIntInRange(0, 2)
        if mode == 0:
            vals = [fdp.ConsumeIntInRange(-8, 8) for _ in range(numel)]
        elif mode == 1:
            vals = [fdp.PickValueInList([-1, 0, 1, 2, 4, 9, 16, 127, -128]) for _ in range(numel)]
        else:
            vals = [int(math.floor(v)) for v in _make_base_values(fdp, numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    vals = _make_base_values(fdp, numel)
    return torch.tensor(vals).reshape(shape)


def _make_out_tensor(fdp, inp):
    compatible_dtype = fdp.ConsumeBool()
    if compatible_dtype:
        out_dtype = inp.dtype
    else:
        if inp.is_complex():
            out_dtype = fdp.PickValueInList([torch.complex64, torch.complex128])
        elif inp.is_floating_point():
            out_dtype = fdp.PickValueInList([torch.float16, torch.bfloat16, torch.float32, torch.float64])
        else:
            out_dtype = fdp.PickValueInList(DTYPES)

    if fdp.ConsumeBool():
        shape = tuple(inp.shape)
    else:
        shape = _pick_shape_1d(fdp)

    return _make_tensor(fdp, dtype=out_dtype, shape=shape)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 5)

        if mode == 0:
            a = fdp.ConsumeIntInRange(-1, 8)
            torch.sqrt(a)

        elif mode == 1:
            a = fdp.ConsumeFloatInRange(-1.0, 1.0)
            torch.sqrt(a)

        elif mode == 2:
            real = fdp.ConsumeFloatInRange(-16.0, 16.0)
            imag = fdp.ConsumeFloatInRange(-16.0, 16.0)
            a = complex(real, imag)
            torch.sqrt(a)

        elif mode == 3:
            dtype = fdp.PickValueInList([
                torch.float32,
                torch.float64,
                torch.float16,
                torch.bfloat16,
                torch.complex64,
                torch.complex128,
                torch.int32,
                torch.int64,
                torch.bool,
            ])
            inp = _make_tensor(fdp, dtype=dtype, shape=_pick_shape_1d(fdp))
            torch.sqrt(inp)

        elif mode == 4:
            dtype = fdp.PickValueInList([
                torch.float32,
                torch.float64,
                torch.float16,
                torch.bfloat16,
                torch.complex64,
                torch.complex128,
            ])
            inp = _make_tensor(fdp, dtype=dtype, shape=_pick_shape_1d(fdp))
            out = _make_out_tensor(fdp, inp)
            torch.sqrt(inp, out=out)

        else:
            inp = _make_tensor(
                fdp,
                dtype=fdp.PickValueInList([
                    torch.float32,
                    torch.float64,
                    torch.complex64,
                    torch.complex128,
                ]),
                shape=_pick_shape_1d(fdp),
            )
            if fdp.ConsumeBool():
                torch.sqrt(input=inp)
            else:
                out = _make_out_tensor(fdp, inp)
                torch.sqrt(input=inp, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
