# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.triu
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.triu.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.int32,
        torch.int64,
        torch.bool,
    ])


def _gen_shape(fdp):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return [fdp.ConsumeIntInRange(0, 8), fdp.ConsumeIntInRange(0, 8)]
    if mode == 1:
        return [
            fdp.ConsumeIntInRange(0, 4),
            fdp.ConsumeIntInRange(0, 6),
            fdp.ConsumeIntInRange(0, 6),
        ]
    if mode == 2:
        return [
            fdp.ConsumeIntInRange(0, 3),
            fdp.ConsumeIntInRange(0, 3),
            fdp.ConsumeIntInRange(0, 5),
            fdp.ConsumeIntInRange(0, 5),
        ]
    if mode == 3:
        return [fdp.ConsumeIntInRange(1, 8), fdp.ConsumeIntInRange(1, 8)]
    return [
        fdp.ConsumeIntInRange(1, 3),
        fdp.ConsumeIntInRange(1, 3),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
    ]


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, shape, dtype):
    n = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype.is_floating_point:
        vals = []
        for _ in range(n):
            if fdp.ConsumeBool():
                vals.append(fdp.ConsumeFloatInRange(-16.0, 16.0))
            else:
                vals.append(float(fdp.ConsumeIntInRange(-16, 16)))
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = [fdp.ConsumeIntInRange(-32, 32) for _ in range(n)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)
        shape = _gen_shape(fdp)
        x = _make_tensor(fdp, shape, dtype)

        diag_mode = fdp.ConsumeIntInRange(0, 3)
        if len(shape) >= 2:
            tail_span = max(shape[-2], shape[-1]) + 4
        else:
            tail_span = 8
        if diag_mode == 0:
            diagonal = fdp.ConsumeIntInRange(-1, 8)
        elif diag_mode == 1:
            diagonal = fdp.ConsumeIntInRange(-tail_span, tail_span)
        elif diag_mode == 2:
            diagonal = 0
        else:
            diagonal = fdp.ConsumeIntInRange(-32, 32)

        call_mode = fdp.ConsumeIntInRange(0, 5)
        if call_mode == 0:
            y = torch.triu(x)
        elif call_mode == 1:
            y = torch.triu(x, diagonal)
        elif call_mode == 2:
            y = torch.triu(x, diagonal=diagonal)
        elif call_mode == 3:
            out = torch.empty_like(x)
            y = torch.triu(x, out=out)
        elif call_mode == 4:
            out = torch.empty_like(x)
            y = torch.triu(x, diagonal, out=out)
        else:
            out = torch.empty_like(x)
            y = torch.triu(input=x, diagonal=diagonal, out=out)

        if isinstance(y, torch.Tensor):
            _ = y.shape
            _ = y.dtype
            if y.numel() > 0:
                _ = y.flatten()[0]

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
