# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.kthvalue
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.kthvalue.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _numel_from_shape(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, shape, dtype):
    numel = _numel_from_shape(shape)
    if numel == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 5)

    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(numel)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 1:
        vals = fdp.ConsumeFloatListInRange(numel, -1000.0, 1000.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 2:
        vals = fdp.ConsumeRegularFloatList(numel)
        t = torch.tensor(vals, dtype=dtype)
        if numel > 0:
            t = t.round()
    elif mode == 3:
        vals = [float(fdp.ConsumeIntInRange(-8, 8)) for _ in range(numel)]
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 4:
        base = torch.arange(numel, dtype=dtype)
        if fdp.ConsumeBool():
            base = torch.flip(base, dims=[0])
        shift = float(fdp.ConsumeIntInRange(-3, 3))
        t = base + shift
    else:
        vals = [fdp.ConsumeProbability() for _ in range(numel)]
        t = torch.tensor(vals, dtype=dtype)

    return t.reshape(shape)


def _make_named_tensor_2d(fdp, dtype):
    n = fdp.ConsumeIntInRange(1, 6)
    m = fdp.ConsumeIntInRange(1, 6)
    t = _make_tensor(fdp, [n, m], dtype)
    names = fdp.PickValueInList(
        [
            ("N", "M"),
            ("row", "col"),
            ("batch", "feature"),
            ("x", "y"),
        ]
    )
    return t.refine_names(*names), names


def _resolve_dim(rank, raw_dim):
    return raw_dim if raw_dim >= 0 else raw_dim + rank


def _out_shape(shape, dim, keepdim):
    out = list(shape)
    if keepdim:
        out[dim] = 1
        return out
    del out[dim]
    return out


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        branch = fdp.ConsumeIntInRange(0, 4)
        dtype = _pick_dtype(fdp)

        if branch == 0:
            rank = fdp.ConsumeIntInRange(1, 4)
            shape = [fdp.ConsumeIntInRange(1, 8) for _ in range(rank)]
            x = _make_tensor(fdp, shape, dtype)

            raw_dim = fdp.ConsumeIntInRange(-rank, rank - 1)
            dim = _resolve_dim(rank, raw_dim)
            k = fdp.ConsumeIntInRange(1, shape[dim])
            keepdim = fdp.ConsumeBool()

            if fdp.ConsumeBool():
                torch.kthvalue(x, k, dim=raw_dim, keepdim=keepdim)
            else:
                torch.kthvalue(x, k, raw_dim, keepdim)

        elif branch == 1:
            rank = fdp.ConsumeIntInRange(1, 4)
            shape = [fdp.ConsumeIntInRange(1, 8) for _ in range(rank)]
            x = _make_tensor(fdp, shape, dtype)

            raw_dim = fdp.ConsumeIntInRange(-rank, rank - 1)
            dim = _resolve_dim(rank, raw_dim)
            k = fdp.ConsumeIntInRange(1, shape[dim])
            keepdim = fdp.ConsumeBool()

            out_shape = _out_shape(shape, dim, keepdim)
            values = torch.empty(out_shape, dtype=dtype)
            indices = torch.empty(out_shape, dtype=torch.int64)

            call_style = fdp.ConsumeIntInRange(0, 2)
            if call_style == 0:
                torch.kthvalue(x, k, dim=raw_dim, keepdim=keepdim, out=(values, indices))
            elif call_style == 1:
                torch.kthvalue(x, k, raw_dim, keepdim, out=(values, indices))
            else:
                torch.kthvalue(input=x, k=k, dim=raw_dim, keepdim=keepdim, out=(values, indices))

        elif branch == 2:
            x, names = _make_named_tensor_2d(fdp, dtype)
            dim_name = fdp.PickValueInList([names[0], names[1]])
            dim_index = 0 if dim_name == names[0] else 1
            k = fdp.ConsumeIntInRange(1, x.shape[dim_index])
            keepdim = fdp.ConsumeBool()

            if fdp.ConsumeBool():
                torch.kthvalue(x, k, dim=dim_name, keepdim=keepdim)
            else:
                torch.kthvalue(input=x, k=k, dim=dim_name, keepdim=keepdim)

        elif branch == 3:
            x, names = _make_named_tensor_2d(fdp, dtype)
            dim_name = fdp.PickValueInList([names[0], names[1]])
            dim_index = 0 if dim_name == names[0] else 1
            k = fdp.ConsumeIntInRange(1, x.shape[dim_index])
            keepdim = fdp.ConsumeBool()

            out_shape = _out_shape(list(x.shape), dim_index, keepdim)
            values = torch.empty(out_shape, dtype=dtype, names=tuple(n for i, n in enumerate(names) if keepdim or i != dim_index))
            indices = torch.empty(out_shape, dtype=torch.int64, names=tuple(n for i, n in enumerate(names) if keepdim or i != dim_index))
            if keepdim:
                kept_names = list(names)
                values = torch.empty(out_shape, dtype=dtype).refine_names(*kept_names)
                indices = torch.empty(out_shape, dtype=torch.int64).refine_names(*kept_names)

            torch.kthvalue(x, k, dim=dim_name, keepdim=keepdim, out=(values, indices))

        else:
            rank = fdp.ConsumeIntInRange(1, 4)
            shape = [fdp.ConsumeIntInRange(1, 8) for _ in range(rank)]
            x = _make_tensor(fdp, shape, dtype)

            k = fdp.ConsumeIntInRange(1, shape[-1])
            keepdim = fdp.ConsumeBool()

            if fdp.ConsumeBool():
                torch.kthvalue(x, k, keepdim=keepdim)
            else:
                torch.kthvalue(input=x, k=k, keepdim=keepdim)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
