# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.pca_lowrank
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.pca_lowrank.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape(fdp):
    rank = fdp.PickValueInList([2, 3])
    if rank == 2:
        m = fdp.ConsumeIntInRange(1, 8)
        c = fdp.ConsumeIntInRange(1, 64)
        return (m, c)
    n = fdp.ConsumeIntInRange(1, 8)
    m = fdp.ConsumeIntInRange(1, 8)
    c = fdp.ConsumeIntInRange(1, 64)
    return (n, m, c)


def _numel(shape):
    total = 1
    for s in shape:
        total *= s
    return total


def _make_dense_tensor(fdp, shape, dtype):
    count = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 5)

    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(count, -10.0, 10.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 1:
        vals = fdp.ConsumeFloatListInRange(count, -1.0, 1.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 2:
        vals = [float(fdp.ConsumeIntInRange(-3, 3)) for _ in range(count)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 3:
        base = fdp.ConsumeFloatInRange(-5.0, 5.0)
        return torch.full(shape, base, dtype=dtype)
    if mode == 4:
        vals = [0.0] * count
        if count > 0:
            idx = fdp.ConsumeIntInRange(0, count - 1)
            vals[idx] = fdp.ConsumeFloatInRange(-50.0, 50.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    t = torch.arange(count, dtype=dtype).reshape(shape)
    scale = fdp.ConsumeFloatInRange(-3.0, 3.0)
    bias = fdp.ConsumeFloatInRange(-3.0, 3.0)
    return t * scale + bias


def _make_sparse_2d_from_dense(fdp, dense):
    m, n = dense.shape
    nnz = fdp.ConsumeIntInRange(0, min(m * n, 16))
    if nnz == 0:
        indices = torch.zeros((2, 0), dtype=torch.int64)
        values = torch.zeros((0,), dtype=dense.dtype)
        return torch.sparse_coo_tensor(indices, values, dense.shape)

    rows = []
    cols = []
    vals = []
    for _ in range(nnz):
        rows.append(fdp.ConsumeIntInRange(0, m - 1))
        cols.append(fdp.ConsumeIntInRange(0, n - 1))
        vals.append(fdp.ConsumeFloatInRange(-10.0, 10.0))
    indices = torch.tensor([rows, cols], dtype=torch.int64)
    values = torch.tensor(vals, dtype=dense.dtype)
    return torch.sparse_coo_tensor(indices, values, dense.shape)


def _make_input_tensor(fdp):
    dtype = _pick_dtype(fdp)
    shape = _consume_shape(fdp)
    dense = _make_dense_tensor(fdp, shape, dtype)

    if len(shape) == 2 and fdp.ConsumeBool():
        return _make_sparse_2d_from_dense(fdp, dense).coalesce()
    return dense


def _choose_q(fdp, shape):
    m = shape[-2]
    n = shape[-1]
    default_q = min(6, m, n)
    max_reasonable = max(m, n) + 2

    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        return None
    if mode == 1:
        return fdp.ConsumeIntInRange(-1, 8)
    if mode == 2:
        return default_q
    if mode == 3:
        return fdp.ConsumeIntInRange(0, max_reasonable)
    if mode == 4:
        return fdp.PickValueInList([0, 1, min(m, n), max(m, n), max_reasonable])
    return fdp.ConsumeIntInRange(-2, max_reasonable + 2)


def _choose_niter(fdp):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return fdp.ConsumeIntInRange(-1, 8)
    if mode == 1:
        return fdp.PickValueInList([0, 1, 2, 3, 4, 8])
    if mode == 2:
        return 2
    if mode == 3:
        return fdp.ConsumeIntInRange(0, 5)
    return fdp.ConsumeIntInRange(-3, 10)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        A = _make_input_tensor(fdp)
        q = _choose_q(fdp, A.shape)
        center = fdp.ConsumeBool()
        niter = _choose_niter(fdp)

        call_mode = fdp.ConsumeIntInRange(0, 4)
        if call_mode == 0:
            result = torch.pca_lowrank(A)
        elif call_mode == 1:
            result = torch.pca_lowrank(A, q=q)
        elif call_mode == 2:
            result = torch.pca_lowrank(A, q=q, center=center)
        elif call_mode == 3:
            result = torch.pca_lowrank(A, q=q, center=center, niter=niter)
        else:
            result = torch.pca_lowrank(A=A, q=q, center=center, niter=niter)

        if isinstance(result, tuple) and len(result) == 3:
            u, s, v = result
            _ = u.shape
            _ = s.shape
            _ = v.shape
            if u.numel() > 0:
                _ = u.reshape(-1)[0].item()
            if s.numel() > 0:
                _ = s.reshape(-1)[0].item()
            if v.numel() > 0:
                _ = v.reshape(-1)[0].item()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
