# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.mul
# source_yaml_count=16
# source_api_txt=/root/api_txt/torch.mul.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


DTYPES = [
    torch.float32,
    torch.float64,
    torch.int32,
    torch.int64,
    torch.complex64,
    torch.complex128,
]

SCALAR_NUMBERS = [
    -2,
    -1,
    0,
    1,
    2,
    -0.0,
    0.0,
    0.5,
    -0.5,
    3.0,
    -3.0,
    1 + 0j,
    -1 + 0j,
    0.5 + 0.25j,
    -0.75 - 1.25j,
    True,
    False,
]


def _consume_dim_size(fdp):
    return fdp.PickValueInList([0, 1, 2, 3, 4, 5, 8])


def _consume_shape(fdp, allow_scalar=True):
    rank_choices = [0, 1, 2, 3, 4, 5] if allow_scalar else [1, 2, 3, 4, 5]
    rank = fdp.PickValueInList(rank_choices)
    if rank == 0:
        return ()
    return tuple(_consume_dim_size(fdp) for _ in range(rank))


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_scalar_value(fdp, dtype):
    if dtype in (torch.float32, torch.float64):
        choice = fdp.ConsumeIntInRange(0, 6)
        if choice == 0:
            return 0.0
        if choice == 1:
            return -0.0
        if choice == 2:
            return 1.0
        if choice == 3:
            return -1.0
        if choice == 4:
            return fdp.ConsumeFloatInRange(-10.0, 10.0)
        if choice == 5:
            return float(fdp.ConsumeIntInRange(-8, 8))
        return fdp.PickValueInList([math.pi, -math.pi, 1e-6, -1e-6])
    if dtype in (torch.int32, torch.int64):
        return fdp.PickValueInList([-8, -1, 0, 1, 2, 7, 8])
    if dtype in (torch.complex64, torch.complex128):
        r = fdp.PickValueInList([0.0, 1.0, -1.0, fdp.ConsumeFloatInRange(-5.0, 5.0)])
        i = fdp.PickValueInList([0.0, 1.0, -1.0, fdp.ConsumeFloatInRange(-5.0, 5.0)])
        return complex(r, i)
    return 0


def _make_tensor_from_shape(fdp, shape, dtype):
    numel = _numel(shape)
    if dtype in (torch.float32, torch.float64):
        vals = []
        for _ in range(numel):
            mode = fdp.ConsumeIntInRange(0, 5)
            if mode == 0:
                vals.append(0.0)
            elif mode == 1:
                vals.append(1.0)
            elif mode == 2:
                vals.append(-1.0)
            elif mode == 3:
                vals.append(fdp.ConsumeFloatInRange(-10.0, 10.0))
            elif mode == 4:
                vals.append(float(fdp.ConsumeIntInRange(-16, 16)))
            else:
                vals.append(fdp.PickValueInList([1e-6, -1e-6, 3.14159265, -2.7182818]))
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.int32, torch.int64):
        vals = [fdp.PickValueInList([-16, -8, -1, 0, 1, 2, 7, 8, 16]) for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype in (torch.complex64, torch.complex128):
        vals = []
        for _ in range(numel):
            real = fdp.PickValueInList([0.0, 1.0, -1.0, fdp.ConsumeFloatInRange(-5.0, 5.0)])
            imag = fdp.PickValueInList([0.0, 1.0, -1.0, fdp.ConsumeFloatInRange(-5.0, 5.0)])
            vals.append(complex(real, imag))
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    return torch.zeros(shape, dtype=torch.float32)


def _make_tensor(fdp, allow_scalar=True, dtype=None, shape=None):
    if dtype is None:
        dtype = fdp.PickValueInList(DTYPES)
    if shape is None:
        shape = _consume_shape(fdp, allow_scalar=allow_scalar)
    return _make_tensor_from_shape(fdp, shape, dtype)


def _broadcast_shape(base_shape, fdp):
    if len(base_shape) == 0:
        return ()
    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        return base_shape
    if mode == 1:
        return tuple(1 for _ in base_shape)
    if mode == 2:
        idx = fdp.ConsumeIntInRange(0, len(base_shape) - 1)
        out = list(base_shape)
        out[idx] = 1
        return tuple(out)
    if mode == 3:
        k = fdp.ConsumeIntInRange(1, 2)
        return tuple([1] * k + list(base_shape))
    if mode == 4 and len(base_shape) > 1:
        start = fdp.ConsumeIntInRange(0, len(base_shape) - 1)
        return tuple(base_shape[start:])
    return tuple(1 if fdp.ConsumeBool() else d for d in base_shape)


def _make_number(fdp, kind):
    if kind == "int":
        return fdp.PickValueInList([-8, -1, 0, 1, 2, 7, 8])
    if kind == "float":
        return fdp.PickValueInList([
            -1.0,
            0.0,
            1.0,
            fdp.ConsumeFloatInRange(-10.0, 10.0),
            math.pi,
            -math.pi,
        ])
    if kind == "complex":
        return complex(
            fdp.PickValueInList([0.0, 1.0, -1.0, fdp.ConsumeFloatInRange(-5.0, 5.0)]),
            fdp.PickValueInList([0.0, 1.0, -1.0, fdp.ConsumeFloatInRange(-5.0, 5.0)]),
        )
    return fdp.PickValueInList(SCALAR_NUMBERS)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 8)

        if mode == 0:
            a = _make_number(fdp, "int")
            b = _make_number(fdp, "int")
            torch.mul(a, b)

        elif mode == 1:
            a = _make_number(fdp, "float")
            b = _make_number(fdp, "float")
            torch.mul(a, b)

        elif mode == 2:
            scalar_kind = fdp.PickValueInList(["int", "float", "complex"])
            tensor_dtype = fdp.PickValueInList(DTYPES)
            x = _make_tensor(fdp, allow_scalar=True, dtype=tensor_dtype)
            y = _make_number(fdp, scalar_kind)
            if fdp.ConsumeBool():
                torch.mul(x, y)
            else:
                torch.mul(y, x)

        elif mode == 3:
            dtype = fdp.PickValueInList(DTYPES)
            base_shape = _consume_shape(fdp, allow_scalar=True)
            x = _make_tensor_from_shape(fdp, base_shape, dtype)
            other_shape = _broadcast_shape(base_shape, fdp)
            y = _make_tensor_from_shape(fdp, other_shape, dtype)
            torch.mul(x, y)

        elif mode == 4:
            dtype1 = fdp.PickValueInList(DTYPES)
            dtype2 = fdp.PickValueInList(DTYPES)
            base_shape = _consume_shape(fdp, allow_scalar=True)
            x = _make_tensor_from_shape(fdp, base_shape, dtype1)
            other_shape = _broadcast_shape(base_shape, fdp)
            y = _make_tensor_from_shape(fdp, other_shape, dtype2)
            torch.mul(x, y)

        elif mode == 5:
            dtype = fdp.PickValueInList(DTYPES)
            base_shape = _consume_shape(fdp, allow_scalar=True)
            x = _make_tensor_from_shape(fdp, base_shape, dtype)
            other_shape = _broadcast_shape(base_shape, fdp)
            y = _make_tensor_from_shape(fdp, other_shape, dtype)
            out_shape = torch.broadcast_shapes(tuple(x.shape), tuple(y.shape))
            out = _make_tensor_from_shape(fdp, out_shape, dtype)
            torch.mul(x, y, out=out)

        elif mode == 6:
            dtype = fdp.PickValueInList(DTYPES)
            x = _make_tensor(fdp, allow_scalar=True, dtype=dtype)
            y = fdp.PickValueInList(SCALAR_NUMBERS)
            out = _make_tensor_from_shape(fdp, tuple(x.shape), dtype)
            torch.mul(x, y, out=out)

        elif mode == 7:
            a = _make_number(fdp, "complex")
            b = fdp.PickValueInList([
                _make_number(fdp, "complex"),
                _make_number(fdp, "float"),
                _make_number(fdp, "int"),
            ])
            torch.mul(a, b)

        else:
            list_len = fdp.ConsumeIntInRange(0, 6)
            elems = []
            elem_kind = fdp.PickValueInList(["int", "float", "complex", "bool"])
            for _ in range(list_len):
                if elem_kind == "int":
                    elems.append(_make_number(fdp, "int"))
                elif elem_kind == "float":
                    elems.append(_make_number(fdp, "float"))
                elif elem_kind == "complex":
                    elems.append(_make_number(fdp, "complex"))
                else:
                    elems.append(fdp.ConsumeBool())
            n = fdp.ConsumeIntInRange(-2, 8)
            if fdp.ConsumeBool():
                torch.mul(elems, n)
            else:
                torch.mul(n, elems)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
