# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.sparse.sum
# source_yaml_count=10
# source_api_txt=/root/api_txt/torch.sparse.sum.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


DTYPES = [
    None,
    torch.float32,
    torch.float64,
    torch.float16,
    torch.bfloat16,
    torch.int32,
    torch.int64,
]


def _consume_shape(fdp, rank):
    dims = []
    for _ in range(rank):
        dims.append(fdp.ConsumeIntInRange(1, 4))
    return dims


def _make_dense_values(fdp, numel, dtype):
    if dtype in (torch.float16, torch.float32, torch.float64, torch.bfloat16):
        vals = fdp.ConsumeFloatListInRange(numel, -10.0, 10.0)
        t = torch.tensor(vals, dtype=torch.float32)
        return t.to(dtype=dtype)
    if dtype in (torch.int32, torch.int64):
        vals = fdp.ConsumeIntListInRange(numel, -20, 20)
        return torch.tensor(vals, dtype=dtype)
    vals = fdp.ConsumeFloatListInRange(numel, -10.0, 10.0)
    return torch.tensor(vals, dtype=torch.float32)


def _build_sparse_coo_tensor(fdp):
    rank = fdp.ConsumeIntInRange(2, 5)
    sparse_dim = fdp.ConsumeIntInRange(1, rank)
    dense_dim = rank - sparse_dim

    shape = _consume_shape(fdp, rank)
    nnz_max = 8
    nnz = fdp.ConsumeIntInRange(0, nnz_max)

    base_dtype = fdp.PickValueInList(
        [torch.float32, torch.float64, torch.float16, torch.bfloat16, torch.int32, torch.int64]
    )

    if sparse_dim > 0:
        indices_data = []
        for d in range(sparse_dim):
            hi = max(0, shape[d] - 1)
            indices_data.append(fdp.ConsumeIntListInRange(nnz, 0, hi))
        if nnz == 0:
            indices = torch.zeros((sparse_dim, 0), dtype=torch.int64)
        else:
            indices = torch.tensor(indices_data, dtype=torch.int64)
    else:
        indices = torch.zeros((0, nnz), dtype=torch.int64)

    dense_shape = shape[sparse_dim:]
    dense_elems_per_nnz = 1
    for s in dense_shape:
        dense_elems_per_nnz *= s
    total_values = nnz * dense_elems_per_nnz
    values = _make_dense_values(fdp, total_values, base_dtype)
    if dense_dim > 0:
        values = values.reshape([nnz] + dense_shape)
    else:
        values = values.reshape([nnz])

    requires_coalesce = fdp.ConsumeBool()
    s = torch.sparse_coo_tensor(indices, values, size=shape)
    if requires_coalesce:
        s = s.coalesce()
    return s


def _pick_dims(fdp, rank):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return None
    count = fdp.ConsumeIntInRange(1, rank)
    dims = []
    for _ in range(count):
        if fdp.ConsumeBool():
            d = fdp.ConsumeIntInRange(0, rank - 1)
        else:
            d = fdp.ConsumeIntInRange(-rank, -1)
        dims.append(d)
    if fdp.ConsumeBool():
        seen = set()
        uniq = []
        for d in dims:
            canon = d if d >= 0 else rank + d
            if canon not in seen:
                seen.add(canon)
                uniq.append(d)
        dims = uniq if uniq else [0]
    if len(dims) == 1 and fdp.ConsumeBool():
        return dims[0]
    return tuple(dims)


def _result_shape(size, sparse_dim, dense_dim, dims):
    if dims is None:
        return []
    rank = sparse_dim + dense_dim
    if isinstance(dims, int):
        dims = (dims,)
    canon = []
    for d in dims:
        cd = d if d >= 0 else rank + d
        if 0 <= cd < rank and cd not in canon:
            canon.append(cd)
    out = []
    for i in range(rank):
        if i not in canon:
            out.append(size[i])
    if not canon:
        out = list(size)
    if all(d < sparse_dim for d in canon) and len(canon) == sparse_dim:
        dense_tail = list(size[sparse_dim:])
        return dense_tail
    return out


def _make_out_tensor(fdp, src, dims, dtype):
    chosen_dtype = dtype if dtype is not None else src.dtype
    shape = _result_shape(tuple(src.size()), src.sparse_dim(), src.dense_dim(), dims)
    if len(shape) == 0:
        if chosen_dtype in (torch.float16, torch.float32, torch.float64, torch.bfloat16):
            return torch.empty([], dtype=chosen_dtype)
        return torch.empty([], dtype=chosen_dtype)
    return torch.empty(shape, dtype=chosen_dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        s = _build_sparse_coo_tensor(fdp)
        dims = _pick_dims(fdp, s.dim())
        dtype = fdp.PickValueInList(DTYPES)

        call_mode = fdp.ConsumeIntInRange(0, 5)

        if call_mode == 0:
            if dtype is None:
                torch.sparse.sum(s)
            else:
                torch.sparse.sum(s, dtype=dtype)
        elif call_mode == 1:
            if dtype is None:
                torch.sparse.sum(s, dim=dims)
            else:
                torch.sparse.sum(s, dim=dims, dtype=dtype)
        elif call_mode == 2:
            if dims is None:
                if dtype is None:
                    torch.sparse.sum(input=s)
                else:
                    torch.sparse.sum(input=s, dtype=dtype)
            else:
                if dtype is None:
                    torch.sparse.sum(input=s, dim=dims)
                else:
                    torch.sparse.sum(input=s, dim=dims, dtype=dtype)
        elif call_mode == 3:
            if dims is None:
                if dtype is None:
                    torch.sparse.sum(s, None)
                else:
                    torch.sparse.sum(s, None, dtype)
            else:
                if dtype is None:
                    torch.sparse.sum(s, dims)
                else:
                    torch.sparse.sum(s, dims, dtype)
        elif call_mode == 4:
            out = _make_out_tensor(fdp, s, dims, dtype)
            if dims is None:
                if dtype is None:
                    torch.sparse.sum(s, out=out)
                else:
                    torch.sparse.sum(s, dtype=dtype, out=out)
            else:
                if dtype is None:
                    torch.sparse.sum(s, dim=dims, out=out)
                else:
                    torch.sparse.sum(s, dim=dims, dtype=dtype, out=out)
        else:
            # Exercise downstream behavior on the result to increase coverage.
            if dims is None:
                r = torch.sparse.sum(s, dtype=dtype) if dtype is not None else torch.sparse.sum(s)
            else:
                r = torch.sparse.sum(s, dim=dims, dtype=dtype) if dtype is not None else torch.sparse.sum(s, dim=dims)
            if isinstance(r, torch.Tensor):
                if r.layout == torch.sparse_coo:
                    _ = r.coalesce()._nnz()
                    _ = tuple(r.size())
                else:
                    _ = r.numel()
                    _ = tuple(r.size())

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
