# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.rnn.pad_sequence
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.rnn.pad_sequence.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
from torch.nn.utils.rnn import pad_sequence


def _pick_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.int64,
        torch.int32,
        torch.int16,
        torch.int8,
        torch.uint8,
        torch.bool,
    ])


def _shape_for_rank(fdp, rank):
    if rank < 0:
        rank = 0
    shape = []
    # First dim is sequence length L and may vary across tensors later.
    for i in range(rank):
        if i == 0:
            dim = fdp.ConsumeIntInRange(0, 16)
        else:
            dim = fdp.ConsumeIntInRange(0, 8)
        shape.append(dim)
    return shape


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor_from_shape(fdp, shape, dtype):
    numel = _numel(shape)
    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if dtype.is_floating_point:
        vals = fdp.ConsumeFloatListInRange(numel, -10.0, 10.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = fdp.ConsumeIntListInRange(numel, -20, 20)
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _make_sequence_list(fdp):
    # pad_sequence accepts tensors shaped L x * with * possibly empty (rank 1)
    # and requires identical trailing dims and dtype across all tensors.
    rank = fdp.ConsumeIntInRange(1, 5)
    batch = fdp.ConsumeIntInRange(0, 8)
    dtype = _pick_dtype(fdp)

    base_shape = _shape_for_rank(fdp, rank)
    trailing = base_shape[1:] if rank > 1 else []

    sequences = []
    for _ in range(batch):
        seq_len = fdp.ConsumeIntInRange(0, 16)
        shape = [seq_len] + trailing
        t = _make_tensor_from_shape(fdp, shape, dtype)
        sequences.append(t)

    # Sometimes force non-empty valid lists more often to reach deeper code.
    if not sequences and fdp.ConsumeBool():
        seq_len = fdp.ConsumeIntInRange(0, 16)
        shape = [seq_len] + trailing
        sequences.append(_make_tensor_from_shape(fdp, shape, dtype))

    return sequences


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        sequences = _make_sequence_list(fdp)
        batch_first = fdp.ConsumeBool()
        padding_value = fdp.ConsumeFloatInRange(-1.0, 1.0)

        # Docs/YAML indicate "right" is valid; also try "left" to explore support.
        padding_side = fdp.PickValueInList(["right", "left"])

        if fdp.ConsumeBool():
            out = pad_sequence(
                sequences,
                batch_first=batch_first,
                padding_value=padding_value,
                padding_side=padding_side,
            )
        else:
            out = pad_sequence(sequences, batch_first, padding_value, padding_side)

        if isinstance(out, torch.Tensor):
            _ = out.size()
            _ = out.numel()
            if out.numel() > 0:
                _ = out.reshape(-1)[0]

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
