# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.save
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.save.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import io
import os
import pickle
import tempfile

import torch


DTYPES = [
    torch.bool,
    torch.uint8,
    torch.int8,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.float16,
    torch.float32,
    torch.float64,
    torch.complex64,
    torch.complex128,
]


def _consume_small_string(fdp, max_len=24):
    return fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, max_len))


def _consume_shape(fdp, max_rank=4, max_dim=5):
    rank = fdp.ConsumeIntInRange(0, max_rank)
    return [fdp.ConsumeIntInRange(0, max_dim) for _ in range(rank)]


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_tensor(fdp):
    dtype = fdp.PickValueInList(DTYPES)
    shape = _consume_shape(fdp)
    n = _numel(shape)

    if dtype == torch.bool:
        data = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if dtype in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64):
        data = [fdp.ConsumeIntInRange(-128, 127) for _ in range(n)]
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if dtype in (torch.float16, torch.float32, torch.float64):
        data = [fdp.ConsumeRegularFloat() for _ in range(n)]
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if dtype in (torch.complex64, torch.complex128):
        data = [
            complex(fdp.ConsumeRegularFloat(), fdp.ConsumeRegularFloat())
            for _ in range(n)
        ]
        return torch.tensor(data, dtype=dtype).reshape(shape)

    data = [fdp.ConsumeRegularFloat() for _ in range(n)]
    return torch.tensor(data).reshape(shape)


def _make_python_scalar(fdp):
    choice = fdp.ConsumeIntInRange(0, 5)
    if choice == 0:
        return None
    if choice == 1:
        return fdp.ConsumeBool()
    if choice == 2:
        return fdp.ConsumeIntInRange(-100000, 100000)
    if choice == 3:
        return fdp.ConsumeRegularFloat()
    if choice == 4:
        return complex(fdp.ConsumeRegularFloat(), fdp.ConsumeRegularFloat())
    return _consume_small_string(fdp, 32)


def _make_collection(fdp, depth):
    kind = fdp.ConsumeIntInRange(0, 4)
    count = fdp.ConsumeIntInRange(0, 4)

    if kind == 0:
        return [_make_object(fdp, depth + 1) for _ in range(count)]
    if kind == 1:
        return tuple(_make_object(fdp, depth + 1) for _ in range(count))
    if kind == 2:
        d = {}
        for _ in range(count):
            key_choice = fdp.ConsumeIntInRange(0, 2)
            if key_choice == 0:
                key = _consume_small_string(fdp, 16)
            elif key_choice == 1:
                key = fdp.ConsumeIntInRange(-1000, 1000)
            else:
                key = fdp.ConsumeBool()
            d[key] = _make_object(fdp, depth + 1)
        return d
    if kind == 3:
        return {
            "tensor": _make_tensor(fdp),
            "meta": {
                "name": _consume_small_string(fdp, 16),
                "flag": fdp.ConsumeBool(),
                "value": fdp.ConsumeIntInRange(-100, 100),
            },
        }
    return {
        "a": _make_python_scalar(fdp),
        "b": _make_tensor(fdp),
        "c": [_make_python_scalar(fdp) for _ in range(count)],
    }


def _make_object(fdp, depth=0):
    if depth >= 2:
        leaf = fdp.ConsumeIntInRange(0, 2)
        if leaf == 0:
            return _make_python_scalar(fdp)
        if leaf == 1:
            return _make_tensor(fdp)
        return {"v": _make_python_scalar(fdp), "t": _make_tensor(fdp)}

    choice = fdp.ConsumeIntInRange(0, 4)
    if choice == 0:
        return _make_python_scalar(fdp)
    if choice == 1:
        return _make_tensor(fdp)
    if choice == 2:
        t = _make_tensor(fdp)
        if t.numel() > 0 and t.dtype != torch.bool:
            return {"base": t, "view": t.view(-1)}
        return {"base": t}
    return _make_collection(fdp, depth)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        obj = _make_object(fdp)

        pickle_protocol = fdp.ConsumeIntInRange(0, pickle.HIGHEST_PROTOCOL)
        use_new_zip = fdp.ConsumeBool()
        disable_byteorder = fdp.ConsumeBool()

        mode = fdp.ConsumeIntInRange(0, 2)

        if mode == 0:
            suffix = _consume_small_string(fdp, 8)
            if not suffix:
                suffix = ".pt"
            elif "." not in suffix:
                suffix = "." + suffix
            with tempfile.NamedTemporaryFile(suffix=suffix, delete=True) as tmp:
                if fdp.ConsumeBool():
                    torch.save(
                        obj,
                        tmp.name,
                        pickle_protocol=pickle_protocol,
                        _use_new_zipfile_serialization=use_new_zip,
                        _disable_byteorder_record=disable_byteorder,
                    )
                else:
                    torch.save(obj, tmp.name)
                try:
                    tmp.flush()
                    os.fsync(tmp.fileno())
                except Exception:
                    pass

        elif mode == 1:
            buffer = io.BytesIO()
            if fdp.ConsumeBool():
                torch.save(
                    obj,
                    buffer,
                    pickle_protocol=pickle_protocol,
                    _use_new_zipfile_serialization=use_new_zip,
                    _disable_byteorder_record=disable_byteorder,
                )
            else:
                torch.save(obj, buffer)
            _ = buffer.getvalue()

        else:
            suffix = _consume_small_string(fdp, 8)
            if not suffix:
                suffix = ".pt"
            elif "." not in suffix:
                suffix = "." + suffix
            with tempfile.NamedTemporaryFile(suffix=suffix, delete=True) as tmp:
                path_obj = os.PathLike
                class _P(path_obj):
                    def __fspath__(self_inner):
                        return tmp.name
                p = _P()
                torch.save(
                    obj,
                    p,
                    pickle_protocol=pickle_protocol,
                    _use_new_zipfile_serialization=use_new_zip,
                    _disable_byteorder_record=disable_byteorder,
                )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
