# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.randperm
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.randperm.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


CPU_DTYPES = [
    torch.int64,
    torch.int32,
    torch.int16,
    torch.int8,
    torch.uint8,
    torch.float64,
    torch.float32,
    torch.float16,
    torch.bool,
]

OUT_DTYPES = [
    torch.float32,
    torch.float64,
]

LAYOUTS = [
    torch.strided,
]


def _choose_device(fdp):
    if torch.cuda.is_available() and fdp.ConsumeBool():
        idx = 0
        try:
            count = torch.cuda.device_count()
            if count > 0:
                idx = fdp.ConsumeIntInRange(0, count - 1)
        except Exception:
            idx = 0
        return torch.device("cuda", idx)
    return torch.device("cpu")


def _choose_dtype(fdp, device):
    dtypes = list(CPU_DTYPES)
    if device.type == "cuda":
        dtypes = [
            torch.int64,
            torch.int32,
            torch.int16,
            torch.int8,
            torch.uint8,
            torch.float64,
            torch.float32,
            torch.float16,
            torch.bool,
        ]
        if hasattr(torch, "bfloat16"):
            dtypes.append(torch.bfloat16)
    return fdp.PickValueInList(dtypes)


def _make_generator(fdp, device):
    if not fdp.ConsumeBool():
        return None
    gen = torch.Generator(device=device.type)
    seed = fdp.ConsumeUInt(8)
    gen.manual_seed(seed)
    return gen


def _choose_n(fdp):
    if fdp.ConsumeBool():
        return fdp.ConsumeIntInRange(0, 8)
    return fdp.ConsumeIntInRange(-4, 64)


def _make_out_tensor(fdp, n, device):
    dtype = fdp.PickValueInList(OUT_DTYPES)
    if fdp.ConsumeBool() and n >= 0:
        shape_n = n
    else:
        shape_n = fdp.ConsumeIntInRange(0, 16)
    return torch.empty((shape_n,), dtype=dtype, device=device)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        n = _choose_n(fdp)
        device = _choose_device(fdp)
        layout = fdp.PickValueInList(LAYOUTS)
        generator = _make_generator(fdp, device)
        requires_grad = fdp.ConsumeBool()
        pin_memory = fdp.ConsumeBool()

        branch = fdp.ConsumeIntInRange(0, 3)

        if branch == 0:
            dtype = _choose_dtype(fdp, device)
            kwargs = {
                "dtype": dtype,
                "layout": layout,
                "device": device,
                "requires_grad": requires_grad,
                "pin_memory": pin_memory if device.type == "cpu" else False,
            }
            if generator is not None and fdp.ConsumeBool():
                kwargs["generator"] = generator
            result = torch.randperm(n, **kwargs)
            if result.numel() > 0:
                _ = result[0].item()

        elif branch == 1:
            out = _make_out_tensor(fdp, n, device)
            kwargs = {
                "out": out,
            }
            if generator is not None and fdp.ConsumeBool():
                kwargs["generator"] = generator
            result = torch.randperm(n, **kwargs)
            if result.numel() > 0:
                _ = result[-1].item()

        elif branch == 2:
            dtype = _choose_dtype(fdp, device)
            out = _make_out_tensor(fdp, n, device)
            kwargs = {
                "dtype": dtype,
                "layout": layout,
                "device": device,
                "out": out,
                "requires_grad": requires_grad,
                "pin_memory": pin_memory if device.type == "cpu" else False,
            }
            if generator is not None:
                kwargs["generator"] = generator
            result = torch.randperm(n, **kwargs)
            if result.numel() > 1:
                _ = result.sum().item()

        else:
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["layout"] = layout
            if fdp.ConsumeBool():
                kwargs["device"] = device
            if fdp.ConsumeBool():
                kwargs["pin_memory"] = pin_memory if device.type == "cpu" else False
            if fdp.ConsumeBool():
                kwargs["requires_grad"] = requires_grad
            if fdp.ConsumeBool():
                kwargs["dtype"] = _choose_dtype(fdp, device)
            if generator is not None and fdp.ConsumeBool():
                kwargs["generator"] = generator
            if fdp.ConsumeBool():
                kwargs["out"] = _make_out_tensor(fdp, n, device)
            result = torch.randperm(n, **kwargs)
            if result.ndim == 1 and result.numel() >= 0:
                _ = result.shape[0]

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
