# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.exp
# source_yaml_count=6
# source_api_txt=/root/api_txt/torch.exp.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


def _pick_dtype(fdp, for_out=False):
    base = [torch.float32, torch.float64]
    extra = [
        torch.float16,
        torch.bfloat16,
        torch.complex64,
        torch.complex128,
        torch.int8,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
    ]
    if for_out:
        choices = base + extra
    else:
        choices = base + extra
    return fdp.PickValueInList(choices)


def _consume_shape(fdp):
    rank = fdp.PickValueInList([0, 1, 2, 3, 4, 5])
    if rank == 0:
        return []
    dims = []
    for i in range(rank):
        if i == 0:
            dims.append(fdp.ConsumeIntInRange(0, 8))
        else:
            dims.append(fdp.ConsumeIntInRange(0, 8))
    return dims


def _numel_from_shape(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _special_scalar_float(fdp):
    specials = [
        -100.0,
        -20.0,
        -2.0,
        -1.0,
        -0.0,
        0.0,
        1.0,
        2.0,
        10.0,
        20.0,
        88.0,
        float("inf"),
        float("-inf"),
        float("nan"),
        math.log(2.0),
    ]
    if fdp.ConsumeBool():
        return fdp.PickValueInList(specials)
    return fdp.ConsumeFloat()


def _make_tensor(fdp, dtype=None, shape=None):
    if dtype is None:
        dtype = _pick_dtype(fdp)
    if shape is None:
        shape = _consume_shape(fdp)

    numel = _numel_from_shape(shape)
    if numel == 0:
        if dtype.is_complex:
            return torch.empty(shape, dtype=dtype)
        return torch.empty(shape, dtype=dtype)

    if dtype == torch.bool:
        values = [fdp.ConsumeBool() for _ in range(numel)]
        return torch.tensor(values, dtype=dtype).reshape(shape)

    if dtype.is_floating_point:
        mode = fdp.ConsumeIntInRange(0, 3)
        if mode == 0:
            vals = [fdp.ConsumeRegularFloat() for _ in range(numel)]
        elif mode == 1:
            vals = [fdp.ConsumeFloatInRange(-100.0, 100.0) for _ in range(numel)]
        elif mode == 2:
            edge_vals = [
                -100.0, -20.0, -2.0, -1.0, -0.0, 0.0, 1.0, 2.0, 10.0, 20.0, 88.0
            ]
            vals = [fdp.PickValueInList(edge_vals) for _ in range(numel)]
        else:
            vals = [fdp.ConsumeFloat() for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    if dtype.is_complex:
        mode = fdp.ConsumeIntInRange(0, 2)
        vals = []
        for _ in range(numel):
            if mode == 0:
                r = fdp.ConsumeRegularFloat()
                im = fdp.ConsumeRegularFloat()
            elif mode == 1:
                r = fdp.ConsumeFloatInRange(-20.0, 20.0)
                im = fdp.ConsumeFloatInRange(-20.0, 20.0)
            else:
                r = _special_scalar_float(fdp)
                im = _special_scalar_float(fdp)
            vals.append(complex(r, im))
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    if dtype in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64):
        info = torch.iinfo(dtype)
        if fdp.ConsumeBool():
            lo = max(info.min, -16)
            hi = min(info.max, 16)
            vals = [fdp.ConsumeIntInRange(lo, hi) for _ in range(numel)]
        else:
            edge = [-128, -16, -2, -1, 0, 1, 2, 8, 16, 127, 255]
            vals = []
            for _ in range(numel):
                v = fdp.PickValueInList(edge)
                v = min(max(v, info.min), info.max)
                vals.append(v)
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    return torch.zeros(shape, dtype=dtype)


def _make_out_tensor(fdp, inp):
    strategy = fdp.ConsumeIntInRange(0, 4)
    if strategy == 0:
        out_dtype = inp.dtype
        out_shape = list(inp.shape)
    elif strategy == 1:
        out_dtype = fdp.PickValueInList([torch.float32, torch.float64])
        out_shape = list(inp.shape)
    elif strategy == 2:
        out_dtype = inp.dtype
        out_shape = _consume_shape(fdp)
    elif strategy == 3:
        out_dtype = _pick_dtype(fdp, for_out=True)
        out_shape = list(inp.shape)
    else:
        out_dtype = _pick_dtype(fdp, for_out=True)
        out_shape = _consume_shape(fdp)
    return _make_tensor(fdp, out_dtype, out_shape)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 5)

        if mode == 0:
            shape = _consume_shape(fdp)
            dtype = _pick_dtype(fdp)
            inp = _make_tensor(fdp, dtype=dtype, shape=shape)
            torch.exp(inp)

        elif mode == 1:
            shape = _consume_shape(fdp)
            dtype = _pick_dtype(fdp)
            inp = _make_tensor(fdp, dtype=dtype, shape=shape)
            out = _make_out_tensor(fdp, inp)
            torch.exp(inp, out=out)

        elif mode == 2:
            scalar_mode = fdp.ConsumeIntInRange(0, 3)
            if scalar_mode == 0:
                a = fdp.ConsumeIntInRange(-1, 8)
            elif scalar_mode == 1:
                a = fdp.ConsumeFloatInRange(-1.0, 1.0)
            elif scalar_mode == 2:
                a = complex(
                    fdp.ConsumeFloatInRange(-20.0, 20.0),
                    fdp.ConsumeFloatInRange(-20.0, 20.0),
                )
            else:
                a = _special_scalar_float(fdp)
            torch.exp(a)

        elif mode == 3:
            shape = []
            dtype = fdp.PickValueInList(
                [torch.float32, torch.float64, torch.complex64, torch.complex128]
            )
            inp = _make_tensor(fdp, dtype=dtype, shape=shape)
            torch.exp(inp)

        elif mode == 4:
            shape = fdp.PickValueInList([[1], [2], [1, 3], [2, 2], [1, 2, 3], [1, 1, 2, 2], [1, 1, 1, 2, 2]])
            dtype = fdp.PickValueInList(
                [torch.float32, torch.float64, torch.float16, torch.bfloat16, torch.complex64, torch.complex128]
            )
            inp = _make_tensor(fdp, dtype=dtype, shape=shape)
            if fdp.ConsumeBool():
                out = torch.empty_like(inp)
                torch.exp(inp, out=out)
            else:
                torch.exp(inp)

        else:
            shape = _consume_shape(fdp)
            dtype = fdp.PickValueInList([torch.float32, torch.float64])
            inp = _make_tensor(fdp, dtype=dtype, shape=shape)
            if fdp.ConsumeBool():
                out = _make_tensor(fdp, dtype=dtype, shape=list(inp.shape))
                torch.exp(input=inp, out=out)
            else:
                torch.exp(input=inp)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
