# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.addmv
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.addmv.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys

import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _pick_scalar_for_dtype(fdp, dtype):
    if fdp.ConsumeBool():
        if dtype in (torch.float32, torch.float64):
            return fdp.ConsumeFloatInRange(-8.0, 8.0)
        return fdp.ConsumeIntInRange(-8, 8)
    if dtype in (torch.float32, torch.float64):
        return fdp.PickValueInList([0.0, 1.0, -1.0, 2.0, -2.0, 0.5, -0.5])
    return fdp.PickValueInList([0, 1, -1, 2, -2])


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor_from_fdp(fdp, shape, dtype, allow_special=False):
    count = _numel(shape)
    if count == 0:
        return torch.empty(shape, dtype=dtype)
    if allow_special and fdp.ConsumeBool():
        vals = fdp.ConsumeFloatList(count)
    else:
        vals = fdp.ConsumeRegularFloatList(count)
    t = torch.tensor(vals, dtype=dtype)
    return t.reshape(shape)


def _make_input_tensor(fdp, n, dtype):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return _make_tensor_from_fdp(fdp, (n,), dtype, allow_special=True)
    if mode == 1:
        return _make_tensor_from_fdp(fdp, (1,), dtype, allow_special=True)
    if mode == 2:
        return torch.tensor(fdp.ConsumeRegularFloatList(1), dtype=dtype).reshape(())
    if mode == 3:
        return torch.empty((n,), dtype=dtype)
    return torch.zeros((n,), dtype=dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)

        n = fdp.ConsumeIntInRange(1, 8)
        m = fdp.ConsumeIntInRange(1, 64)

        mat = _make_tensor_from_fdp(fdp, (n, m), dtype, allow_special=fdp.ConsumeBool())
        vec = _make_tensor_from_fdp(fdp, (m,), dtype, allow_special=fdp.ConsumeBool())
        inp = _make_input_tensor(fdp, n, dtype)

        alpha = _pick_scalar_for_dtype(fdp, dtype)
        beta = _pick_scalar_for_dtype(fdp, dtype)

        use_out = fdp.ConsumeBool()
        use_keywords = fdp.ConsumeBool()

        if use_out:
            out_mode = fdp.ConsumeIntInRange(0, 3)
            if out_mode == 0:
                out = torch.empty((n,), dtype=dtype)
            elif out_mode == 1:
                out = torch.zeros((n,), dtype=dtype)
            elif out_mode == 2:
                out = _make_tensor_from_fdp(fdp, (n,), dtype, allow_special=True)
            else:
                out = torch.empty((n,), dtype=dtype).as_strided((n,), (1,))

            if use_keywords:
                torch.addmv(inp, mat, vec, beta=beta, alpha=alpha, out=out)
            else:
                torch.addmv(inp, mat, vec, out=out)
        else:
            call_mode = fdp.ConsumeIntInRange(0, 2)
            if call_mode == 0:
                torch.addmv(inp, mat, vec)
            elif call_mode == 1:
                torch.addmv(inp, mat, vec, beta=beta, alpha=alpha)
            else:
                torch.addmv(input=inp, mat=mat, vec=vec, beta=beta, alpha=alpha)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
