# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.can_cast
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.can_cast.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


ALL_DTYPES = [
    torch.bool,
    torch.uint8,
    torch.int8,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.float16,
    torch.bfloat16,
    torch.float32,
    torch.float64,
    torch.complex64,
    torch.complex128,
]

OPTIONAL_DTYPES = [
    "quint8",
    "qint8",
    "qint32",
    "quint4x2",
    "quint2x4",
    "bits1x8",
    "bits2x4",
    "bits4x2",
    "float8_e4m3fn",
    "float8_e4m3fnuz",
    "float8_e5m2",
    "float8_e5m2fnuz",
    "float8_e8m0fnu",
    "uint16",
    "uint32",
    "uint64",
    "complex32",
]


def _available_dtypes():
    dtypes = list(ALL_DTYPES)
    for name in OPTIONAL_DTYPES:
        dt = getattr(torch, name, None)
        if dt is not None:
            dtypes.append(dt)
    return dtypes


DTYPES = _available_dtypes()


def _pick_dtype(fdp):
    if fdp.ConsumeBool():
        return fdp.PickValueInList(DTYPES)
    idx = fdp.ConsumeIntInRange(0, max(len(DTYPES) - 1, 0))
    return DTYPES[idx]


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        from_dtype = _pick_dtype(fdp)
        to_dtype = _pick_dtype(fdp)

        if fdp.ConsumeBool():
            result = torch.can_cast(from_dtype, to_dtype)
        else:
            result = torch.can_cast(from_=from_dtype, to=to_dtype)

        if result:
            torch.promote_types(from_dtype, to_dtype)
        else:
            if fdp.ConsumeBool():
                torch.promote_types(to_dtype, from_dtype)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
