# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.is_complex
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.is_complex.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


DTYPES = [
    torch.complex64,
    torch.complex128,
    torch.float16,
    torch.float32,
    torch.float64,
    torch.bfloat16,
    torch.int8,
    torch.uint8,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.bool,
]


def _consume_shape(fdp):
    if fdp.ConsumeBool():
        return []
    rank = fdp.ConsumeIntInRange(0, 4)
    shape = []
    for _ in range(rank):
        shape.append(fdp.ConsumeIntInRange(0, 4))
    return shape


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp):
    dtype = fdp.PickValueInList(DTYPES)

    if fdp.ConsumeBool():
        shape = []
    else:
        shape = _consume_shape(fdp)

    n = _numel(shape)

    if dtype in (torch.complex64, torch.complex128):
        real = fdp.ConsumeRegularFloatList(n)
        imag = fdp.ConsumeRegularFloatList(n)
        if n == 0:
            t = torch.tensor([], dtype=dtype)
        else:
            vals = [complex(r, i) for r, i in zip(real, imag)]
            t = torch.tensor(vals, dtype=dtype)
    elif dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        if n == 0:
            t = torch.tensor([], dtype=dtype)
        else:
            t = torch.tensor(vals, dtype=dtype)
    elif dtype in (torch.float16, torch.float32, torch.float64, torch.bfloat16):
        vals = fdp.ConsumeRegularFloatList(n)
        if n == 0:
            t = torch.tensor([], dtype=dtype)
        else:
            t = torch.tensor(vals, dtype=dtype)
    else:
        vals = [fdp.ConsumeIntInRange(-16, 16) for _ in range(n)]
        if n == 0:
            t = torch.tensor([], dtype=dtype)
        else:
            t = torch.tensor(vals, dtype=dtype)

    if shape:
        t = t.reshape(shape)
    elif len(shape) == 0 and t.numel() == 1 and fdp.ConsumeBool():
        t = t.reshape(())
    elif len(shape) == 0 and t.numel() != 1:
        if t.numel() == 0:
            if fdp.ConsumeBool():
                t = t.reshape((0,))
        else:
            t = t.reshape(())

    if fdp.ConsumeBool():
        t = t.clone()
    if fdp.ConsumeBool() and t.dim() > 0:
        t = t.contiguous()
    return t


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        x = _make_tensor(fdp)

        if fdp.ConsumeBool():
            _ = torch.is_complex(x)
        else:
            _ = torch.is_complex(input=x)

        if fdp.ConsumeBool():
            y = x
            if y.dim() == 0 and fdp.ConsumeBool():
                y = y.unsqueeze(0)
            _ = torch.is_complex(y)

        if fdp.ConsumeBool():
            for dt in (torch.complex64, torch.complex128, torch.float32, torch.int32, torch.bool):
                if x.numel() == 0:
                    z = x.to(dtype=dt)
                else:
                    z = x.to(dtype=dt)
                _ = torch.is_complex(z)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
