# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.conv_transpose1d
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.functional.conv_transpose1d.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape3(fdp):
    n = fdp.ConsumeIntInRange(1, 4)
    c = fdp.ConsumeIntInRange(1, 16)
    l = fdp.ConsumeIntInRange(1, 32)
    return n, c, l


def _make_tensor(fdp, shape, dtype):
    numel = 1
    for s in shape:
        numel *= s
    vals = fdp.ConsumeFloatListInRange(numel, -8.0, 8.0)
    if len(vals) < numel:
        vals = vals + [0.0] * (numel - len(vals))
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _make_optional_bias(fdp, out_channels, dtype):
    if fdp.ConsumeBool():
        return None
    vals = fdp.ConsumeFloatListInRange(out_channels, -8.0, 8.0)
    if len(vals) < out_channels:
        vals = vals + [0.0] * (out_channels - len(vals))
    return torch.tensor(vals, dtype=dtype)


def _valid_groups(fdp, c_in, out_channels):
    divisors = []
    max_g = min(8, c_in, out_channels)
    for g in range(1, max_g + 1):
        if c_in % g == 0 and out_channels % g == 0:
            divisors.append(g)
    if not divisors:
        return 1
    return fdp.PickValueInList(divisors)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)

        n, c_in, l_in = _consume_shape3(fdp)
        kw = fdp.ConsumeIntInRange(1, 11)

        preliminary_out = fdp.ConsumeIntInRange(1, 16)
        groups = _valid_groups(fdp, c_in, preliminary_out)

        out_per_group = fdp.ConsumeIntInRange(1, max(1, 16 // groups))
        c_out = out_per_group * groups

        input_tensor = _make_tensor(fdp, (n, c_in, l_in), dtype)
        weight = _make_tensor(fdp, (c_in, c_out // groups, kw), dtype)
        bias = _make_optional_bias(fdp, c_out, dtype)

        stride = fdp.ConsumeIntInRange(1, 4)
        dilation = fdp.ConsumeIntInRange(1, 4)

        max_padding = dilation * (kw - 1)
        yaml_pad_cap = 4
        padding = fdp.ConsumeIntInRange(0, min(max_padding, yaml_pad_cap))

        max_output_padding = max(0, stride - 1)
        yaml_out_pad_cap = 4
        output_padding = fdp.ConsumeIntInRange(0, min(max_output_padding, yaml_out_pad_cap))

        call_mode = fdp.ConsumeIntInRange(0, 2)

        if call_mode == 0:
            F.conv_transpose1d(
                input_tensor,
                weight,
                bias,
                stride,
                padding,
                output_padding,
                groups,
                dilation,
            )
        elif call_mode == 1:
            F.conv_transpose1d(
                input=input_tensor,
                weight=weight,
                bias=bias,
                stride=(stride,),
                padding=(padding,),
                output_padding=(output_padding,),
                groups=groups,
                dilation=(dilation,),
            )
        else:
            F.conv_transpose1d(
                input=input_tensor,
                weight=weight,
                bias=bias,
                stride=stride,
                padding=padding,
                output_padding=output_padding,
                groups=groups,
                dilation=dilation,
            )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
