# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.rnn.pad_packed_sequence
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.rnn.pad_packed_sequence.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
from torch.nn.utils.rnn import pack_padded_sequence, pack_sequence, pad_packed_sequence


def _pick_tensor_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
    ])


def _pick_value_for_dtype(fdp, dtype):
    if dtype == torch.bool:
        return bool(fdp.ConsumeBool())
    if dtype in (torch.uint8, torch.int32, torch.int64):
        return int(fdp.ConsumeIntInRange(-8, 8))
    return float(fdp.ConsumeFloatInRange(-5.0, 5.0))


def _make_feature_tensor(fdp, shape, dtype):
    numel = 1
    for s in shape:
        numel *= s

    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(numel)]
    elif dtype == torch.uint8:
        vals = [fdp.ConsumeIntInRange(0, 8) for _ in range(numel)]
    elif dtype in (torch.int32, torch.int64):
        vals = [fdp.ConsumeIntInRange(-8, 8) for _ in range(numel)]
    else:
        vals = [fdp.ConsumeFloatInRange(-5.0, 5.0) for _ in range(numel)]

    t = torch.tensor(vals, dtype=dtype)
    return t.reshape(shape)


def _build_packed_from_padded(fdp):
    batch_first = fdp.ConsumeBool()
    rank = fdp.PickValueInList([2, 3, 4, 5])
    batch_size = fdp.ConsumeIntInRange(1, 6)
    max_len = fdp.ConsumeIntInRange(1, 8)

    lengths = [fdp.ConsumeIntInRange(1, max_len) for _ in range(batch_size)]
    dtype = _pick_tensor_dtype(fdp)

    feature_shape = []
    for _ in range(rank - 2):
        feature_shape.append(fdp.ConsumeIntInRange(1, 4))

    padded_shape = ([batch_size, max_len] if batch_first else [max_len, batch_size]) + feature_shape
    padded = _make_feature_tensor(fdp, padded_shape, dtype)

    lengths_tensor = torch.tensor(lengths, dtype=torch.int64)
    packed = pack_padded_sequence(
        padded,
        lengths_tensor,
        batch_first=batch_first,
        enforce_sorted=False,
    )
    return packed


def _build_packed_from_sequence_list(fdp):
    rank = fdp.PickValueInList([2, 3, 4, 5])
    batch_size = fdp.ConsumeIntInRange(1, 6)
    max_len = fdp.ConsumeIntInRange(1, 8)
    dtype = _pick_tensor_dtype(fdp)

    feature_shape = []
    for _ in range(rank - 2):
        feature_shape.append(fdp.ConsumeIntInRange(1, 4))

    seqs = []
    for _ in range(batch_size):
        seq_len = fdp.ConsumeIntInRange(1, max_len)
        shape = [seq_len] + feature_shape
        seqs.append(_make_feature_tensor(fdp, shape, dtype))

    enforce_sorted = fdp.ConsumeBool()
    if enforce_sorted:
        seqs.sort(key=lambda x: x.size(0), reverse=True)

    packed = pack_sequence(seqs, enforce_sorted=enforce_sorted)
    return packed


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        if fdp.ConsumeBool():
            sequence = _build_packed_from_padded(fdp)
        else:
            sequence = _build_packed_from_sequence_list(fdp)

        batch_first = fdp.ConsumeBool()
        padding_value = fdp.ConsumeFloatInRange(-1.0, 1.0)

        max_seq_len = int(sequence.batch_sizes.size(0))
        total_length_mode = fdp.ConsumeIntInRange(0, 4)
        if total_length_mode == 0:
            total_length = None
        elif total_length_mode == 1:
            total_length = fdp.ConsumeIntInRange(-1, 8)
        elif total_length_mode == 2:
            total_length = max_seq_len
        elif total_length_mode == 3:
            total_length = max_seq_len + fdp.ConsumeIntInRange(0, 4)
        else:
            total_length = max(0, max_seq_len - fdp.ConsumeIntInRange(0, 2))

        if fdp.ConsumeBool():
            out, lengths = pad_packed_sequence(
                sequence,
                batch_first=batch_first,
                padding_value=padding_value,
                total_length=total_length,
            )
        else:
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["batch_first"] = batch_first
            if fdp.ConsumeBool():
                kwargs["padding_value"] = padding_value
            if fdp.ConsumeBool():
                kwargs["total_length"] = total_length
            out, lengths = pad_packed_sequence(sequence, **kwargs)

        _ = out.shape
        _ = lengths.shape
        if lengths.numel() > 0:
            _ = int(lengths.max().item())
        if out.numel() > 0 and out.dtype != torch.bool:
            _ = out.reshape(-1)[0].item()
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
