# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.init.eye_
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.init.eye_.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    dtypes = [
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
    ]
    return fdp.PickValueInList(dtypes)


def _pick_device(fdp):
    if torch.cuda.is_available() and fdp.ConsumeBool():
        return torch.device("cuda")
    return torch.device("cpu")


def _shape_from_fdp(fdp):
    # Bias toward YAML-guided valid 2D shapes while still exploring edges.
    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        n = fdp.ConsumeIntInRange(1, 8)
        c = fdp.ConsumeIntInRange(1, 64)
    elif mode == 1:
        # include zeros to explore empty tensors
        n = fdp.ConsumeIntInRange(0, 8)
        c = fdp.ConsumeIntInRange(0, 64)
    elif mode == 2:
        # square matrices
        s = fdp.ConsumeIntInRange(0, 16)
        n, c = s, s
    elif mode == 3:
        # tiny boundaries
        choices = [0, 1, 2, 3, 4]
        n = fdp.PickValueInList(choices)
        c = fdp.PickValueInList(choices)
    elif mode == 4:
        # moderately larger but still cheap
        n = fdp.ConsumeIntInRange(0, 32)
        c = fdp.ConsumeIntInRange(0, 32)
    else:
        # rectangular extreme-ish aspect ratios
        if fdp.ConsumeBool():
            n = fdp.ConsumeIntInRange(0, 4)
            c = fdp.ConsumeIntInRange(0, 64)
        else:
            n = fdp.ConsumeIntInRange(0, 64)
            c = fdp.ConsumeIntInRange(0, 4)
    return (n, c)


def _make_base_tensor(fdp, shape, dtype, device):
    kind = fdp.ConsumeIntInRange(0, 6)
    if kind == 0:
        return torch.empty(shape, dtype=dtype, device=device)
    if kind == 1:
        return torch.zeros(shape, dtype=dtype, device=device)
    if kind == 2:
        return torch.ones(shape, dtype=dtype, device=device)
    if kind == 3:
        if dtype == torch.bool:
            vals = torch.randint(0, 2, shape, dtype=torch.int64, device=device)
            return vals.to(dtype=torch.bool)
        if dtype.is_floating_point:
            t = torch.randn(shape, device=device)
            return t.to(dtype=dtype)
        return torch.randint(0, 10, shape, dtype=torch.int64, device=device).to(dtype=dtype)
    if kind == 4:
        fill = fdp.ConsumeRegularFloat()
        if dtype == torch.bool:
            return torch.full(shape, bool(fill > 0), dtype=dtype, device=device)
        if dtype.is_floating_point:
            return torch.full(shape, fill, dtype=dtype, device=device)
        return torch.full(shape, int(fill), dtype=dtype, device=device)
    if kind == 5:
        # create from Python data to exercise a different creation path
        total = shape[0] * shape[1]
        if dtype == torch.bool:
            data = [fdp.ConsumeBool() for _ in range(total)]
        elif dtype.is_floating_point:
            data = [fdp.ConsumeFloatInRange(-10.0, 10.0) for _ in range(total)]
        else:
            data = [fdp.ConsumeIntInRange(-10, 10) for _ in range(total)]
        return torch.tensor(data, dtype=dtype, device=device).reshape(shape)
    return torch.empty_strided(shape, (shape[1] if len(shape) > 1 else 1, 1), dtype=dtype, device=device)


def _maybe_transform_tensor(fdp, tensor):
    t = tensor
    for _ in range(fdp.ConsumeIntInRange(0, 4)):
        op = fdp.ConsumeIntInRange(0, 6)
        if op == 0:
            t = t.contiguous()
        elif op == 1:
            t = t.clone()
        elif op == 2:
            if t.numel() > 0:
                t = t.transpose(0, 1).transpose(0, 1)
        elif op == 3:
            if t.numel() > 0 and t.shape[0] > 0 and t.shape[1] > 0:
                t = t.narrow(0, 0, t.shape[0]).narrow(1, 0, t.shape[1])
        elif op == 4:
            t = t.detach()
        elif op == 5:
            # preserve 2D shape while exercising view logic
            t = t.reshape(t.shape)
        else:
            if t.numel() > 0:
                t = t.as_strided(t.shape, t.stride())
    return t


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)
        device = _pick_device(fdp)
        shape = _shape_from_fdp(fdp)
        tensor = _make_base_tensor(fdp, shape, dtype, device)
        tensor = _maybe_transform_tensor(fdp, tensor)

        if fdp.ConsumeBool():
            result = torch.nn.init.eye_(tensor)
        else:
            result = torch.nn.init.eye_(tensor=tensor)

        if fdp.ConsumeBool():
            _ = result.shape
            _ = result.dtype
            if result.numel() > 0:
                _ = result.flatten()[0].item()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
