# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.bitwise_and
# source_yaml_count=6
# source_api_txt=/root/api_txt/torch.bitwise_and.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


INTEGRAL_DTYPES = [
    torch.bool,
    torch.uint8,
    torch.int8,
    torch.int16,
    torch.int32,
    torch.int64,
]

SMALL_INT_VALUES = [
    -129, -128, -127, -65, -64, -63, -33, -32, -31,
    -17, -16, -15, -9, -8, -7, -3, -2, -1,
    0, 1, 2, 3, 7, 8, 9, 15, 16, 17, 31, 32, 33,
    63, 64, 65, 127, 128, 129, 255, 256,
]


def _consume_shape(fdp, fixed_rank=None):
    if fixed_rank is None:
        rank = fdp.PickValueInList([0, 1, 2, 3, 4, 5])
    else:
        rank = fixed_rank
    if rank == 0:
        return ()
    dims = []
    for _ in range(rank):
        dims.append(fdp.PickValueInList([0, 1, 2, 3, 4, 5, 8]))
    return tuple(dims)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _scalar_for_dtype(fdp, dtype):
    if dtype is torch.bool:
        return fdp.ConsumeBool()
    return fdp.PickValueInList(SMALL_INT_VALUES)


def _tensor_from_shape_dtype(fdp, shape, dtype):
    n = _numel(shape)
    if dtype is torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = [fdp.PickValueInList(SMALL_INT_VALUES) for _ in range(n)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _broadcast_shape(base_shape, fdp):
    rank = len(base_shape)
    if rank == 0:
        return ()
    result = []
    for dim in base_shape:
        if fdp.ConsumeBool():
            result.append(dim)
        else:
            result.append(1)
    return tuple(result)


def _make_out_tensor(fdp, shape, dtype):
    if fdp.ConsumeBool():
        return torch.empty(shape, dtype=dtype)
    alt_dtype = dtype if fdp.ConsumeBool() else fdp.PickValueInList(INTEGRAL_DTYPES)
    return _tensor_from_shape_dtype(fdp, shape, alt_dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 5)
        dtype = fdp.PickValueInList(INTEGRAL_DTYPES)

        if mode == 0:
            shape = _consume_shape(fdp)
            inp = _tensor_from_shape_dtype(fdp, shape, dtype)
            other = _scalar_for_dtype(fdp, dtype)
            if fdp.ConsumeBool():
                torch.bitwise_and(inp, other)
            else:
                out = _make_out_tensor(fdp, shape, dtype)
                torch.bitwise_and(inp, other, out=out)

        elif mode == 1:
            shape = _consume_shape(fdp)
            other = _tensor_from_shape_dtype(fdp, shape, dtype)
            self_scalar = _scalar_for_dtype(fdp, dtype)
            if fdp.ConsumeBool():
                torch.bitwise_and(self_scalar, other)
            else:
                out = _make_out_tensor(fdp, shape, dtype)
                torch.bitwise_and(self_scalar, other, out=out)

        elif mode == 2:
            shape = _consume_shape(fdp, fixed_rank=1)
            a = _tensor_from_shape_dtype(fdp, shape, dtype)
            b = _tensor_from_shape_dtype(fdp, shape, dtype)
            if fdp.ConsumeBool():
                torch.bitwise_and(a, b)
            else:
                out = _make_out_tensor(fdp, shape, dtype)
                torch.bitwise_and(a, b, out=out)

        elif mode == 3:
            rank = fdp.PickValueInList([1, 2, 3, 4, 5])
            shape = _consume_shape(fdp, fixed_rank=rank)
            a = _tensor_from_shape_dtype(fdp, shape, dtype)
            b = _tensor_from_shape_dtype(fdp, shape, dtype)
            if fdp.ConsumeBool():
                torch.bitwise_and(a, b)
            else:
                out = _make_out_tensor(fdp, shape, dtype)
                torch.bitwise_and(a, b, out=out)

        elif mode == 4:
            shape = _consume_shape(fdp)
            a = _tensor_from_shape_dtype(fdp, shape, dtype)
            bshape = _broadcast_shape(shape, fdp)
            b = _tensor_from_shape_dtype(fdp, bshape, dtype)
            if fdp.ConsumeBool():
                torch.bitwise_and(a, b)
            else:
                out = _make_out_tensor(fdp, shape, dtype)
                torch.bitwise_and(a, b, out=out)

        else:
            if fdp.ConsumeBool():
                a = torch.tensor(_scalar_for_dtype(fdp, dtype), dtype=dtype)
                b = torch.tensor(_scalar_for_dtype(fdp, dtype), dtype=dtype)
            else:
                shape = ()
                a = _tensor_from_shape_dtype(fdp, shape, dtype)
                b = _tensor_from_shape_dtype(fdp, shape, dtype)
            if fdp.ConsumeBool():
                torch.bitwise_and(a, b)
            else:
                out = _make_out_tensor(fdp, (), dtype)
                torch.bitwise_and(a, b, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
