# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.quantization.prepare
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.quantization.prepare.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import copy
import torch
import torch.nn as nn

try:
    import torch.ao.quantization as tq
except Exception:
    import torch.quantization as tq


class TinyLeaf(nn.Module):
    def __init__(self, in_f, out_f, use_relu):
        super().__init__()
        self.linear = nn.Linear(in_f, out_f)
        self.relu = nn.ReLU() if use_relu else nn.Identity()

    def forward(self, x):
        return self.relu(self.linear(x))


class TinyBlock(nn.Module):
    def __init__(self, in_ch, out_ch, kernel_size, use_bn, use_relu):
        super().__init__()
        padding = kernel_size // 2
        layers = [nn.Conv2d(in_ch, out_ch, kernel_size=kernel_size, padding=padding)]
        if use_bn:
            layers.append(nn.BatchNorm2d(out_ch))
        layers.append(nn.ReLU() if use_relu else nn.Identity())
        self.seq = nn.Sequential(*layers)

    def forward(self, x):
        return self.seq(x)


class FuzzModel(nn.Module):
    def __init__(self, choice_a, choice_b, choice_c, choice_d, choice_e):
        super().__init__()
        self.quant = tq.QuantStub()
        self.dequant = tq.DeQuantStub()

        conv_out = 2 + (choice_a % 4)
        k = 1 if (choice_b % 2 == 0) else 3
        self.block1 = TinyBlock(3, conv_out, k, bool(choice_c % 2), True)
        self.block2 = TinyBlock(conv_out, conv_out, 3, bool(choice_d % 2), bool(choice_e % 2))
        self.avg = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = TinyLeaf(conv_out, 2 + (choice_b % 5), bool(choice_a % 2))
        self.float_fn = torch.nn.quantized.FloatFunctional()
        self.skip = nn.Identity()

    def forward(self, x):
        x = self.quant(x)
        y = self.block1(x)
        z = self.block2(y)
        z = self.float_fn.add(z, self.skip(y))
        z = self.avg(z)
        z = torch.flatten(z, 1)
        z = self.fc(z)
        z = self.dequant(z)
        return z


def _pick_qconfig(fdp):
    candidates = []
    if hasattr(tq, "default_qconfig"):
        candidates.append(tq.default_qconfig)
    if hasattr(tq, "default_per_channel_qconfig"):
        candidates.append(tq.default_per_channel_qconfig)
    if hasattr(tq, "default_dynamic_qconfig"):
        candidates.append(tq.default_dynamic_qconfig)
    if hasattr(tq, "float16_dynamic_qconfig"):
        candidates.append(tq.float16_dynamic_qconfig)
    if hasattr(tq, "default_qat_qconfig"):
        candidates.append(tq.default_qat_qconfig)
    if hasattr(tq, "default_weight_only_qconfig"):
        candidates.append(tq.default_weight_only_qconfig)

    if not candidates:
        return None
    qconfig = fdp.PickValueInList(candidates)
    return qconfig


def _build_model(fdp):
    model = FuzzModel(
        fdp.ConsumeIntInRange(0, 7),
        fdp.ConsumeIntInRange(0, 7),
        fdp.ConsumeIntInRange(0, 7),
        fdp.ConsumeIntInRange(0, 7),
        fdp.ConsumeIntInRange(0, 7),
    )
    qconfig = _pick_qconfig(fdp)
    if qconfig is not None:
        model.qconfig = qconfig

    modules = list(model.modules())
    for m in modules:
        if fdp.ConsumeBool():
            qc = _pick_qconfig(fdp)
            if qc is not None:
                m.qconfig = qc
        elif fdp.ConsumeBool():
            m.qconfig = None
    return model


def _pick_module_types(fdp):
    base = [
        nn.Linear,
        nn.Conv2d,
        nn.ReLU,
        nn.BatchNorm2d,
        nn.Sequential,
        TinyLeaf,
        TinyBlock,
    ]
    count = fdp.ConsumeIntInRange(0, len(base))
    chosen = []
    for cls in base:
        if len(chosen) >= count:
            break
        if fdp.ConsumeBool():
            chosen.append(cls)
    if fdp.ConsumeBool():
        chosen = []
    return chosen if chosen else None


def _pick_prepare_custom_config_dict(fdp):
    if not fdp.ConsumeBool():
        return None
    cfg = {}

    if fdp.ConsumeBool():
        preserved = []
        for name in ["block1", "block2", "fc", "avg", "seq", "linear", "relu"]:
            if fdp.ConsumeBool():
                preserved.append(name)
        if preserved:
            cfg["preserved_attributes"] = preserved

    if fdp.ConsumeBool():
        cfg["non_traceable_module_name"] = [
            name for name in ["block1", "block2", "fc"] if fdp.ConsumeBool()
        ]

    if fdp.ConsumeBool():
        cfg["non_traceable_module_class"] = [
            cls for cls in [TinyLeaf, TinyBlock] if fdp.ConsumeBool()
        ]

    return cfg


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        model = _build_model(fdp)
        inplace = fdp.ConsumeBool()
        allow_list = _pick_module_types(fdp)
        observer_non_leaf_module_list = _pick_module_types(fdp)
        prepare_custom_config_dict = _pick_prepare_custom_config_dict(fdp)

        if not inplace:
            model = copy.deepcopy(model)

        call_style = fdp.ConsumeIntInRange(0, 2)
        if call_style == 0:
            prepared = tq.prepare(
                model,
                inplace=inplace,
                allow_list=allow_list,
                observer_non_leaf_module_list=observer_non_leaf_module_list,
                prepare_custom_config_dict=prepare_custom_config_dict,
            )
        elif call_style == 1:
            prepared = tq.prepare(
                model,
                inplace,
                allow_list,
                observer_non_leaf_module_list,
                prepare_custom_config_dict,
            )
        else:
            kwargs = {"inplace": inplace}
            if fdp.ConsumeBool():
                kwargs["allow_list"] = allow_list
            if fdp.ConsumeBool():
                kwargs["observer_non_leaf_module_list"] = observer_non_leaf_module_list
            if fdp.ConsumeBool():
                kwargs["prepare_custom_config_dict"] = prepare_custom_config_dict
            prepared = tq.prepare(model, **kwargs)

        if isinstance(prepared, nn.Module) and fdp.ConsumeBool():
            batch = fdp.ConsumeIntInRange(1, 3)
            h = fdp.ConsumeIntInRange(2, 8)
            w = fdp.ConsumeIntInRange(2, 8)
            x = torch.randn(batch, 3, h, w)
            prepared.eval()
            try:
                prepared(x)
            except (
                RuntimeError,
                TypeError,
                ValueError,
                IndexError,
                AssertionError,
                NotImplementedError,
            ):
                return
            except Exception:
                return

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
