# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.imag
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.imag.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _consume_shape_1d(fdp):
    if fdp.ConsumeBool():
        n = fdp.ConsumeIntInRange(1, 8)
    else:
        n = fdp.PickValueInList([1, 2, 3, 4, 5, 8])
    return (n,)


def _make_base_values(fdp, numel):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(numel)
    elif mode == 1:
        vals = [0.0] * numel
    elif mode == 2:
        vals = []
        for _ in range(numel):
            vals.append(float(fdp.PickValueInList([-1.0, 0.0, 1.0, 2.0, -2.0, 3.14159265])))
    elif mode == 3:
        vals = []
        for _ in range(numel):
            vals.append(float(fdp.ConsumeIntInRange(-8, 8)))
    else:
        vals = fdp.ConsumeFloatListInRange(numel, -100.0, 100.0)
    return vals


def _make_complex_tensor(fdp):
    shape = _consume_shape_1d(fdp)
    numel = shape[0]
    complex_dtype = fdp.PickValueInList([torch.complex64, torch.complex128])

    real_vals = _make_base_values(fdp, numel)
    imag_vals = _make_base_values(fdp, numel)

    base_float_dtype = torch.float32 if complex_dtype == torch.complex64 else torch.float64
    real = torch.tensor(real_vals, dtype=base_float_dtype).reshape(shape)
    imag = torch.tensor(imag_vals, dtype=base_float_dtype).reshape(shape)

    if fdp.ConsumeBool():
        real = real.contiguous()
    else:
        real = real.clone()

    if fdp.ConsumeBool():
        imag = imag.contiguous()
    else:
        imag = imag.clone()

    t = torch.complex(real, imag)

    if fdp.ConsumeBool():
        t = t.requires_grad_(False)

    return t


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        x = _make_complex_tensor(fdp)

        if fdp.ConsumeBool():
            y = torch.imag(x)
        else:
            y = torch.imag(input=x)

        if fdp.ConsumeBool():
            _ = y.shape
            _ = y.dtype
            _ = y.numel()

        if y.numel() > 0:
            idx = fdp.ConsumeIntInRange(0, y.numel() - 1)
            _ = y.reshape(-1)[idx].item()

        if fdp.ConsumeBool():
            x2 = x.clone()
            y2 = torch.imag(x2)
            if y2.numel() > 0:
                flat_x2 = x2.reshape(-1)
                flat_y2 = y2.reshape(-1)
                i = fdp.ConsumeIntInRange(0, y2.numel() - 1)
                before = flat_y2[i].item()
                flat_x2[i] = complex(float(flat_x2[i].real), before + 1.0)
                _ = flat_y2[i].item()

        if fdp.ConsumeBool():
            _ = y.contiguous()
        else:
            _ = y.clone()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
