# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.quantization.prepare_qat
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.quantization.prepare_qat.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import copy
import torch
import torch.nn as nn

try:
    from torch.ao.quantization import get_default_qat_qconfig, get_default_qat_qconfig_mapping
except Exception:
    get_default_qat_qconfig = None
    get_default_qat_qconfig_mapping = None


def _consume_shape(fdp, min_rank=1, max_rank=4, min_dim=1, max_dim=8):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    return [fdp.ConsumeIntInRange(min_dim, max_dim) for _ in range(rank)]


def _choose_activation():
    return [
        nn.ReLU,
        nn.ReLU6,
        nn.LeakyReLU,
        nn.ELU,
        nn.Hardswish,
        nn.SiLU,
    ]


class FuzzModel(nn.Module):
    def __init__(self, in_ch, mid_ch, out_ch, linear_out, conv_dim, variant, act_cls):
        super().__init__()
        self.variant = variant
        self.conv_dim = conv_dim

        if conv_dim == 1:
            Conv = nn.Conv1d
            BN = nn.BatchNorm1d
            pool = nn.AdaptiveAvgPool1d(1)
        elif conv_dim == 2:
            Conv = nn.Conv2d
            BN = nn.BatchNorm2d
            pool = nn.AdaptiveAvgPool2d((1, 1))
        else:
            Conv = nn.Conv3d
            BN = nn.BatchNorm3d
            pool = nn.AdaptiveAvgPool3d((1, 1, 1))

        k1 = 3
        k2 = 1

        self.conv1 = Conv(in_ch, mid_ch, kernel_size=k1, stride=1, padding=1, bias=(variant % 2 == 0))
        self.bn1 = BN(mid_ch)
        self.act1 = act_cls()
        self.conv2 = Conv(mid_ch, out_ch, kernel_size=k2, stride=1, padding=0, bias=(variant % 3 == 0))
        self.bn2 = BN(out_ch)
        self.act2 = act_cls()
        self.pool = pool
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(out_ch, linear_out, bias=(variant % 2 == 1))
        self.act3 = act_cls()
        self.fc2 = nn.Linear(linear_out, max(1, linear_out // 2), bias=True)

        if variant % 5 == 0:
            self.skip_proj = nn.Linear(max(1, linear_out // 2), max(1, linear_out // 2))
        else:
            self.skip_proj = None

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.act1(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = self.act2(x)
        x = self.pool(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.act3(x)
        x = self.fc2(x)
        if self.skip_proj is not None and x.shape[-1] > 0:
            x = self.skip_proj(x) + x
        return x


def _make_model(fdp):
    conv_dim = fdp.PickValueInList([1, 2, 3])
    in_ch = fdp.ConsumeIntInRange(1, 4)
    mid_ch = fdp.ConsumeIntInRange(1, 8)
    out_ch = fdp.ConsumeIntInRange(1, 8)
    linear_out = fdp.ConsumeIntInRange(1, 16)
    variant = fdp.ConsumeIntInRange(0, 15)
    act_cls = fdp.PickValueInList(_choose_activation())

    model = FuzzModel(
        in_ch=in_ch,
        mid_ch=mid_ch,
        out_ch=out_ch,
        linear_out=linear_out,
        conv_dim=conv_dim,
        variant=variant,
        act_cls=act_cls,
    )
    model.train()

    return model, conv_dim, in_ch


def _assign_qconfig(model, fdp):
    backend = fdp.PickValueInList(["fbgemm", "qnnpack"])
    qconfig = None
    if get_default_qat_qconfig is not None:
        qconfig = get_default_qat_qconfig(backend)

    if qconfig is None:
        return

    mode = fdp.ConsumeIntInRange(0, 3)
    if mode == 0:
        model.qconfig = qconfig
    elif mode == 1:
        model.qconfig = qconfig
        for name, mod in model.named_modules():
            if isinstance(mod, (nn.Conv1d, nn.Conv2d, nn.Conv3d, nn.Linear)):
                mod.qconfig = qconfig
    elif mode == 2:
        for name, mod in model.named_modules():
            if name == "":
                continue
            if isinstance(mod, (nn.Conv1d, nn.Conv2d, nn.Conv3d, nn.Linear, nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d)):
                mod.qconfig = qconfig
    else:
        model.qconfig = qconfig
        for name, mod in model.named_modules():
            if isinstance(mod, (nn.ReLU, nn.ReLU6, nn.LeakyReLU, nn.ELU, nn.Hardswish, nn.SiLU)):
                mod.qconfig = qconfig


def _make_mapping(fdp):
    choice = fdp.ConsumeIntInRange(0, 5)
    if choice == 0:
        return None
    if choice == 1 and get_default_qat_qconfig_mapping is not None:
        # Intentionally not used as "mapping" for prepare_qat because the API
        # expects a module-class mapping dict; keep fallback to None/empty/custom dicts.
        return {}
    if choice == 2:
        return {}
    if choice == 3:
        return {
            nn.Linear: nn.qat.Linear,
        }
    if choice == 4:
        return {
            nn.Linear: nn.qat.Linear,
            nn.Conv2d: nn.qat.Conv2d,
        }
    return {
        nn.Linear: nn.qat.Linear,
        nn.Conv1d: getattr(nn.qat, "Conv1d", nn.qat.Conv2d),
        nn.Conv2d: nn.qat.Conv2d,
        nn.Conv3d: getattr(nn.qat, "Conv3d", nn.qat.Conv2d),
    }


def _maybe_run_model(model, conv_dim, in_ch, fdp):
    batch = fdp.ConsumeIntInRange(1, 3)
    spatial = _consume_shape(fdp, min_rank=conv_dim, max_rank=conv_dim, min_dim=1, max_dim=6)
    shape = [batch, in_ch] + spatial
    x = torch.randn(shape, dtype=torch.float32)
    with torch.no_grad():
        model(x)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)

    try:
        model, conv_dim, in_ch = _make_model(fdp)
        _assign_qconfig(model, fdp)
        mapping = _make_mapping(fdp)
        inplace = fdp.ConsumeBool()

        call_style = fdp.ConsumeIntInRange(0, 2)

        target_model = model if inplace else copy.deepcopy(model)

        if call_style == 0:
            prepared = torch.quantization.prepare_qat(target_model, mapping=mapping, inplace=inplace)
        elif call_style == 1:
            prepared = torch.quantization.prepare_qat(target_model, mapping, inplace)
        else:
            if mapping is None:
                prepared = torch.quantization.prepare_qat(target_model, inplace=inplace)
            else:
                prepared = torch.quantization.prepare_qat(target_model, mapping=mapping, inplace=inplace)

        if isinstance(prepared, nn.Module):
            _maybe_run_model(prepared, conv_dim, in_ch, fdp)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
