# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.jit.trace
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.jit.trace.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn as nn


DTYPES = [torch.float32, torch.float64]


def _consume_shape(fdp):
    rank = fdp.PickValueInList([1, 2, 3, 4, 5])
    if rank == 1:
        return [fdp.ConsumeIntInRange(1, 8)]
    if rank == 2:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
        ]
    if rank == 3:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
            fdp.ConsumeIntInRange(1, 16),
        ]
    if rank == 4:
        return [
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        ]
    return [
        fdp.ConsumeIntInRange(1, 4),
        fdp.ConsumeIntInRange(1, 8),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
    ]


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype):
    count = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        t = torch.zeros(shape, dtype=dtype)
    elif mode == 1:
        t = torch.ones(shape, dtype=dtype)
    elif mode == 2:
        vals = fdp.ConsumeRegularFloatList(count)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 3:
        vals = fdp.ConsumeIntListInRange(count, -8, 8)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 4:
        start = fdp.ConsumeFloatInRange(-5.0, 5.0)
        step = fdp.ConsumeFloatInRange(-3.0, 3.0)
        vals = [start + step * i for i in range(count)]
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    else:
        vals = []
        for _ in range(count):
            vals.append(fdp.PickValueInList([-1.0, 0.0, 1.0, 2.0, -2.0, 3.5]))
        t = torch.tensor(vals, dtype=dtype).reshape(shape)

    if fdp.ConsumeBool():
        t = t.contiguous()
    return t


class UnaryModule(nn.Module):
    def __init__(self, op_kind, scale, bias):
        super().__init__()
        self.op_kind = op_kind
        self.register_buffer("scale_buf", torch.tensor(scale))
        self.register_buffer("bias_buf", torch.tensor(bias))

    def forward(self, x):
        y = x * self.scale_buf.to(dtype=x.dtype) + self.bias_buf.to(dtype=x.dtype)
        if self.op_kind == 0:
            return y
        if self.op_kind == 1:
            return torch.relu(y)
        if self.op_kind == 2:
            return torch.sigmoid(y)
        if self.op_kind == 3:
            return torch.tanh(y)
        if self.op_kind == 4:
            return y + x
        if self.op_kind == 5:
            return y * y
        return torch.neg(y)


class BinaryModule(nn.Module):
    def __init__(self, op_kind):
        super().__init__()
        self.op_kind = op_kind

    def forward(self, x, y):
        if self.op_kind == 0:
            return x + y
        if self.op_kind == 1:
            return x - y
        if self.op_kind == 2:
            return x * y
        if self.op_kind == 3:
            return x / (y.abs() + 1.0)
        if self.op_kind == 4:
            return torch.maximum(x, y)
        return torch.minimum(x, y)


def _make_check_inputs_unary(fdp, shape, dtype):
    checks = []
    count = fdp.ConsumeIntInRange(0, 2)
    for _ in range(count):
        checks.append((_make_tensor(fdp, shape, dtype),))
    return checks if count > 0 else None


def _make_check_inputs_binary(fdp, shape, dtype):
    checks = []
    count = fdp.ConsumeIntInRange(0, 2)
    for _ in range(count):
        checks.append((
            _make_tensor(fdp, shape, dtype),
            _make_tensor(fdp, shape, dtype),
        ))
    return checks if count > 0 else None


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = fdp.PickValueInList(DTYPES)
        shape = _consume_shape(fdp)

        use_module = fdp.ConsumeBool()
        use_kwargs = fdp.ConsumeBool()
        arity = fdp.ConsumeIntInRange(1, 2)

        check_trace = fdp.ConsumeBool()
        strict = fdp.ConsumeBool()
        optimize = None if fdp.ConsumeBool() else fdp.ConsumeBool()
        force_outplace = fdp.ConsumeBool()
        check_tolerance = fdp.ConsumeFloatInRange(0.0, 1e-2)

        if arity == 1:
            x = _make_tensor(fdp, shape, dtype)
            scale = fdp.ConsumeFloatInRange(-4.0, 4.0)
            bias = fdp.ConsumeFloatInRange(-4.0, 4.0)
            op_kind = fdp.ConsumeIntInRange(0, 6)

            if use_module:
                func = UnaryModule(op_kind, scale, bias)
            else:
                def func(inp, op_kind=op_kind, scale=scale, bias=bias):
                    y = inp * scale + bias
                    if op_kind == 0:
                        return y
                    if op_kind == 1:
                        return torch.relu(y)
                    if op_kind == 2:
                        return torch.sigmoid(y)
                    if op_kind == 3:
                        return torch.tanh(y)
                    if op_kind == 4:
                        return y + inp
                    if op_kind == 5:
                        return y * y
                    return torch.neg(y)

            kwargs = {
                "optimize": optimize,
                "check_trace": check_trace,
                "check_inputs": _make_check_inputs_unary(fdp, shape, dtype),
                "check_tolerance": check_tolerance,
                "strict": strict,
                "_force_outplace": force_outplace,
            }

            if use_kwargs:
                traced = torch.jit.trace(
                    func,
                    example_inputs=None,
                    example_kwarg_inputs={"inp": x},
                    **kwargs
                )
                if fdp.ConsumeBool():
                    traced(inp=x)
                else:
                    traced(**{"inp": x})
            else:
                traced = torch.jit.trace(func, x, **kwargs)
                traced(x)
        else:
            x = _make_tensor(fdp, shape, dtype)
            y = _make_tensor(fdp, shape, dtype)
            op_kind = fdp.ConsumeIntInRange(0, 5)

            if use_module:
                func = BinaryModule(op_kind)
            else:
                def func(a, b, op_kind=op_kind):
                    if op_kind == 0:
                        return a + b
                    if op_kind == 1:
                        return a - b
                    if op_kind == 2:
                        return a * b
                    if op_kind == 3:
                        return a / (b.abs() + 1.0)
                    if op_kind == 4:
                        return torch.maximum(a, b)
                    return torch.minimum(a, b)

            kwargs = {
                "optimize": optimize,
                "check_trace": check_trace,
                "check_inputs": _make_check_inputs_binary(fdp, shape, dtype),
                "check_tolerance": check_tolerance,
                "strict": strict,
                "_force_outplace": force_outplace,
            }

            if use_kwargs:
                traced = torch.jit.trace(
                    func,
                    example_inputs=None,
                    example_kwarg_inputs={"a": x, "b": y},
                    **kwargs
                )
                if fdp.ConsumeBool():
                    traced(a=x, b=y)
                else:
                    traced(**{"a": x, "b": y})
            else:
                traced = torch.jit.trace(func, (x, y), **kwargs)
                traced(x, y)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
