# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.random.manual_seed
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.random.manual_seed.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


INT64_MIN = -0x8000_0000_0000_0000
UINT64_MAX = 0xFFFF_FFFF_FFFF_FFFF


def _consume_seed(fdp):
    mode = fdp.ConsumeIntInRange(0, 7)
    if mode == 0:
        return fdp.ConsumeIntInRange(-1, 8)
    if mode == 1:
        return INT64_MIN
    if mode == 2:
        return UINT64_MAX
    if mode == 3:
        return 0
    if mode == 4:
        return -1
    if mode == 5:
        return 1
    if mode == 6:
        return fdp.ConsumeInt(8)
    return fdp.ConsumeUInt(8)


def _make_generator(fdp):
    if fdp.ConsumeBool() and torch.cuda.is_available():
        try:
            idx = 0
            if torch.cuda.device_count() > 1:
                idx = fdp.ConsumeIntInRange(0, torch.cuda.device_count() - 1)
            return torch.Generator(device=f"cuda:{idx}")
        except Exception:
            pass
    return torch.Generator()


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        seed = _consume_seed(fdp)

        if fdp.ConsumeBool():
            gen = torch.random.manual_seed(seed)
        else:
            gen = _make_generator(fdp)
            gen.manual_seed(seed)

        if fdp.ConsumeBool():
            n = fdp.ConsumeIntInRange(0, 8)
            dtype = fdp.PickValueInList(
                [
                    torch.float32,
                    torch.float64,
                    torch.float16,
                    torch.int64,
                    torch.int32,
                    torch.int16,
                    torch.uint8,
                ]
            )
            device = "cpu"
            if fdp.ConsumeBool() and torch.cuda.is_available():
                try:
                    idx = 0
                    if torch.cuda.device_count() > 1:
                        idx = fdp.ConsumeIntInRange(0, torch.cuda.device_count() - 1)
                    device = f"cuda:{idx}"
                except Exception:
                    device = "cpu"
            try:
                torch.rand(n, generator=gen, device=device)
            except Exception:
                try:
                    if dtype.is_floating_point:
                        torch.rand(n, generator=gen, device=device, dtype=dtype)
                    else:
                        torch.randint(0, max(1, n + 1), (n,), generator=gen, device=device, dtype=dtype)
                except Exception:
                    pass

        if fdp.ConsumeBool():
            torch.initial_seed()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
