# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.dropout
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.functional.dropout.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _pick_dtype(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
    ])


def _make_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 5)
    shape = []
    for _ in range(rank):
        dim = fdp.PickValueInList([0, 1, 2, 3, 4, 5, 8, 16])
        shape.append(dim)
    return tuple(shape)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_tensor(fdp):
    dtype = _pick_dtype(fdp)
    shape = _make_shape(fdp)
    total = _numel(shape)

    strategy = fdp.ConsumeIntInRange(0, 5)

    if total == 0:
        return torch.empty(shape, dtype=dtype)

    if strategy == 0:
        vals = fdp.ConsumeRegularFloatList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if strategy == 1:
        vals = fdp.ConsumeFloatListInRange(total, -1.0, 1.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if strategy == 2:
        vals = fdp.ConsumeFloatListInRange(total, -100.0, 100.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if strategy == 3:
        base = fdp.PickValueInList([
            -0.0, 0.0, 1.0, -1.0, 0.5, -0.5, 2.0, -2.0, 1e-6, -1e-6, 1e6, -1e6
        ])
        return torch.full(shape, base, dtype=dtype)
    if strategy == 4:
        vals = [float(v) for v in fdp.ConsumeIntListInRange(total, -8, 8)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    vals = fdp.ConsumeRegularFloatList(total)
    t = torch.tensor(vals, dtype=dtype).reshape(shape)
    if total > 0:
        t = t.contiguous()
    return t


def _make_probability(fdp):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return fdp.ConsumeProbability()
    if mode == 1:
        return fdp.PickValueInList([0.0, 1.0, 0.5, 1e-12, 1.0 - 1e-12, 0.25, 0.75])
    if mode == 2:
        return fdp.ConsumeFloatInRange(0.0, 1.0)
    if mode == 3:
        numerator = fdp.ConsumeIntInRange(0, 1000)
        return numerator / 1000.0
    return fdp.PickValueInList([0.0, 0.1, 0.2, 0.3, 0.7, 0.8, 0.9, 1.0])


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        x = _make_tensor(fdp)
        p = _make_probability(fdp)
        training = fdp.ConsumeBool()
        inplace = fdp.ConsumeBool()

        call_style = fdp.ConsumeIntInRange(0, 4)

        if inplace and not x.is_leaf:
            x = x.clone()

        if call_style == 0:
            F.dropout(x, p, training, inplace)
        elif call_style == 1:
            F.dropout(input=x, p=p, training=training, inplace=inplace)
        elif call_style == 2:
            F.dropout(x, p=p, training=training, inplace=inplace)
        elif call_style == 3:
            F.dropout(input=x, p=p, training=training)
        else:
            F.dropout(x, p, training)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
