# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.autograd.functional.vjp
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.autograd.functional.vjp.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_float_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _shape_for_rank(fdp, rank):
    if rank <= 0:
        return ()
    if rank == 1:
        return (fdp.ConsumeIntInRange(1, 8),)
    if rank == 2:
        return (
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
        )
    if rank == 3:
        return (
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        )
    if rank == 4:
        return (
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 6),
            fdp.ConsumeIntInRange(1, 6),
            fdp.ConsumeIntInRange(1, 6),
        )
    return (
        fdp.ConsumeIntInRange(1, 3),
        fdp.ConsumeIntInRange(1, 4),
        fdp.ConsumeIntInRange(1, 4),
        fdp.ConsumeIntInRange(1, 4),
        fdp.ConsumeIntInRange(1, 4),
    )


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype, requires_grad=False):
    n = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 5)
    if n == 0:
        t = torch.empty(shape, dtype=dtype)
    elif mode == 0:
        vals = fdp.ConsumeRegularFloatList(n)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 1:
        vals = fdp.ConsumeIntListInRange(n, -3, 3)
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 2:
        base = fdp.ConsumeFloatInRange(-5.0, 5.0)
        step = fdp.ConsumeFloatInRange(-2.0, 2.0)
        vals = [base + step * i for i in range(n)]
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    elif mode == 3:
        t = torch.zeros(shape, dtype=dtype)
    elif mode == 4:
        val = fdp.ConsumeFloatInRange(-10.0, 10.0)
        t = torch.full(shape, val, dtype=dtype)
    else:
        vals = []
        for _ in range(n):
            vals.append(fdp.PickValueInList([-1.0, 0.0, 1.0, 2.0, -2.0, 0.5]))
        t = torch.tensor(vals, dtype=dtype).reshape(shape)
    if requires_grad and t.is_floating_point():
        t.requires_grad_(True)
    return t


def _make_v_like_output(fdp, output):
    if isinstance(output, tuple):
        return tuple(_make_v_like_output(fdp, o) for o in output)
    if not isinstance(output, torch.Tensor):
        return None
    return _make_tensor(fdp, tuple(output.shape), output.dtype, requires_grad=False)


def _build_func(fdp, variant):
    if variant == 0:
        def func(x):
            return x
        return func, 1, False

    if variant == 1:
        def func(x):
            return x * 2.0 + torch.sin(x)
        return func, 1, False

    if variant == 2:
        reduce_dim = fdp.ConsumeIntInRange(0, 4)

        def func(x):
            dim = reduce_dim % x.dim()
            return torch.exp(x).sum(dim=dim)
        return func, 1, False

    if variant == 3:
        reduce_dim = fdp.ConsumeIntInRange(0, 4)
        keepdim = fdp.ConsumeBool()

        def func(x):
            dim = reduce_dim % x.dim()
            return x.tanh().mean(dim=dim, keepdim=keepdim)
        return func, 1, False

    if variant == 4:
        transpose_ok = fdp.ConsumeBool()

        def func(x):
            y = x.relu()
            if transpose_ok and x.dim() >= 2:
                perm = list(range(x.dim()))
                perm[0], perm[-1] = perm[-1], perm[0]
                y = y.permute(perm)
            return y * y
        return func, 1, False

    if variant == 5:
        out_kind = fdp.ConsumeIntInRange(0, 2)

        def func(x):
            a = x.sin()
            b = x.cos()
            if out_kind == 0:
                return (a, b)
            if out_kind == 1:
                return (a.sum(), b.sum())
            return (a.sum(dim=0), b.mean(dim=0))
        return func, 1, False

    if variant == 6:
        dependent_y = fdp.ConsumeBool()

        def func(x, y):
            if dependent_y:
                return 2.0 * x + 3.0 * y
            return 2.0 * x
        return func, 2, True

    if variant == 7:
        def func(x, y):
            return (x * y).sum()
        return func, 2, True

    if variant == 8:
        dim_choice = fdp.ConsumeIntInRange(0, 3)

        def func(x, y):
            z = x + y
            dim = dim_choice % z.dim()
            return (z * z).sum(dim=dim)
        return func, 2, True

    def func(x):
        return (x.sigmoid().sum(), x.square())
    return func, 1, False


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_float_dtype(fdp)
        create_graph = fdp.ConsumeBool()
        strict = fdp.ConsumeBool()

        variant = fdp.ConsumeIntInRange(0, 9)
        func, n_inputs, needs_same_shape = _build_func(fdp, variant)

        if n_inputs == 1:
            rank = fdp.ConsumeIntInRange(1, 5)
            shape = _shape_for_rank(fdp, rank)
            x = _make_tensor(fdp, shape, dtype, requires_grad=True)
            inputs = x if fdp.ConsumeBool() else (x,)
            call_inputs = x
        else:
            rank = fdp.ConsumeIntInRange(1, 5)
            shape1 = _shape_for_rank(fdp, rank)
            shape2 = shape1 if needs_same_shape or fdp.ConsumeBool() else _shape_for_rank(fdp, rank)
            x = _make_tensor(fdp, shape1, dtype, requires_grad=True)
            y = _make_tensor(fdp, shape2, dtype, requires_grad=True)
            inputs = (x, y)
            call_inputs = (x, y)

        precompute_output = fdp.ConsumeBool()
        provide_v = fdp.ConsumeBool()
        v = None

        if precompute_output:
            out = func(*call_inputs) if isinstance(call_inputs, tuple) else func(call_inputs)
            if provide_v:
                v = _make_v_like_output(fdp, out)
        else:
            if n_inputs == 1 and fdp.ConsumeBool():
                if x.numel() == 1:
                    v = None
                else:
                    if provide_v:
                        v = _make_tensor(fdp, tuple(x.shape), dtype, requires_grad=False)
            elif n_inputs == 1 and provide_v:
                if fdp.ConsumeBool():
                    v = _make_tensor(fdp, tuple(x.shape), dtype, requires_grad=False)

        if fdp.ConsumeBool():
            output, vjp_res = torch.autograd.functional.vjp(
                func=func,
                inputs=inputs,
                v=v,
                create_graph=create_graph,
                strict=strict,
            )
        else:
            output, vjp_res = torch.autograd.functional.vjp(
                func,
                inputs,
                v,
                create_graph,
                strict,
            )

        if isinstance(output, torch.Tensor):
            _ = output.numel()
        elif isinstance(output, tuple):
            for o in output:
                if isinstance(o, torch.Tensor):
                    _ = o.numel()

        if isinstance(vjp_res, torch.Tensor):
            _ = vjp_res.numel()
        elif isinstance(vjp_res, tuple):
            for r in vjp_res:
                if isinstance(r, torch.Tensor):
                    _ = r.numel()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
