# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.utils.checkpoint.checkpoint_sequential
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.utils.checkpoint.checkpoint_sequential.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn as nn
from torch.utils.checkpoint import checkpoint_sequential


def _pick_dtype(fdp: atheris.FuzzedDataProvider):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
    ])


def _shape_for_rank(fdp: atheris.FuzzedDataProvider, rank: int):
    if rank == 2:
        return (
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 16),
        )
    if rank == 3:
        return (
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 16),
            fdp.ConsumeIntInRange(1, 16),
        )
    if rank == 4:
        return (
            fdp.ConsumeIntInRange(1, 4),
            fdp.ConsumeIntInRange(1, 16),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        )
    return (
        fdp.ConsumeIntInRange(1, 3),
        fdp.ConsumeIntInRange(1, 8),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
    )


def _make_tensor(fdp: atheris.FuzzedDataProvider, shape, dtype):
    numel = 1
    for s in shape:
        numel *= s
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        t = torch.randn(shape, dtype=torch.float32)
    elif mode == 1:
        vals = fdp.ConsumeFloatListInRange(numel, -8.0, 8.0)
        t = torch.tensor(vals, dtype=torch.float32).reshape(shape)
    elif mode == 2:
        t = torch.zeros(shape, dtype=torch.float32)
    elif mode == 3:
        t = torch.ones(shape, dtype=torch.float32)
    else:
        vals = [float(v) for v in fdp.ConsumeIntListInRange(numel, -4, 4)]
        t = torch.tensor(vals, dtype=torch.float32).reshape(shape)
    return t.to(dtype=dtype)


def _act_module(fdp: atheris.FuzzedDataProvider):
    choice = fdp.ConsumeIntInRange(0, 7)
    if choice == 0:
        return nn.ReLU()
    if choice == 1:
        return nn.Tanh()
    if choice == 2:
        return nn.Sigmoid()
    if choice == 3:
        return nn.Identity()
    if choice == 4:
        return nn.LeakyReLU(negative_slope=fdp.ConsumeFloatInRange(0.0, 1.0))
    if choice == 5:
        return nn.ELU(alpha=fdp.ConsumeFloatInRange(0.0, 2.0))
    if choice == 6:
        return nn.Hardswish()
    return nn.Softplus(beta=fdp.ConsumeFloatInRange(0.5, 3.0), threshold=fdp.ConsumeFloatInRange(1.0, 20.0))


def _norm_module(rank: int, channels: int):
    if rank == 2:
        return nn.LayerNorm(channels)
    if rank == 3:
        return nn.BatchNorm1d(channels)
    if rank == 4:
        return nn.BatchNorm2d(channels)
    return nn.BatchNorm3d(channels)


def _dropout_module(rank: int, p: float):
    if rank == 2:
        return nn.Dropout(p=p)
    if rank == 3:
        return nn.Dropout1d(p=p)
    if rank == 4:
        return nn.Dropout2d(p=p)
    return nn.Dropout3d(p=p)


def _conv_module(fdp: atheris.FuzzedDataProvider, rank: int, channels: int):
    out_channels = fdp.ConsumeIntInRange(1, 16)
    if rank == 3:
        k = fdp.ConsumeIntInRange(1, 3)
        return nn.Conv1d(channels, out_channels, kernel_size=k, padding=k // 2)
    if rank == 4:
        k = fdp.ConsumeIntInRange(1, 3)
        return nn.Conv2d(channels, out_channels, kernel_size=k, padding=k // 2)
    if rank == 5:
        k = fdp.ConsumeIntInRange(1, 3)
        return nn.Conv3d(channels, out_channels, kernel_size=k, padding=k // 2)
    return None


def _linear_module(fdp: atheris.FuzzedDataProvider, channels: int):
    out_features = fdp.ConsumeIntInRange(1, 32)
    return nn.Linear(channels, out_features)


def _build_functions(fdp: atheris.FuzzedDataProvider, rank: int, channels: int):
    modules = []
    current_c = channels
    count = fdp.ConsumeIntInRange(1, 8)
    for _ in range(count):
        kind = fdp.ConsumeIntInRange(0, 4)
        if kind == 0:
            m = _act_module(fdp)
        elif kind == 1:
            m = _norm_module(rank, current_c)
        elif kind == 2:
            p = fdp.ConsumeFloatInRange(0.0, 0.8)
            m = _dropout_module(rank, p)
        elif kind == 3 and rank >= 3:
            conv = _conv_module(fdp, rank, current_c)
            if conv is None:
                m = _act_module(fdp)
            else:
                m = conv
                current_c = conv.out_channels
        else:
            m = _linear_module(fdp, current_c)
            current_c = m.out_features
        modules.append(m)
    return modules


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        rank = fdp.PickValueInList([2, 3, 4, 5])
        shape = _shape_for_rank(fdp, rank)
        dtype = _pick_dtype(fdp)
        inp = _make_tensor(fdp, shape, dtype)

        if fdp.ConsumeBool():
            inp.requires_grad_(True)

        functions = _build_functions(fdp, rank, shape[1])

        if fdp.ConsumeBool():
            fn_container = nn.Sequential(*functions)
        else:
            fn_container = functions

        for m in functions:
            if isinstance(m, nn.Module):
                try:
                    m.to(dtype=dtype)
                except Exception:
                    pass
                if fdp.ConsumeBool():
                    m.train()
                else:
                    m.eval()

        max_segments = max(1, len(functions) + 2)
        segments = fdp.ConsumeIntInRange(1, max_segments)
        use_reentrant = fdp.ConsumeBool()
        preserve_rng_state = fdp.ConsumeBool()

        call_style = fdp.ConsumeIntInRange(0, 2)
        if call_style == 0:
            out = checkpoint_sequential(
                fn_container,
                segments,
                inp,
                use_reentrant=use_reentrant,
            )
        elif call_style == 1:
            out = checkpoint_sequential(
                fn_container,
                segments,
                inp,
                use_reentrant=use_reentrant,
                preserve_rng_state=preserve_rng_state,
            )
        else:
            out = checkpoint_sequential(
                functions=fn_container,
                segments=segments,
                input=inp,
                use_reentrant=use_reentrant,
                preserve_rng_state=preserve_rng_state,
            )

        if isinstance(out, torch.Tensor):
            if out.numel() > 0 and out.dtype.is_floating_point:
                loss_mode = fdp.ConsumeIntInRange(0, 2)
                if loss_mode == 0:
                    loss = out.sum()
                elif loss_mode == 1:
                    loss = out.mean()
                else:
                    loss = (out * out).sum()
                if loss.requires_grad:
                    loss.backward()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
