# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.add
# source_yaml_count=16
# source_api_txt=/root/api_txt/torch.add.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


FLOAT_DTYPES = [torch.float32, torch.float64]
INT_DTYPES = [torch.int8, torch.int16, torch.int32, torch.int64, torch.uint8]
COMPLEX_DTYPES = [torch.complex64, torch.complex128]
ALL_TENSOR_DTYPES = FLOAT_DTYPES + INT_DTYPES + COMPLEX_DTYPES + [torch.bool]


def _consume_small_dim(fdp, allow_zero=False):
    choices = [0, 1, 2, 3, 4, 5, 8]
    if not allow_zero:
        choices = [x for x in choices if x != 0]
    return fdp.PickValueInList(choices)


def _consume_rank(fdp, min_rank=0, max_rank=5):
    max_rank = max(min_rank, max_rank)
    return fdp.ConsumeIntInRange(min_rank, max_rank)


def _consume_shape(fdp, rank, allow_zero=False):
    return tuple(_consume_small_dim(fdp, allow_zero=allow_zero) for _ in range(rank))


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _consume_scalar_number(fdp):
    mode = fdp.ConsumeIntInRange(0, 6)
    if mode == 0:
        return fdp.ConsumeIntInRange(-8, 8)
    if mode == 1:
        return fdp.ConsumeFloatInRange(-8.0, 8.0)
    if mode == 2:
        return complex(fdp.ConsumeFloatInRange(-4.0, 4.0), fdp.ConsumeFloatInRange(-4.0, 4.0))
    if mode == 3:
        return bool(fdp.ConsumeBool())
    if mode == 4:
        return 0
    if mode == 5:
        return 1
    return -1


def _consume_alpha(fdp):
    common = [-3, -2, -1, 0, 1, 2, 3]
    if fdp.ConsumeBool():
        return fdp.PickValueInList(common)
    if fdp.ConsumeBool():
        return fdp.ConsumeFloatInRange(-4.0, 4.0)
    return _consume_scalar_number(fdp)


def _safe_float_list(fdp, count):
    vals = []
    for _ in range(count):
        if fdp.ConsumeBool():
            vals.append(fdp.PickValueInList([-1.0, 0.0, 1.0, 2.0, -2.0, 0.5, -0.5]))
        else:
            vals.append(fdp.ConsumeFloatInRange(-10.0, 10.0))
    return vals


def _safe_int_list(fdp, count, low=-8, high=8):
    vals = []
    for _ in range(count):
        if fdp.ConsumeBool():
            vals.append(fdp.PickValueInList([low, -1, 0, 1, high]))
        else:
            vals.append(fdp.ConsumeIntInRange(low, high))
    return vals


def _make_tensor_from_shape_dtype(fdp, shape, dtype):
    n = _numel(shape)
    if dtype in FLOAT_DTYPES:
        data = _safe_float_list(fdp, n)
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if dtype in INT_DTYPES:
        low = 0 if dtype == torch.uint8 else -8
        data = _safe_int_list(fdp, n, low=low, high=8)
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if dtype in COMPLEX_DTYPES:
        real = _safe_float_list(fdp, n)
        imag = _safe_float_list(fdp, n)
        data = [complex(r, i) for r, i in zip(real, imag)]
        return torch.tensor(data, dtype=dtype).reshape(shape)
    if dtype == torch.bool:
        data = [fdp.ConsumeBool() for _ in range(n)]
        return torch.tensor(data, dtype=dtype).reshape(shape)
    data = _safe_float_list(fdp, n)
    return torch.tensor(data, dtype=torch.float32).reshape(shape)


def _broadcast_shape(base_shape, fdp):
    if len(base_shape) == 0:
        if fdp.ConsumeBool():
            return ()
        return (1,)
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return base_shape
    if mode == 1:
        return tuple(1 if fdp.ConsumeBool() else d for d in base_shape)
    if mode == 2:
        k = fdp.ConsumeIntInRange(0, len(base_shape))
        suffix = base_shape[len(base_shape) - k :]
        return tuple(1 if fdp.ConsumeBool() else d for d in suffix)
    if mode == 3:
        extra = fdp.ConsumeIntInRange(1, 2)
        prefix = tuple(1 for _ in range(extra))
        return prefix + tuple(1 if fdp.ConsumeBool() else d for d in base_shape)
    return ()


def _pick_dtype_for_tensor_add(fdp):
    return fdp.PickValueInList(ALL_TENSOR_DTYPES)


def _compatible_out_dtype(a, b):
    return torch.result_type(a, b)


def _call_scalar_overloads(fdp):
    mode = fdp.ConsumeIntInRange(0, 8)
    if mode == 0:
        a = fdp.ConsumeIntInRange(-8, 8)
        b = fdp.ConsumeIntInRange(-8, 8)
        torch.add(a, b)
    elif mode == 1:
        a = fdp.ConsumeFloatInRange(-8.0, 8.0)
        b = fdp.ConsumeFloatInRange(-8.0, 8.0)
        torch.add(a, b)
    elif mode == 2:
        a = complex(fdp.ConsumeFloatInRange(-4.0, 4.0), fdp.ConsumeFloatInRange(-4.0, 4.0))
        b = complex(fdp.ConsumeFloatInRange(-4.0, 4.0), fdp.ConsumeFloatInRange(-4.0, 4.0))
        torch.add(a, b)
    elif mode == 3:
        a = fdp.ConsumeIntInRange(-8, 8)
        b = fdp.ConsumeFloatInRange(-8.0, 8.0)
        torch.add(a, b)
    elif mode == 4:
        a = fdp.ConsumeFloatInRange(-8.0, 8.0)
        b = fdp.ConsumeIntInRange(-8, 8)
        torch.add(a, b)
    elif mode == 5:
        a = complex(fdp.ConsumeFloatInRange(-4.0, 4.0), fdp.ConsumeFloatInRange(-4.0, 4.0))
        b = fdp.ConsumeFloatInRange(-8.0, 8.0)
        torch.add(a, b)
    elif mode == 6:
        a = fdp.ConsumeFloatInRange(-8.0, 8.0)
        b = complex(fdp.ConsumeFloatInRange(-4.0, 4.0), fdp.ConsumeFloatInRange(-4.0, 4.0))
        torch.add(a, b)
    elif mode == 7:
        a = fdp.ConsumeIntInRange(-8, 8)
        b = complex(fdp.ConsumeFloatInRange(-4.0, 4.0), fdp.ConsumeFloatInRange(-4.0, 4.0))
        torch.add(a, b)
    else:
        a = fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 8))
        b = fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 8))
        torch.add(a, b)


def _call_tensor_scalar_add(fdp):
    rank = _consume_rank(fdp, 1, 5)
    shape = _consume_shape(fdp, rank, allow_zero=True)
    dtype = fdp.PickValueInList(FLOAT_DTYPES + INT_DTYPES + COMPLEX_DTYPES)
    self_tensor = _make_tensor_from_shape_dtype(fdp, shape, dtype)
    other = _consume_scalar_number(fdp)
    alpha = _consume_alpha(fdp)

    if fdp.ConsumeBool():
        torch.add(self_tensor, other)
    elif fdp.ConsumeBool():
        torch.add(self_tensor, other, alpha=alpha)
    else:
        out_dtype = _compatible_out_dtype(self_tensor, other)
        out = torch.empty_like(self_tensor, dtype=out_dtype)
        if fdp.ConsumeBool():
            torch.add(self_tensor, other, alpha=alpha, out=out)
        else:
            torch.add(self_tensor, other, out=out)


def _call_tensor_tensor_add(fdp):
    rank = _consume_rank(fdp, 0, 5)
    self_shape = _consume_shape(fdp, rank, allow_zero=True)
    other_shape = _broadcast_shape(self_shape, fdp)

    self_dtype = _pick_dtype_for_tensor_add(fdp)
    if fdp.ConsumeBool():
        other_dtype = self_dtype
    else:
        other_dtype = _pick_dtype_for_tensor_add(fdp)

    self_tensor = _make_tensor_from_shape_dtype(fdp, self_shape, self_dtype)
    other_tensor = _make_tensor_from_shape_dtype(fdp, other_shape, other_dtype)

    alpha = _consume_alpha(fdp)

    if fdp.ConsumeBool():
        result = torch.add(self_tensor, other_tensor)
    elif fdp.ConsumeBool():
        result = torch.add(self_tensor, other_tensor, alpha=alpha)
    else:
        bshape = torch.broadcast_shapes(tuple(self_tensor.shape), tuple(other_tensor.shape))
        out_dtype = _compatible_out_dtype(self_tensor, other_tensor)
        out = torch.empty(bshape, dtype=out_dtype)
        if fdp.ConsumeBool():
            result = torch.add(self_tensor, other_tensor, out=out)
        else:
            result = torch.add(self_tensor, other_tensor, alpha=alpha, out=out)

    if fdp.ConsumeBool():
        _ = result.shape
    if fdp.ConsumeBool() and result.numel() > 0:
        _ = result.flatten()[0].item()


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        mode = fdp.ConsumeIntInRange(0, 2)
        if mode == 0:
            _call_tensor_tensor_add(fdp)
        elif mode == 1:
            _call_tensor_scalar_add(fdp)
        else:
            _call_scalar_overloads(fdp)
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
