# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.hann_window
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.hann_window.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    dtypes = [
        None,
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
    ]
    return fdp.PickValueInList(dtypes)


def _pick_layout(fdp):
    # Only torch.strided is supported by docs; include None/default path too.
    return fdp.PickValueInList([None, torch.strided])


def _pick_device(fdp):
    devices = [None, torch.device("cpu"), "cpu"]
    if torch.cuda.is_available():
        devices.extend([torch.device("cuda"), "cuda"])
    return fdp.PickValueInList(devices)


def _window_length(fdp):
    # YAML suggests [-1, 8], docs require positive integer.
    # Bias toward valid but still include invalid/boundary cases.
    if fdp.ConsumeBool():
        return fdp.ConsumeIntInRange(1, 8)
    return fdp.ConsumeIntInRange(-1, 8)


def _make_out_tensor(fdp, length, device):
    dtype = fdp.PickValueInList([torch.float32, torch.float64])
    actual_len = length
    if fdp.ConsumeBool():
        actual_len = length
    else:
        actual_len = fdp.ConsumeIntInRange(0, 10)

    if actual_len < 0:
        actual_len = 0

    if device is None:
        device = "cpu"
    elif isinstance(device, torch.device):
        device = device.type
    elif isinstance(device, str):
        device = device
    else:
        device = "cpu"

    if device == "cuda" and not torch.cuda.is_available():
        device = "cpu"

    base = torch.empty((actual_len,), dtype=dtype, device=device)
    if actual_len > 0:
        mode = fdp.ConsumeIntInRange(0, 2)
        if mode == 0:
            base.zero_()
        elif mode == 1:
            base.fill_(fdp.ConsumeFloatInRange(-2.0, 2.0))
        else:
            vals = fdp.ConsumeFloatListInRange(actual_len, -4.0, 4.0)
            base.copy_(torch.tensor(vals, dtype=dtype, device=device))
    return base


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        call_mode = fdp.ConsumeIntInRange(0, 3)
        length = _window_length(fdp)

        if call_mode == 0:
            kwargs = {}
            dtype = _pick_dtype(fdp)
            layout = _pick_layout(fdp)
            device = _pick_device(fdp)
            requires_grad = fdp.ConsumeBool()

            if dtype is not None:
                kwargs["dtype"] = dtype
            if layout is not None:
                kwargs["layout"] = layout
            if device is not None:
                kwargs["device"] = device
            if fdp.ConsumeBool():
                kwargs["requires_grad"] = requires_grad

            result = torch.hann_window(length, **kwargs)
            if result.numel() > 0 and fdp.ConsumeBool():
                _ = result.sum()

        elif call_mode == 1:
            periodic = fdp.ConsumeBool()
            kwargs = {}
            dtype = _pick_dtype(fdp)
            layout = _pick_layout(fdp)
            device = _pick_device(fdp)
            requires_grad = fdp.ConsumeBool()

            if dtype is not None:
                kwargs["dtype"] = dtype
            if layout is not None:
                kwargs["layout"] = layout
            if device is not None:
                kwargs["device"] = device
            if fdp.ConsumeBool():
                kwargs["requires_grad"] = requires_grad

            result = torch.hann_window(length, periodic, **kwargs)
            if result.numel() > 0 and fdp.ConsumeBool():
                _ = result.mean()

        elif call_mode == 2:
            device = _pick_device(fdp)
            out = _make_out_tensor(fdp, length, device)
            result = torch.hann_window(length, out=out)
            if result.numel() > 0 and fdp.ConsumeBool():
                _ = result[-1]

        else:
            periodic = fdp.ConsumeBool()
            device = _pick_device(fdp)
            out = _make_out_tensor(fdp, length, device)
            result = torch.hann_window(length, periodic, out=out)
            if result.numel() > 0 and fdp.ConsumeBool():
                _ = result[0]

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
