# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.argmax
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.argmax.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 3)
    shape = []
    for _ in range(rank):
        shape.append(fdp.ConsumeIntInRange(0, 6))
    return tuple(shape)


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor_from_shape(fdp, shape, dtype):
    total = _numel(shape)
    if total == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 1:
        vals = [float(x) for x in fdp.ConsumeIntListInRange(total, -16, 16)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 2:
        base = torch.zeros(shape, dtype=dtype)
        if total > 0:
            flat = base.reshape(-1)
            idx = fdp.ConsumeIntInRange(0, total - 1)
            flat[idx] = fdp.ConsumeFloatInRange(-1000.0, 1000.0)
        return base
    if mode == 3:
        vals = [fdp.ConsumeFloatInRange(-1e6, 1e6) for _ in range(total)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = []
    for _ in range(total):
        choice = fdp.ConsumeIntInRange(0, 6)
        if choice == 0:
            vals.append(float("nan"))
        elif choice == 1:
            vals.append(float("inf"))
        elif choice == 2:
            vals.append(float("-inf"))
        else:
            vals.append(fdp.ConsumeRegularFloat())
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _choose_dim(fdp, ndim):
    if fdp.ConsumeBool():
        return None
    if ndim == 0:
        return fdp.PickValueInList([0, -1])
    return fdp.ConsumeIntInRange(-ndim, ndim - 1)


def _expected_out_shape(shape, dim, keepdim):
    if dim is None:
        return tuple()
    ndim = len(shape)
    if ndim == 0:
        return tuple()
    dim = dim % ndim
    if keepdim:
        out = list(shape)
        out[dim] = 1
        return tuple(out)
    return tuple(shape[i] for i in range(ndim) if i != dim)


def _make_out_tensor(fdp, out_shape):
    out_mode = fdp.ConsumeIntInRange(0, 3)
    if out_mode == 0:
        return torch.empty(out_shape, dtype=torch.int64)
    if out_mode == 1:
        total = _numel(out_shape)
        if total == 0:
            return torch.empty(out_shape, dtype=torch.int64)
        vals = fdp.ConsumeIntListInRange(total, -8, 8)
        return torch.tensor(vals, dtype=torch.int64).reshape(out_shape)
    if out_mode == 2:
        wrong_dtype = fdp.PickValueInList([torch.float32, torch.float64, torch.int32])
        return torch.empty(out_shape, dtype=wrong_dtype)

    altered = list(out_shape)
    if len(altered) == 0:
        altered = [fdp.ConsumeIntInRange(0, 2)]
    else:
        idx = fdp.ConsumeIntInRange(0, len(altered) - 1)
        altered[idx] = fdp.ConsumeIntInRange(0, 6)
    return torch.empty(tuple(altered), dtype=torch.int64)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)
        shape = _consume_shape(fdp)
        x = _make_tensor_from_shape(fdp, shape, dtype)

        dim = _choose_dim(fdp, x.ndim)
        keepdim = fdp.ConsumeBool()

        call_mode = fdp.ConsumeIntInRange(0, 5)

        if call_mode == 0:
            torch.argmax(x)
        elif call_mode == 1:
            torch.argmax(x, dim=dim, keepdim=keepdim)
        elif call_mode == 2:
            if dim is None:
                torch.argmax(x, dim=dim)
            else:
                torch.argmax(x, dim=dim)
        elif call_mode == 3:
            if dim is None:
                torch.argmax(input=x)
            else:
                torch.argmax(input=x, dim=dim, keepdim=keepdim)
        else:
            out_shape = _expected_out_shape(tuple(x.shape), dim, keepdim)
            out = _make_out_tensor(fdp, out_shape)
            if call_mode == 4:
                torch.argmax(x, dim=dim, keepdim=keepdim, out=out)
            else:
                if dim is None:
                    torch.argmax(input=x, out=out)
                else:
                    torch.argmax(input=x, dim=dim, keepdim=keepdim, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
