# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.polygamma
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.polygamma.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys

import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_shape(fdp, allow_scalar):
    if allow_scalar:
        rank = fdp.ConsumeIntInRange(0, 5)
    else:
        rank = fdp.ConsumeIntInRange(1, 5)

    dims = []
    for _ in range(rank):
        if fdp.ConsumeBool():
            dims.append(fdp.PickValueInList([0, 1, 2, 3, 4, 8]))
        else:
            dims.append(fdp.ConsumeIntInRange(0, 8))
    return tuple(dims)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_tensor(fdp, shape, dtype):
    count = _numel(shape)
    if count == 0:
        return torch.empty(shape, dtype=dtype)

    mode = fdp.ConsumeIntInRange(0, 5)
    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(count)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 1:
        vals = fdp.ConsumeFloatListInRange(count, -10.0, 10.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 2:
        vals = []
        for _ in range(count):
            vals.append(fdp.PickValueInList([0.0, -0.0, 1.0, -1.0, 2.0, 0.5, -0.5, 10.0, -10.0]))
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 3:
        t = torch.empty(shape, dtype=dtype)
        t.uniform_(fdp.ConsumeFloatInRange(-5.0, 0.0), fdp.ConsumeFloatInRange(0.0, 5.0) + 1e-6)
        return t
    if mode == 4:
        vals = []
        for _ in range(count):
            vals.append(fdp.ConsumeFloat())
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    base = torch.arange(count, dtype=dtype).reshape(shape)
    shift = fdp.ConsumeFloatInRange(-3.0, 3.0)
    scale = fdp.ConsumeFloatInRange(-2.0, 2.0)
    return base * scale + shift


def _make_out_tensor(fdp, ref):
    out_dtype = ref.dtype if fdp.ConsumeBool() else _pick_dtype(fdp)
    shape = tuple(ref.shape)
    if ref.numel() == 0:
        if fdp.ConsumeBool():
            return torch.empty(shape, dtype=out_dtype)
        return torch.zeros(shape, dtype=out_dtype)

    if fdp.ConsumeBool():
        vals = fdp.ConsumeFloatListInRange(ref.numel(), -5.0, 5.0)
        return torch.tensor(vals, dtype=out_dtype).reshape(shape)
    return torch.empty(shape, dtype=out_dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        n = fdp.ConsumeIntInRange(-1, 8)
        use_out = fdp.ConsumeBool()

        if use_out:
            # YAML suggests scalar-only for out overload, but API supports general tensors.
            # Prefer executable broader coverage while still sometimes exercising scalars.
            scalar_bias = fdp.ConsumeBool()
            self_shape = () if scalar_bias else _consume_shape(fdp, allow_scalar=True)
        else:
            # YAML emphasizes non-scalar ranks for default overload.
            self_shape = _consume_shape(fdp, allow_scalar=False)

        self_dtype = _pick_dtype(fdp)
        inp = _make_tensor(fdp, self_shape, self_dtype)

        if use_out:
            out = _make_out_tensor(fdp, inp)
            if fdp.ConsumeBool():
                torch.polygamma(n, inp, out=out)
            else:
                torch.polygamma(n=n, input=inp, out=out)
        else:
            call_mode = fdp.ConsumeIntInRange(0, 2)
            if call_mode == 0:
                torch.polygamma(n, inp)
            elif call_mode == 1:
                torch.polygamma(n=n, input=inp)
            else:
                res = torch.polygamma(n, inp)
                if fdp.ConsumeBool() and res.numel() > 0:
                    _ = res.reshape(-1)[0].item()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
