# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.bernoulli
# source_yaml_count=6
# source_api_txt=/root/api_txt/torch.bernoulli.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


FLOAT_DTYPES = [torch.float32, torch.float64]
OUT_DTYPES = [torch.float32, torch.float64, torch.int8, torch.int16, torch.int32, torch.int64, torch.uint8, torch.bool]


def _consume_shape(fdp, min_rank=1, max_rank=5):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    dims = []
    for _ in range(rank):
        dims.append(fdp.PickValueInList([0, 1, 2, 3, 4, 8, 16]))
    return tuple(dims)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_prob_tensor(fdp, shape, dtype):
    total = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 7)

    if total == 0:
        return torch.empty(shape, dtype=dtype)

    if mode == 0:
        return torch.zeros(shape, dtype=dtype)
    if mode == 1:
        return torch.ones(shape, dtype=dtype)
    if mode == 2:
        val = fdp.PickValueInList([0.0, 1.0, 0.5, 0.25, 0.75])
        return torch.full(shape, val, dtype=dtype)
    if mode == 3:
        vals = fdp.ConsumeProbabilityList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 4:
        vals = [fdp.PickValueInList([0.0, 1.0, 0.5, 1e-7, 1.0 - 1e-7]) for _ in range(total)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 5:
        base = torch.linspace(0.0, 1.0, steps=total, dtype=dtype)
        return base.reshape(shape)
    if mode == 6:
        vals = []
        for _ in range(total):
            bucket = fdp.ConsumeIntInRange(0, 4)
            if bucket == 0:
                vals.append(0.0)
            elif bucket == 1:
                vals.append(1.0)
            elif bucket == 2:
                vals.append(0.5)
            elif bucket == 3:
                vals.append(fdp.ConsumeFloatInRange(0.0, 1.0))
            else:
                vals.append(fdp.ConsumeProbability())
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    t = torch.empty(shape, dtype=dtype)
    t.uniform_(0.0, 1.0)
    return t


def _make_out_tensor(fdp, shape):
    dtype = fdp.PickValueInList(OUT_DTYPES)
    mode = fdp.ConsumeIntInRange(0, 2)
    if mode == 0:
        return torch.empty(shape, dtype=dtype)
    if mode == 1:
        return torch.zeros(shape, dtype=dtype)
    return torch.ones(shape, dtype=dtype)


def _maybe_generator(fdp):
    if not fdp.ConsumeBool():
        return None
    g = torch.Generator()
    g.manual_seed(fdp.ConsumeUInt(8))
    return g


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        branch = fdp.ConsumeIntInRange(0, 5)

        if branch == 0:
            shape = _consume_shape(fdp, 1, 5)
            dtype = fdp.PickValueInList(FLOAT_DTYPES)
            self_tensor = _make_prob_tensor(fdp, shape, dtype)
            generator = _maybe_generator(fdp)
            if generator is None:
                torch.bernoulli(self_tensor)
            else:
                torch.bernoulli(self_tensor, generator=generator)

        elif branch == 1:
            shape = _consume_shape(fdp, 1, 5)
            dtype = fdp.PickValueInList(FLOAT_DTYPES)
            self_tensor = _make_prob_tensor(fdp, shape, dtype)
            p = fdp.PickValueInList([0.0, 1.0, 0.5, 0.25, 0.75, fdp.ConsumeProbability()])
            generator = _maybe_generator(fdp)
            if generator is None:
                torch.bernoulli(self_tensor, p)
            else:
                torch.bernoulli(self_tensor, p, generator=generator)

        elif branch == 2:
            shape = _consume_shape(fdp, 1, 5)
            dtype = fdp.PickValueInList(FLOAT_DTYPES)
            self_tensor = _make_prob_tensor(fdp, shape, dtype)
            p_tensor = _make_prob_tensor(fdp, shape, dtype)
            generator = _maybe_generator(fdp)
            if generator is None:
                torch.bernoulli(self_tensor, p_tensor)
            else:
                torch.bernoulli(self_tensor, p_tensor, generator=generator)

        elif branch == 3:
            shape = _consume_shape(fdp, 1, 5)
            dtype = fdp.PickValueInList(FLOAT_DTYPES)
            self_tensor = _make_prob_tensor(fdp, shape, dtype)
            out = _make_out_tensor(fdp, shape)
            generator = _maybe_generator(fdp)
            if generator is None:
                torch.bernoulli(self_tensor, out=out)
            else:
                torch.bernoulli(self_tensor, generator=generator, out=out)

        elif branch == 4:
            shape = _consume_shape(fdp, 1, 5)
            dtype = fdp.PickValueInList(FLOAT_DTYPES)
            self_tensor = _make_prob_tensor(fdp, shape, dtype)
            p = fdp.PickValueInList([0.0, 1.0, 0.5, 0.25, 0.75, fdp.ConsumeProbability()])
            out = _make_out_tensor(fdp, shape)
            generator = _maybe_generator(fdp)
            if generator is None:
                torch.bernoulli(self_tensor, p, out=out)
            else:
                torch.bernoulli(self_tensor, p, generator=generator, out=out)

        else:
            shape = _consume_shape(fdp, 1, 5)
            dtype = fdp.PickValueInList(FLOAT_DTYPES)
            self_tensor = _make_prob_tensor(fdp, shape, dtype)
            p_tensor = _make_prob_tensor(fdp, shape, dtype)
            out = _make_out_tensor(fdp, shape)
            generator = _maybe_generator(fdp)
            if generator is None:
                torch.bernoulli(self_tensor, p_tensor, out=out)
            else:
                torch.bernoulli(self_tensor, p_tensor, generator=generator, out=out)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
