# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.distributed.gather
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.distributed.gather.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys

import torch
import torch.distributed as dist


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64, torch.int32, torch.int64])


def _make_shape(fdp):
    rank = fdp.ConsumeIntInRange(0, 4)
    shape = []
    for _ in range(rank):
        shape.append(fdp.ConsumeIntInRange(0, 4))
    if not shape:
        if fdp.ConsumeBool():
            return ()
        return (fdp.ConsumeIntInRange(0, 8),)
    return tuple(shape)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_tensor(fdp, dtype, shape):
    n = _numel(shape)
    if dtype.is_floating_point:
        vals = []
        for _ in range(n):
            if fdp.ConsumeBool():
                vals.append(fdp.ConsumeFloatInRange(-10.0, 10.0))
            else:
                vals.append(float(fdp.ConsumeIntInRange(-10, 10)))
        if n == 0:
            return torch.empty(shape, dtype=dtype)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    vals = [fdp.ConsumeIntInRange(-10, 10) for _ in range(n)]
    if n == 0:
        return torch.empty(shape, dtype=dtype)
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _maybe_init_pg():
    if dist.is_available() and not dist.is_initialized():
        init_method = "file:///tmp/atheris_torch_distributed_gather_init"
        try:
            dist.init_process_group(
                backend="gloo",
                init_method=init_method,
                rank=0,
                world_size=1,
            )
        except Exception:
            pass


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        _maybe_init_pg()

        tensor_dtype = fdp.PickValueInList([torch.float32, torch.float64])
        shape = _make_shape(fdp)
        tensor = _make_tensor(fdp, tensor_dtype, shape)

        if dist.is_available() and dist.is_initialized():
            world_size = dist.get_world_size()
            rank = dist.get_rank()
        else:
            world_size = 1
            rank = 0

        async_op = fdp.ConsumeBool()
        use_group = fdp.ConsumeBool()
        group = dist.group.WORLD if (use_group and dist.is_available() and dist.is_initialized()) else None

        use_dst = fdp.ConsumeBool()
        use_group_dst = fdp.ConsumeBool()
        if use_dst and use_group_dst:
            if fdp.ConsumeBool():
                use_group_dst = False
            else:
                use_dst = False

        dst = 0 if use_dst else None
        group_dst = 0 if use_group_dst else None

        is_dest = False
        if group_dst is not None:
            is_dest = (rank == group_dst)
        elif dst is not None:
            is_dest = (rank == dst)
        else:
            is_dest = (rank == 0)

        gather_list = None
        if is_dest or fdp.ConsumeBool():
            gather_len = world_size if fdp.ConsumeBool() else fdp.ConsumeIntInRange(0, 3)
            gather_list = []
            for _ in range(gather_len):
                if fdp.ConsumeBool():
                    gather_list.append(torch.zeros_like(tensor))
                else:
                    gl_dtype = tensor_dtype if fdp.ConsumeBool() else _pick_dtype(fdp)
                    gl_shape = shape if fdp.ConsumeBool() else _make_shape(fdp)
                    gather_list.append(_make_tensor(fdp, gl_dtype, gl_shape))

        if fdp.ConsumeBool():
            dist.gather(
                tensor=tensor,
                gather_list=gather_list,
                dst=dst,
                group=group,
                async_op=async_op,
                group_dst=group_dst,
            )
        else:
            args = [tensor]
            if fdp.ConsumeBool():
                args.append(gather_list)
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["dst"] = dst
            if fdp.ConsumeBool():
                kwargs["group"] = group
            if fdp.ConsumeBool():
                kwargs["async_op"] = async_op
            if fdp.ConsumeBool():
                kwargs["group_dst"] = group_dst
            dist.gather(*args, **kwargs)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
