# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.prune.remove
# source_yaml_count=5
# source_api_txt=/root/api_txt/torch.nn.utils.prune.remove.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys

import torch
import torch.nn as nn
import torch.nn.utils.prune as prune


def _consume_name(fdp, module):
    candidates = []
    for n, _ in module.named_parameters(recurse=True):
        candidates.append(n)
    for n, _ in module.named_buffers(recurse=True):
        candidates.append(n)
    extra = [
        "",
        "weight",
        "bias",
        "weight_orig",
        "bias_orig",
        "weight_mask",
        "bias_mask",
        "0.weight",
        "0.bias",
        "1.weight",
        "1.bias",
        "foo",
        "bar",
    ]
    candidates.extend(extra)
    if fdp.ConsumeBool() and candidates:
        return fdp.PickValueInList(candidates)
    return fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 16))


def _small_shape(fdp, min_rank=1, max_rank=4, min_dim=1, max_dim=6):
    rank = fdp.ConsumeIntInRange(min_rank, max_rank)
    return tuple(fdp.ConsumeIntInRange(min_dim, max_dim) for _ in range(rank))


def _make_linear(fdp):
    in_features = fdp.ConsumeIntInRange(1, 16)
    out_features = fdp.ConsumeIntInRange(1, 16)
    bias = fdp.ConsumeBool()
    return nn.Linear(in_features, out_features, bias=bias)


def _make_conv2d(fdp):
    in_channels = fdp.ConsumeIntInRange(1, 8)
    out_channels = fdp.ConsumeIntInRange(1, 8)
    kernel_size = fdp.ConsumeIntInRange(1, 4)
    stride = fdp.ConsumeIntInRange(1, 2)
    padding = fdp.ConsumeIntInRange(0, 2)
    bias = fdp.ConsumeBool()
    return nn.Conv2d(
        in_channels=in_channels,
        out_channels=out_channels,
        kernel_size=kernel_size,
        stride=stride,
        padding=padding,
        bias=bias,
    )


def _make_batchnorm1d(fdp):
    num_features = fdp.ConsumeIntInRange(1, 16)
    affine = fdp.ConsumeBool()
    track_running_stats = fdp.ConsumeBool()
    return nn.BatchNorm1d(
        num_features=num_features,
        affine=affine,
        track_running_stats=track_running_stats,
    )


def _make_embedding(fdp):
    num_embeddings = fdp.ConsumeIntInRange(1, 32)
    embedding_dim = fdp.ConsumeIntInRange(1, 16)
    return nn.Embedding(num_embeddings, embedding_dim)


def _make_modulelist(fdp):
    layers = []
    count = fdp.ConsumeIntInRange(1, 3)
    last_out = None
    for i in range(count):
        if i == 0 or last_out is None or fdp.ConsumeBool():
            in_features = fdp.ConsumeIntInRange(1, 16) if last_out is None else last_out
        else:
            in_features = last_out
        out_features = fdp.ConsumeIntInRange(1, 16)
        layers.append(nn.Linear(in_features, out_features, bias=fdp.ConsumeBool()))
        last_out = out_features
    return nn.Sequential(*layers)


def _make_module(fdp):
    choice = fdp.ConsumeIntInRange(0, 5)
    if choice == 0:
        return _make_linear(fdp)
    if choice == 1:
        return _make_conv2d(fdp)
    if choice == 2:
        return _make_batchnorm1d(fdp)
    if choice == 3:
        return _make_embedding(fdp)
    if choice == 4:
        return _make_modulelist(fdp)
    return nn.Sequential(
        _make_linear(fdp),
        nn.ReLU(),
        _make_linear(fdp),
    )


def _apply_pruning_if_possible(fdp, module):
    param_names = [n for n, _ in module.named_parameters(recurse=True)]
    if not param_names:
        return
    target = fdp.PickValueInList(param_names)
    mode = fdp.ConsumeIntInRange(0, 4)
    amount_float = fdp.ConsumeFloatInRange(0.0, 1.0)
    amount_int = fdp.ConsumeIntInRange(0, 8)
    dim = fdp.ConsumeIntInRange(-2, 2)

    if mode == 0:
        prune.random_unstructured(module, name=target, amount=amount_float)
    elif mode == 1:
        prune.l1_unstructured(module, name=target, amount=amount_float)
    elif mode == 2:
        prune.random_structured(module, name=target, amount=amount_float, dim=dim)
    elif mode == 3:
        prune.ln_structured(module, name=target, amount=amount_float, n=fdp.ConsumeIntInRange(1, 3), dim=dim)
    else:
        prune.random_unstructured(module, name=target, amount=amount_int)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        module = _make_module(fdp)

        if fdp.ConsumeBool():
            module.train()
        else:
            module.eval()

        prune_rounds = fdp.ConsumeIntInRange(0, 3)
        for _ in range(prune_rounds):
            try:
                _apply_pruning_if_possible(fdp, module)
            except (
                RuntimeError,
                TypeError,
                ValueError,
                IndexError,
                AssertionError,
                NotImplementedError,
            ):
                pass
            except Exception:
                pass

        if fdp.ConsumeBool():
            name = _consume_name(fdp, module)
            prune.remove(module, name)
        else:
            kw_name = _consume_name(fdp, module)
            prune.remove(module=module, name=kw_name)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
