# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.clip_grad_value_
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.clip_grad_value_.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _make_shape(fdp):
    rank = fdp.ConsumeIntInRange(1, 5)
    if rank == 1:
        limits = [8]
    elif rank == 2:
        limits = [8, 64]
    elif rank == 3:
        limits = [8, 64, 128]
    elif rank == 4:
        limits = [8, 64, 128, 128]
    else:
        limits = [8, 64, 128, 128, 128]

    shape = []
    for lim in limits:
        shape.append(fdp.ConsumeIntInRange(1, lim))
    return tuple(shape)


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, dtype, shape):
    total = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 5)

    if mode == 0:
        vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 1:
        vals = fdp.ConsumeFloatListInRange(total, -1.0, 1.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 2:
        base = fdp.ConsumeFloatInRange(-5.0, 5.0)
        step = fdp.ConsumeFloatInRange(-2.0, 2.0)
        vals = [base + step * i for i in range(total)]
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 3:
        vals = [0.0] * total
        if total > 0:
            idx = fdp.ConsumeIntInRange(0, total - 1)
            vals[idx] = fdp.ConsumeFloatInRange(-100.0, 100.0)
        t = torch.tensor(vals, dtype=dtype)
    elif mode == 4:
        vals = []
        for _ in range(total):
            vals.append(float(fdp.PickValueInList([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0])))
        t = torch.tensor(vals, dtype=dtype)
    else:
        t = torch.empty(total, dtype=dtype)
        t.uniform_(fdp.ConsumeFloatInRange(-10.0, 0.0), fdp.ConsumeFloatInRange(0.0, 10.0))

    return t.reshape(shape)


def _attach_grad(fdp, param):
    grad_mode = fdp.ConsumeIntInRange(0, 5)
    if grad_mode == 0:
        param.grad = None
        return

    grad = _make_tensor(fdp, param.dtype, tuple(param.shape))

    if grad_mode == 1:
        param.grad = grad
    elif grad_mode == 2:
        param.grad = -grad
    elif grad_mode == 3:
        param.grad = grad.contiguous()
    elif grad_mode == 4:
        if grad.numel() > 0:
            grad = grad.clone()
            grad.view(-1)[0] = 0
        param.grad = grad
    else:
        param.grad = grad + fdp.ConsumeFloatInRange(-0.25, 0.25)


def _make_parameter(fdp):
    dtype = _pick_dtype(fdp)
    shape = _make_shape(fdp)
    data = _make_tensor(fdp, dtype, shape)
    requires_grad = fdp.ConsumeBool()
    p = torch.nn.Parameter(data, requires_grad=requires_grad)
    _attach_grad(fdp, p)
    return p


def _make_parameters_arg(fdp):
    as_single = fdp.ConsumeBool()
    count = fdp.ConsumeIntInRange(1, 4)

    if as_single:
        return _make_parameter(fdp)

    params = [_make_parameter(fdp) for _ in range(count)]
    container_kind = fdp.ConsumeIntInRange(0, 2)
    if container_kind == 0:
        return params
    elif container_kind == 1:
        return tuple(params)
    else:
        return iter(params)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        parameters = _make_parameters_arg(fdp)

        clip_mode = fdp.ConsumeIntInRange(0, 4)
        if clip_mode == 0:
            clip_value = fdp.ConsumeFloatInRange(-1.0, 1.0)
        elif clip_mode == 1:
            clip_value = fdp.PickValueInList([-1.0, -0.5, -0.0, 0.0, 0.5, 1.0])
        elif clip_mode == 2:
            clip_value = fdp.ConsumeFloatInRange(0.0, 10.0)
        elif clip_mode == 3:
            clip_value = fdp.ConsumeFloatInRange(-10.0, 0.0)
        else:
            clip_value = fdp.ConsumeRegularFloat()

        foreach_mode = fdp.ConsumeIntInRange(0, 2)
        if foreach_mode == 0:
            foreach = None
        elif foreach_mode == 1:
            foreach = True
        else:
            foreach = False

        call_mode = fdp.ConsumeIntInRange(0, 2)
        if call_mode == 0:
            torch.nn.utils.clip_grad_value_(parameters, clip_value)
        elif call_mode == 1:
            torch.nn.utils.clip_grad_value_(parameters, clip_value, foreach)
        else:
            torch.nn.utils.clip_grad_value_(
                parameters=parameters, clip_value=clip_value, foreach=foreach
            )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
