# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.cat
# source_yaml_count=4
# source_api_txt=/root/api_txt/torch.cat.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


DTYPES = [torch.float32, torch.float64]


def _pick_dtype(fdp):
    return fdp.PickValueInList(DTYPES)


def _shape_for_rank(fdp, rank):
    if rank == 1:
        limits = [8]
    elif rank == 2:
        limits = [8, 16]
    elif rank == 3:
        limits = [8, 16, 16]
    elif rank == 4:
        limits = [8, 16, 16, 16]
    else:
        limits = [8, 16, 16, 16, 16]
    return [fdp.ConsumeIntInRange(0, lim) for lim in limits]


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor_from_shape(fdp, shape, dtype):
    count = _numel(shape)
    values = fdp.ConsumeFloatListInRange(count, -100.0, 100.0)
    if len(values) < count:
        values = values + [0.0] * (count - len(values))
    t = torch.tensor(values, dtype=dtype)
    return t.reshape(shape)


def _make_named_tensor(t, fdp):
    rank = t.dim()
    candidate_names = {
        1: [("N",), ("C",), ("L",), (None,)],
        2: [("N", "C"), ("H", "W"), ("L", "C"), (None, None)],
        3: [("N", "C", "L"), ("C", "H", "W"), ("D", "H", "W"), (None, None, None)],
        4: [("N", "C", "H", "W"), ("C", "D", "H", "W"), (None, None, None, None)],
        5: [("N", "C", "D", "H", "W"), (None, None, None, None, None)],
    }
    names = fdp.PickValueInList(candidate_names[rank])
    return t.refine_names(*names), names


def _build_tensor_list(fdp, rank, dtype):
    n_tensors = fdp.ConsumeIntInRange(1, 5)
    base_shape = _shape_for_rank(fdp, rank)

    if rank > 0:
        cat_dim = fdp.ConsumeIntInRange(-rank, rank - 1)
    else:
        cat_dim = 0
    norm_dim = cat_dim % rank if rank > 0 else 0

    tensors = []
    for _ in range(n_tensors):
        shape = list(base_shape)
        mode = fdp.ConsumeIntInRange(0, 4)
        if mode in (0, 1):
            if rank > 0:
                shape[norm_dim] = fdp.ConsumeIntInRange(0, 16)
        elif mode == 2 and rank > 0 and fdp.ConsumeBool():
            for i in range(rank):
                if i != norm_dim:
                    shape[i] = base_shape[i]
                else:
                    shape[i] = fdp.ConsumeIntInRange(0, 16)
        elif mode == 3 and rank == 1 and fdp.ConsumeBool():
            shape = [0]
        elif mode == 4 and rank > 0 and fdp.ConsumeBool():
            shape = list(base_shape)
        tensors.append(_make_tensor_from_shape(fdp, shape, dtype))
    return tensors, cat_dim


def _expected_cat_shape(tensors, dim):
    if not tensors:
        return None
    rank = tensors[0].dim()
    nd = dim % rank
    out_shape = list(tensors[0].shape)
    total = 0
    for t in tensors:
        total += t.shape[nd]
    out_shape[nd] = total
    return out_shape


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        rank = fdp.ConsumeIntInRange(1, 5)
        dtype = _pick_dtype(fdp)
        tensors, dim = _build_tensor_list(fdp, rank, dtype)

        mode = fdp.ConsumeIntInRange(0, 5)

        if mode == 0:
            result = torch.cat(tensors, dim)
            _ = result.shape

        elif mode == 1:
            result = torch.cat(tensors=tensors, dim=dim)
            _ = result.numel()

        elif mode == 2:
            expected_shape = _expected_cat_shape(tensors, dim)
            if expected_shape is None:
                return
            if fdp.ConsumeBool():
                out_shape = list(expected_shape)
            else:
                out_shape = _shape_for_rank(fdp, rank)
            out = _make_tensor_from_shape(fdp, out_shape, dtype)
            result = torch.cat(tensors, dim=dim, out=out)
            _ = result.stride()

        elif mode == 3:
            expected_shape = _expected_cat_shape(tensors, dim)
            if expected_shape is None:
                return
            if fdp.ConsumeBool():
                out_shape = list(expected_shape)
            else:
                out_shape = _shape_for_rank(fdp, rank)
            out = _make_tensor_from_shape(fdp, out_shape, dtype)
            result = torch.cat(tensors=tensors, dim=dim, out=out)
            _ = result.storage_offset()

        else:
            named_tensors = []
            names_template = None
            for t in tensors:
                nt, names = _make_named_tensor(t, fdp)
                if names_template is None or fdp.ConsumeBool():
                    names_template = names
                if names_template is not None and len(names_template) == nt.dim():
                    nt = nt.rename(*names_template)
                named_tensors.append(nt)

            valid_named_dims = []
            if names_template is not None:
                for n in names_template:
                    if n is not None:
                        valid_named_dims.append(n)
            if valid_named_dims and fdp.ConsumeBool():
                named_dim = fdp.PickValueInList(valid_named_dims)
            else:
                named_dim = fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 4))

            if mode == 4:
                result = torch.cat(named_tensors, named_dim)
                _ = result.shape
            else:
                expected_shape = _expected_cat_shape(named_tensors, named_tensors[0].names.index(named_dim) if named_dim in named_tensors[0].names else 0)
                if expected_shape is None:
                    return
                if fdp.ConsumeBool():
                    out_shape = list(expected_shape)
                else:
                    out_shape = _shape_for_rank(fdp, rank)
                out = _make_tensor_from_shape(fdp, out_shape, dtype)
                result = torch.cat(named_tensors, named_dim, out=out)
                _ = result.numel()

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
