# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.functional.adaptive_max_pool2d
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.nn.functional.adaptive_max_pool2d.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn.functional as F


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _consume_dim_size(fdp, allow_zero=False):
    if allow_zero and fdp.ConsumeBool():
        return 0
    return fdp.ConsumeIntInRange(1, 8)


def _consume_shape_3d_or_4d(fdp):
    rank = 3 if fdp.ConsumeBool() else 4
    n = _consume_dim_size(fdp)
    c = _consume_dim_size(fdp)
    if rank == 3:
        l = _consume_dim_size(fdp)
        return (n, c, l)
    h = _consume_dim_size(fdp)
    w = _consume_dim_size(fdp)
    return (n, c, h, w)


def _numel(shape):
    total = 1
    for s in shape:
        total *= s
    return total


def _make_tensor(fdp, shape, dtype):
    total = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 4)
    if total == 0:
        return torch.empty(shape, dtype=dtype)

    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 1:
        vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 2:
        vals = [float(x) for x in fdp.ConsumeIntListInRange(total, -16, 16)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 3:
        base = torch.arange(total, dtype=dtype).reshape(shape)
        if fdp.ConsumeBool():
            base = -base
        if fdp.ConsumeBool():
            base = base + fdp.ConsumeFloatInRange(-3.0, 3.0)
        return base
    fill = fdp.ConsumeFloatInRange(-5.0, 5.0)
    return torch.full(shape, fill, dtype=dtype)


def _consume_output_size(fdp, input_shape):
    if len(input_shape) == 3:
        in_h = input_shape[-1]
        in_w = input_shape[-1]
    else:
        in_h = input_shape[-2]
        in_w = input_shape[-1]

    mode = fdp.ConsumeIntInRange(0, 6)
    small_h = max(1, min(in_h, 8))
    small_w = max(1, min(in_w, 8))

    if mode == 0:
        v = fdp.ConsumeIntInRange(1, max(1, min(min(in_h, in_w), 8)))
        return v
    if mode == 1:
        return (
            fdp.ConsumeIntInRange(1, small_h),
            fdp.ConsumeIntInRange(1, small_w),
        )
    if mode == 2:
        v = fdp.PickValueInList([1, 2, 3])
        return (v, v)
    if mode == 3:
        return fdp.PickValueInList([1, 2, 3])
    if mode == 4:
        return (1, 1)
    if mode == 5:
        return (small_h, small_w)
    return (
        fdp.ConsumeIntInRange(1, 8),
        fdp.ConsumeIntInRange(1, 8),
    )


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        shape = _consume_shape_3d_or_4d(fdp)
        dtype = _pick_dtype(fdp)
        x = _make_tensor(fdp, shape, dtype)
        output_size = _consume_output_size(fdp, shape)
        return_indices = fdp.ConsumeBool()

        if fdp.ConsumeBool():
            F.adaptive_max_pool2d(
                x,
                output_size,
                return_indices=return_indices,
            )
        else:
            if return_indices:
                F.adaptive_max_pool2d(
                    input=x,
                    output_size=output_size,
                    return_indices=return_indices,
                )
            else:
                F.adaptive_max_pool2d(
                    input=x,
                    output_size=output_size,
                )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
