# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.prune.random_structured
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.prune.random_structured.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn as nn
import torch.nn.utils.prune as prune


def _pick_dtype_for_weights(fdp):
    return fdp.PickValueInList([
        torch.float32,
        torch.float64,
        torch.float16,
        torch.bfloat16,
    ])


def _small_dim_size(fdp, min_v=1, max_v=8):
    return fdp.ConsumeIntInRange(min_v, max_v)


def _make_param(shape, dtype, fdp):
    numel = 1
    for s in shape:
        numel *= s
    vals = fdp.ConsumeFloatListInRange(numel, -10.0, 10.0)
    t = torch.tensor(vals, dtype=torch.float32).reshape(shape)
    if dtype != torch.float32:
        t = t.to(dtype=dtype)
    return nn.Parameter(t)


def _build_module(fdp):
    rank = fdp.PickValueInList([2, 3, 4, 5])

    if rank == 2:
        n = _small_dim_size(fdp, 1, 8)
        c = _small_dim_size(fdp, 1, 16)
        shape = (n, c)
    elif rank == 3:
        n = _small_dim_size(fdp, 1, 8)
        c = _small_dim_size(fdp, 1, 16)
        l = _small_dim_size(fdp, 1, 16)
        shape = (n, c, l)
    elif rank == 4:
        n = _small_dim_size(fdp, 1, 8)
        c = _small_dim_size(fdp, 1, 16)
        h = _small_dim_size(fdp, 1, 16)
        w = _small_dim_size(fdp, 1, 16)
        shape = (n, c, h, w)
    else:
        n = _small_dim_size(fdp, 1, 6)
        c = _small_dim_size(fdp, 1, 12)
        d = _small_dim_size(fdp, 1, 8)
        h = _small_dim_size(fdp, 1, 8)
        w = _small_dim_size(fdp, 1, 8)
        shape = (n, c, d, h, w)

    dtype = _pick_dtype_for_weights(fdp)

    class FuzzModule(nn.Module):
        def __init__(self, tensor_shape, tensor_dtype, provider):
            super().__init__()
            self.weight = _make_param(tensor_shape, tensor_dtype, provider)
            if provider.ConsumeBool():
                self.bias = _make_param((tensor_shape[0],), tensor_dtype, provider)

    return FuzzModule(shape, dtype, fdp), shape


def _pick_amount(fdp, channels):
    mode = fdp.ConsumeIntInRange(0, 4)
    if mode == 0:
        return 0
    if mode == 1:
        return fdp.ConsumeIntInRange(0, max(0, channels))
    if mode == 2:
        return fdp.ConsumeProbability()
    if mode == 3:
        return fdp.ConsumeFloatInRange(0.0, 1.0)
    return fdp.PickValueInList([0, 1, max(0, channels // 2), max(0, channels)])


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        module, shape = _build_module(fdp)
        name = fdp.PickValueInList(["weight", "bias", "nonexistent", ""])
        if fdp.ConsumeBool():
            dim = fdp.ConsumeIntInRange(-len(shape), len(shape) - 1)
        else:
            dim = fdp.ConsumeIntInRange(-len(shape) - 3, len(shape) + 3)

        if -len(shape) <= dim < len(shape):
            effective_dim = dim if dim >= 0 else len(shape) + dim
            channels = shape[effective_dim]
        else:
            channels = 0

        amount = _pick_amount(fdp, channels)

        if fdp.ConsumeBool():
            prune.random_structured(module, name, amount, dim)
        else:
            prune.random_structured(module=module, name=name, amount=amount, dim=dim)

        if hasattr(module, name + "_mask"):
            _ = getattr(module, name + "_mask")
        if hasattr(module, name + "_orig"):
            _ = getattr(module, name + "_orig")
        if hasattr(module, name):
            param = getattr(module, name)
            if isinstance(param, torch.Tensor) and param.ndim > 0 and fdp.ConsumeBool():
                _ = torch.sum(param, dim=fdp.ConsumeIntInRange(-param.ndim, param.ndim - 1))

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
