# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.set_printoptions
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.set_printoptions.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _consume_optional_int(fdp, min_v, max_v):
    if fdp.ConsumeBool():
        return None
    return fdp.ConsumeIntInRange(min_v, max_v)


def _consume_optional_bool(fdp):
    choice = fdp.ConsumeIntInRange(0, 2)
    if choice == 0:
        return None
    if choice == 1:
        return False
    return True


def _consume_profile(fdp):
    profiles = [None, "default", "short", "full", "", "DEFAULT", "invalid"]
    return fdp.PickValueInList(profiles)


def _make_tensor(fdp):
    dtypes = [
        torch.float32,
        torch.float64,
        torch.int32,
        torch.int64,
        torch.bool,
    ]
    dtype = fdp.PickValueInList(dtypes)
    rank = fdp.ConsumeIntInRange(0, 3)
    shape = [fdp.ConsumeIntInRange(0, 4) for _ in range(rank)]

    numel = 1
    for s in shape:
        numel *= s

    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    elif dtype in (torch.int32, torch.int64):
        vals = [fdp.ConsumeIntInRange(-20, 20) for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    else:
        vals = [fdp.ConsumeFloatInRange(-1e4, 1e4) for _ in range(numel)]
        return torch.tensor(vals, dtype=dtype).reshape(shape)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        precision = _consume_optional_int(fdp, -5, 32)
        threshold = _consume_optional_int(fdp, -10, 5000)
        edgeitems = _consume_optional_int(fdp, -5, 32)
        linewidth = _consume_optional_int(fdp, -10, 500)
        profile = _consume_profile(fdp)
        sci_mode = _consume_optional_bool(fdp)

        call_mode = fdp.ConsumeIntInRange(0, 4)

        if call_mode == 0:
            torch.set_printoptions()
        elif call_mode == 1:
            torch.set_printoptions(
                precision=precision,
                threshold=threshold,
                edgeitems=edgeitems,
                linewidth=linewidth,
                profile=profile,
                sci_mode=sci_mode,
            )
        elif call_mode == 2:
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["precision"] = precision
            if fdp.ConsumeBool():
                kwargs["threshold"] = threshold
            if fdp.ConsumeBool():
                kwargs["edgeitems"] = edgeitems
            if fdp.ConsumeBool():
                kwargs["linewidth"] = linewidth
            if fdp.ConsumeBool():
                kwargs["profile"] = profile
            if fdp.ConsumeBool():
                kwargs["sci_mode"] = sci_mode
            torch.set_printoptions(**kwargs)
        elif call_mode == 3:
            torch.set_printoptions(profile=profile)
            torch.set_printoptions(
                precision=precision,
                threshold=threshold,
                edgeitems=edgeitems,
                linewidth=linewidth,
                sci_mode=sci_mode,
            )
        else:
            torch.set_printoptions(
                precision=precision,
                threshold=threshold,
                edgeitems=edgeitems,
                linewidth=linewidth,
                profile=profile,
                sci_mode=sci_mode,
            )
            t = _make_tensor(fdp)
            repr(t)
            str(t)

        if fdp.ConsumeBool():
            t2 = _make_tensor(fdp)
            repr(t2)
            str(t2)

        torch.set_printoptions(profile="default")

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
