# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.masked_select
# source_yaml_count=2
# source_api_txt=/root/api_txt/torch.masked_select.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _choose_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _gen_shape(fdp):
    rank = fdp.PickValueInList([1, 2, 3, 4, 5])
    yaml_ranges = {
        "N": (0, 8),
        "C": (0, 64),
        "L": (0, 128),
        "H": (0, 128),
        "W": (0, 128),
        "D": (0, 128),
    }
    keys_by_rank = {
        1: ["N"],
        2: ["N", "C"],
        3: ["N", "C", "L"],
        4: ["N", "C", "H", "W"],
        5: ["N", "C", "D", "H", "W"],
    }
    shape = []
    for k in keys_by_rank[rank]:
        lo, hi = yaml_ranges[k]
        if fdp.ConsumeBool():
            dim = fdp.ConsumeIntInRange(lo, min(hi, 4))
        else:
            dim = fdp.ConsumeIntInRange(lo, min(hi, 8))
        shape.append(dim)
    return tuple(shape)


def _numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n


def _make_numeric_tensor(fdp, shape, dtype):
    total = _numel(shape)
    mode = fdp.ConsumeIntInRange(0, 4)

    if total == 0:
        return torch.empty(shape, dtype=dtype)

    if mode == 0:
        vals = fdp.ConsumeRegularFloatList(total)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 1:
        vals = fdp.ConsumeFloatListInRange(total, -10.0, 10.0)
        return torch.tensor(vals, dtype=dtype).reshape(shape)
    if mode == 2:
        base = torch.zeros(shape, dtype=dtype)
        if total > 0:
            idx = fdp.ConsumeIntInRange(0, total - 1)
            flat = base.reshape(-1)
            flat[idx] = fdp.ConsumeFloatInRange(-1000.0, 1000.0)
        return base
    if mode == 3:
        vals = []
        for _ in range(total):
            vals.append(float(fdp.ConsumeIntInRange(-5, 5)))
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    start = fdp.ConsumeFloatInRange(-5.0, 5.0)
    step = fdp.ConsumeFloatInRange(-3.0, 3.0)
    if step == 0.0:
        step = 1.0
    vals = [start + i * step for i in range(total)]
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _broadcast_shape(base_shape, fdp):
    if len(base_shape) == 0:
        return ()

    mode = fdp.ConsumeIntInRange(0, 5)
    rank = len(base_shape)

    if mode == 0:
        return tuple(base_shape)

    if mode == 1:
        return tuple(1 if fdp.ConsumeBool() else d for d in base_shape)

    if mode == 2:
        new_rank = fdp.ConsumeIntInRange(1, rank)
        tail = list(base_shape[-new_rank:])
        out = []
        for d in tail:
            out.append(1 if fdp.ConsumeBool() else d)
        return tuple(out)

    if mode == 3:
        extra = fdp.ConsumeIntInRange(1, 2)
        out = [1] * extra
        for d in base_shape:
            out.append(1 if fdp.ConsumeBool() else d)
        return tuple(out)

    if mode == 4:
        out = []
        for d in base_shape:
            if d == 0:
                out.append(0)
            else:
                out.append(1 if fdp.ConsumeBool() else d)
        return tuple(out)

    return tuple(1 for _ in base_shape)


def _make_mask_tensor(fdp, mask_shape, input_tensor):
    total = _numel(mask_shape)
    mode = fdp.ConsumeIntInRange(0, 4)

    if total == 0:
        return torch.empty(mask_shape, dtype=torch.bool)

    if mode == 0:
        probs = fdp.ConsumeProbabilityList(total)
        threshold = fdp.ConsumeProbability()
        vals = [p > threshold for p in probs]
        return torch.tensor(vals, dtype=torch.bool).reshape(mask_shape)

    if mode == 1:
        return torch.zeros(mask_shape, dtype=torch.bool)

    if mode == 2:
        return torch.ones(mask_shape, dtype=torch.bool)

    if mode == 3:
        try:
            comp = fdp.PickValueInList(["gt", "ge", "lt", "le", "eq", "ne"])
            scalar = fdp.ConsumeFloatInRange(-10.0, 10.0)
            if comp == "gt":
                return torch.gt(input_tensor, scalar)
            if comp == "ge":
                return torch.ge(input_tensor, scalar)
            if comp == "lt":
                return torch.lt(input_tensor, scalar)
            if comp == "le":
                return torch.le(input_tensor, scalar)
            if comp == "eq":
                return torch.eq(input_tensor, scalar)
            return torch.ne(input_tensor, scalar)
        except Exception:
            pass

    vals = []
    for _ in range(total):
        vals.append(fdp.ConsumeBool())
    return torch.tensor(vals, dtype=torch.bool).reshape(mask_shape)


def _make_out_tensor(fdp, input_dtype):
    out_len = fdp.ConsumeIntInRange(0, 32)
    out_dtype = input_dtype if fdp.ConsumeBool() else fdp.PickValueInList([torch.float32, torch.float64])
    mode = fdp.ConsumeIntInRange(0, 3)

    if mode == 0:
        return torch.empty((out_len,), dtype=out_dtype)
    if mode == 1:
        return torch.zeros((out_len,), dtype=out_dtype)
    if mode == 2:
        vals = [float(fdp.ConsumeIntInRange(-3, 3)) for _ in range(out_len)]
        return torch.tensor(vals, dtype=out_dtype)
    return torch.full((out_len,), fdp.ConsumeFloatInRange(-2.0, 2.0), dtype=out_dtype)


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _choose_dtype(fdp)
        shape = _gen_shape(fdp)
        inp = _make_numeric_tensor(fdp, shape, dtype)

        mask_shape = _broadcast_shape(shape, fdp)
        mask = _make_mask_tensor(fdp, mask_shape, inp)

        if fdp.ConsumeBool():
            result = torch.masked_select(inp, mask)
        else:
            out = _make_out_tensor(fdp, dtype)
            if fdp.ConsumeBool():
                result = torch.masked_select(inp, mask, out=out)
            else:
                result = torch.masked_select(input=inp, mask=mask, out=out)

        if isinstance(result, torch.Tensor) and result.numel() > 0 and fdp.ConsumeBool():
            _ = result.reshape(-1)[: fdp.ConsumeIntInRange(0, min(result.numel(), 8))]
    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
