# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.lobpcg
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.lobpcg.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch


def _make_spd_matrix(fdp, batch_shape, m, dtype):
    total = 1
    for d in batch_shape:
        total *= d
    total *= m * m
    vals = fdp.ConsumeFloatListInRange(total, -2.0, 2.0)
    t = torch.tensor(vals, dtype=dtype)
    mat = t.reshape(tuple(batch_shape) + (m, m))
    sym = (mat + mat.transpose(-1, -2)) / 2
    eye = torch.eye(m, dtype=dtype)
    if batch_shape:
        eye = eye.reshape((1,) * len(batch_shape) + (m, m)).expand(tuple(batch_shape) + (m, m))
    shift = fdp.ConsumeFloatInRange(0.1, 5.0)
    return sym.matmul(sym.transpose(-1, -2)) + shift * eye


def _make_dense_tensor(fdp, shape, dtype, low=-2.0, high=2.0):
    total = 1
    for d in shape:
        total *= d
    vals = fdp.ConsumeFloatListInRange(total, low, high)
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _maybe_none(fdp, value):
    if fdp.ConsumeBool():
        return None
    return value


def _make_tracker(stop_early):
    def tracker(state):
        if stop_early:
            istep = state.ivars.get("istep", 0)
            if istep >= 1:
                state.bvars["force_stop"] = True
    return tracker


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = fdp.PickValueInList([torch.float32, torch.float64])
        rank = fdp.PickValueInList([2, 3, 4])

        if rank == 2:
            batch_shape = ()
        elif rank == 3:
            batch_shape = (fdp.ConsumeIntInRange(1, 3),)
        else:
            batch_shape = (fdp.ConsumeIntInRange(1, 2), fdp.ConsumeIntInRange(1, 2))

        m = fdp.ConsumeIntInRange(1, 8)

        if fdp.ConsumeBool():
            k = None
        else:
            k = fdp.ConsumeIntInRange(-1, min(8, max(1, m + 2)))

        x_cols = fdp.ConsumeIntInRange(1, max(1, m))
        if fdp.ConsumeBool():
            x_cols = min(m, max(1, x_cols))
        x_shape = tuple(batch_shape) + (m, x_cols)

        A = _make_spd_matrix(fdp, batch_shape, m, dtype)

        B = None
        if fdp.ConsumeBool():
            if fdp.ConsumeBool():
                B = _make_spd_matrix(fdp, batch_shape, m, dtype)
            else:
                eye = torch.eye(m, dtype=dtype)
                if batch_shape:
                    eye = eye.reshape((1,) * len(batch_shape) + (m, m)).expand(tuple(batch_shape) + (m, m)).clone()
                B = eye

        X = None
        if fdp.ConsumeBool():
            X = _make_dense_tensor(fdp, x_shape, dtype, -1.0, 1.0)

        if X is None:
            if fdp.ConsumeBool():
                n = None
            else:
                n = fdp.ConsumeIntInRange(-1, min(8, max(1, m + 2)))
        else:
            if fdp.ConsumeBool():
                n = None
            else:
                n = fdp.ConsumeIntInRange(-1, min(8, max(1, m + 2)))

        iK = None
        if fdp.ConsumeBool():
            if fdp.ConsumeBool():
                iK = _make_spd_matrix(fdp, batch_shape, m, dtype)
            else:
                eye = torch.eye(m, dtype=dtype)
                if batch_shape:
                    eye = eye.reshape((1,) * len(batch_shape) + (m, m)).expand(tuple(batch_shape) + (m, m)).clone()
                iK = eye

        if fdp.ConsumeBool():
            niter = None
        else:
            niter = fdp.ConsumeIntInRange(-1, 8)

        if fdp.ConsumeBool():
            tol = None
        else:
            tol = fdp.ConsumeFloatInRange(-1.0, 1.0)

        largest = None if fdp.ConsumeBool() else fdp.ConsumeBool()
        method = fdp.PickValueInList([None, "ortho", "basic", "", "invalid"])

        tracker = None
        if fdp.ConsumeBool():
            tracker = _make_tracker(fdp.ConsumeBool())

        ortho_iparams = None
        ortho_fparams = None
        ortho_bparams = None

        if fdp.ConsumeBool():
            ortho_iparams = {}
            possible_i = ["m", "n", "k", "niter", "ortho_i_max", "ortho_j_max"]
            for _ in range(fdp.ConsumeIntInRange(0, 4)):
                ortho_iparams[fdp.PickValueInList(possible_i)] = fdp.ConsumeIntInRange(-1, 8)

        if fdp.ConsumeBool():
            ortho_fparams = {}
            possible_f = ["tol", "ortho_tol", "restartControl", "ortho_tol_drop"]
            for _ in range(fdp.ConsumeIntInRange(0, 4)):
                ortho_fparams[fdp.PickValueInList(possible_f)] = fdp.ConsumeFloatInRange(-1.0, 1.0)

        if fdp.ConsumeBool():
            ortho_bparams = {}
            possible_b = ["verbose", "retLambdaHistory", "retResidualNormsHistory"]
            for _ in range(fdp.ConsumeIntInRange(0, 3)):
                ortho_bparams[fdp.PickValueInList(possible_b)] = fdp.ConsumeBool()

        call_style = fdp.ConsumeIntInRange(0, 2)
        if call_style == 0:
            torch.lobpcg(
                A,
                k=k,
                B=B,
                X=X,
                n=n,
                iK=iK,
                niter=niter,
                tol=tol,
                largest=largest,
                method=method,
                tracker=tracker,
                ortho_iparams=ortho_iparams,
                ortho_fparams=ortho_fparams,
                ortho_bparams=ortho_bparams,
            )
        elif call_style == 1:
            torch.lobpcg(
                A,
                k,
                B,
                X,
                n,
                iK,
                niter,
                tol,
                largest,
                method,
                tracker,
                ortho_iparams,
                ortho_fparams,
                ortho_bparams,
            )
        else:
            kwargs = {}
            if fdp.ConsumeBool():
                kwargs["k"] = k
            if fdp.ConsumeBool():
                kwargs["B"] = B
            if fdp.ConsumeBool():
                kwargs["X"] = X
            if fdp.ConsumeBool():
                kwargs["n"] = n
            if fdp.ConsumeBool():
                kwargs["iK"] = iK
            if fdp.ConsumeBool():
                kwargs["niter"] = niter
            if fdp.ConsumeBool():
                kwargs["tol"] = tol
            if fdp.ConsumeBool():
                kwargs["largest"] = largest
            if fdp.ConsumeBool():
                kwargs["method"] = method
            if fdp.ConsumeBool():
                kwargs["tracker"] = tracker
            if fdp.ConsumeBool():
                kwargs["ortho_iparams"] = ortho_iparams
            if fdp.ConsumeBool():
                kwargs["ortho_fparams"] = ortho_fparams
            if fdp.ConsumeBool():
                kwargs["ortho_bparams"] = ortho_bparams
            torch.lobpcg(A, **kwargs)

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
