# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.utils.prune.l1_unstructured
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.utils.prune.l1_unstructured.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import torch
import torch.nn as nn
import torch.nn.utils.prune as prune


def _pick_shape_by_rank(fdp, rank):
    if rank == 2:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 64),
        ]
    if rank == 3:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 64),
            fdp.ConsumeIntInRange(1, 16),
        ]
    if rank == 4:
        return [
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 16),
            fdp.ConsumeIntInRange(1, 8),
            fdp.ConsumeIntInRange(1, 8),
        ]
    return [
        fdp.ConsumeIntInRange(1, 4),
        fdp.ConsumeIntInRange(1, 8),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
        fdp.ConsumeIntInRange(1, 6),
    ]


def _numel(shape):
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _make_tensor(fdp, shape, dtype):
    count = _numel(shape)
    if dtype.is_floating_point:
        vals = fdp.ConsumeFloatListInRange(count, -10.0, 10.0)
        t = torch.tensor(vals, dtype=dtype)
    else:
        vals = fdp.ConsumeIntListInRange(count, -50, 50)
        t = torch.tensor(vals, dtype=dtype)
    return t.reshape(shape)


def _make_module_and_name(fdp):
    module_kind = fdp.PickValueInList(["linear", "conv2d", "conv3d", "custom"])
    floating_dtypes = [torch.float16, torch.float32, torch.float64]
    dtype = fdp.PickValueInList(floating_dtypes)

    if module_kind == "linear":
        out_features = fdp.ConsumeIntInRange(1, 16)
        in_features = fdp.ConsumeIntInRange(1, 16)
        bias = fdp.ConsumeBool()
        module = nn.Linear(in_features, out_features, bias=bias, dtype=dtype)
        name = fdp.PickValueInList(["weight", "bias" if bias else "weight"])
        if name == "bias" and not bias:
            name = "weight"
        return module, name

    if module_kind == "conv2d":
        in_channels = fdp.ConsumeIntInRange(1, 8)
        out_channels = fdp.ConsumeIntInRange(1, 8)
        kh = fdp.ConsumeIntInRange(1, 5)
        kw = fdp.ConsumeIntInRange(1, 5)
        groups_candidates = [g for g in range(1, in_channels + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_candidates)
        bias = fdp.ConsumeBool()
        module = nn.Conv2d(
            in_channels,
            out_channels,
            kernel_size=(kh, kw),
            groups=groups,
            bias=bias,
            dtype=dtype,
        )
        name = fdp.PickValueInList(["weight", "bias" if bias else "weight"])
        if name == "bias" and not bias:
            name = "weight"
        return module, name

    if module_kind == "conv3d":
        in_channels = fdp.ConsumeIntInRange(1, 6)
        out_channels = fdp.ConsumeIntInRange(1, 6)
        kd = fdp.ConsumeIntInRange(1, 3)
        kh = fdp.ConsumeIntInRange(1, 3)
        kw = fdp.ConsumeIntInRange(1, 3)
        groups_candidates = [g for g in range(1, in_channels + 1) if in_channels % g == 0 and out_channels % g == 0]
        groups = fdp.PickValueInList(groups_candidates)
        bias = fdp.ConsumeBool()
        module = nn.Conv3d(
            in_channels,
            out_channels,
            kernel_size=(kd, kh, kw),
            groups=groups,
            bias=bias,
            dtype=dtype,
        )
        name = fdp.PickValueInList(["weight", "bias" if bias else "weight"])
        if name == "bias" and not bias:
            name = "weight"
        return module, name

    class CustomModule(nn.Module):
        def __init__(self, param_shape, with_extra_param, dtype_):
            super().__init__()
            self.weight = nn.Parameter(torch.zeros(param_shape, dtype=dtype_))
            if with_extra_param:
                extra_shape = [max(1, param_shape[0])]
                self.other = nn.Parameter(torch.ones(extra_shape, dtype=dtype_))

    rank = fdp.PickValueInList([2, 3, 4, 5])
    shape = _pick_shape_by_rank(fdp, rank)
    with_extra = fdp.ConsumeBool()
    module = CustomModule(shape, with_extra, dtype)
    name = fdp.PickValueInList(["weight", "other" if with_extra else "weight"])
    if name == "other" and not with_extra:
        name = "weight"
    return module, name


def _choose_amount(fdp, total_params):
    mode = fdp.PickValueInList(["float", "int", "boundary"])
    if mode == "float":
        return fdp.ConsumeProbability()
    if mode == "int":
        return fdp.ConsumeIntInRange(0, total_params)
    return fdp.PickValueInList([0, total_params, min(1, total_params), 0.5])


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        module, name = _make_module_and_name(fdp)
        param = getattr(module, name)
        param_shape = list(param.shape)
        total_params = param.numel()

        amount = _choose_amount(fdp, total_params)

        use_importance = fdp.ConsumeBool()
        importance_scores = None
        if use_importance:
            if fdp.ConsumeBool():
                imp_shape = param_shape
            else:
                rank = len(param_shape)
                if rank in (2, 3, 4, 5):
                    imp_shape = _pick_shape_by_rank(fdp, rank)
                else:
                    imp_shape = param_shape

            imp_dtype = fdp.PickValueInList(
                [torch.float16, torch.float32, torch.float64, torch.int32, torch.int64]
            )
            importance_scores = _make_tensor(fdp, imp_shape, imp_dtype)
            if fdp.ConsumeBool():
                importance_scores = importance_scores.to(param.device)
            if fdp.ConsumeBool():
                importance_scores = importance_scores.contiguous()

        if fdp.ConsumeBool():
            prune.l1_unstructured(module, name, amount, importance_scores=importance_scores)
        else:
            prune.l1_unstructured(
                module=module,
                name=name,
                amount=amount,
                importance_scores=importance_scores,
            )

        if fdp.ConsumeBool():
            _ = module.state_dict()

        if fdp.ConsumeBool():
            sample_shape = [fdp.ConsumeIntInRange(1, 4) for _ in range(max(1, len(param_shape)))]
            x = torch.zeros(sample_shape, dtype=param.dtype)
            try:
                module(x)
            except Exception:
                pass

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
