# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.nn.init.orthogonal_
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.nn.init.orthogonal_.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import math
import torch


def _pick_dtype(fdp):
    return fdp.PickValueInList([torch.float32, torch.float64])


def _bounded_dim(fdp, low, high, allow_zero=False):
    if allow_zero and fdp.ConsumeBool():
        return 0
    return fdp.ConsumeIntInRange(low, high)


def _make_shape(fdp):
    rank_mode = fdp.PickValueInList([2, 3, 4, 5, 6, 1])
    if rank_mode == 1:
        rank = fdp.ConsumeIntInRange(2, 6)
    else:
        rank = rank_mode

    shape = []
    for i in range(rank):
        if i < 2:
            shape.append(_bounded_dim(fdp, 1, 8, allow_zero=False))
        else:
            shape.append(_bounded_dim(fdp, 1, 6, allow_zero=fdp.ConsumeBool()))
    if fdp.ConsumeBool():
        idx = fdp.ConsumeIntInRange(0, rank - 1)
        shape[idx] = 1
    return tuple(shape)


def _numel(shape):
    n = 1
    for s in shape:
        n *= s
    return n


def _make_tensor(fdp, dtype):
    shape = _make_shape(fdp)
    numel = _numel(shape)

    strategy = fdp.PickValueInList(["empty", "zeros", "ones", "full", "randn", "arange"])

    if strategy == "empty":
        return torch.empty(shape, dtype=dtype)
    if strategy == "zeros":
        return torch.zeros(shape, dtype=dtype)
    if strategy == "ones":
        return torch.ones(shape, dtype=dtype)
    if strategy == "full":
        val = fdp.ConsumeFloatInRange(-3.0, 3.0)
        return torch.full(shape, val, dtype=dtype)
    if strategy == "arange":
        if numel == 0:
            return torch.empty(shape, dtype=dtype)
        base = torch.arange(numel, dtype=dtype)
        if fdp.ConsumeBool():
            base = -base
        if fdp.ConsumeBool():
            base = base * fdp.ConsumeFloatInRange(-2.0, 2.0)
        return base.reshape(shape)

    seed = fdp.ConsumeUInt(8)
    g = torch.Generator()
    g.manual_seed(seed)
    return torch.randn(shape, dtype=dtype, generator=g)


def _make_gain(fdp):
    if fdp.ConsumeBool():
        gain = fdp.ConsumeFloatInRange(-1.0, 1.0)
    else:
        gain = fdp.PickValueInList([
            -2.0, -1.0, -0.5, 0.0, 0.5, 1.0, math.sqrt(2.0), 2.0, 10.0
        ])
    return float(gain)


def _make_generator(fdp):
    if fdp.ConsumeBool():
        return None
    g = torch.Generator()
    g.manual_seed(fdp.ConsumeUInt(8))
    return g


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        dtype = _pick_dtype(fdp)
        tensor = _make_tensor(fdp, dtype)
        gain = _make_gain(fdp)
        generator = _make_generator(fdp)

        call_style = fdp.PickValueInList([0, 1, 2, 3])
        if call_style == 0:
            torch.nn.init.orthogonal_(tensor)
        elif call_style == 1:
            torch.nn.init.orthogonal_(tensor, gain)
        elif call_style == 2:
            torch.nn.init.orthogonal_(tensor, gain=gain)
        else:
            torch.nn.init.orthogonal_(tensor, gain=gain, generator=generator)

        if fdp.ConsumeBool():
            torch.nn.init.orthogonal_(tensor, gain=_make_gain(fdp), generator=_make_generator(fdp))

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
