# Auto-generated by llm_harness_codegen_torch.py
# model=gpt-5.4
# api_mode=responses
# target_api=torch.hub.load
# source_yaml_count=1
# source_api_txt=/root/api_txt/torch.hub.load.txt
# source_atheris_doc=/root/atheris-doc/atheris_readme.txt
# repair_attempts_used=0

import atheris
import sys
import os
import tempfile
import textwrap
import torch


def _make_local_hub_repo(base_dir, variant):
    os.makedirs(base_dir, exist_ok=True)
    hubconf_path = os.path.join(base_dir, "hubconf.py")

    if variant == 0:
        content = textwrap.dedent(
            """
            import torch

            dependencies = []

            def basic_model(*args, **kwargs):
                size = int(kwargs.get("size", 2))
                if size < 0:
                    raise ValueError("negative size")
                t = torch.arange(max(0, size), dtype=torch.float32)
                if kwargs.get("reshape", False):
                    side = int((t.numel()) ** 0.5)
                    if side > 0 and side * side == t.numel():
                        t = t.reshape(side, side)
                if kwargs.get("return_module", False):
                    return torch.nn.ReLU()
                return t

            def tensor_op(x=None, scale=1.0, bias=0.0, **kwargs):
                if x is None:
                    x = torch.zeros((1,), dtype=torch.float32)
                elif not isinstance(x, torch.Tensor):
                    x = torch.tensor(x)
                y = x.to(torch.float32) * float(scale) + float(bias)
                if kwargs.get("relu", False):
                    y = torch.relu(y)
                return y

            def factory(name="linear", in_features=1, out_features=1, **kwargs):
                in_features = max(1, int(in_features))
                out_features = max(1, int(out_features))
                if name == "linear":
                    return torch.nn.Linear(in_features, out_features, bias=bool(kwargs.get("bias", True)))
                if name == "identity":
                    return torch.nn.Identity()
                return {"name": name, "in_features": in_features, "out_features": out_features}
            """
        )
    else:
        content = textwrap.dedent(
            """
            import torch

            dependencies = []

            def alt_entry(*args, **kwargs):
                val = int(kwargs.get("val", 0))
                n = max(0, min(abs(val), 16))
                return torch.ones((n,), dtype=torch.float32)

            def nested(data=None, **kwargs):
                if data is None:
                    data = [1, 2, 3]
                t = torch.tensor(data)
                if kwargs.get("sum", False):
                    return t.sum()
                return {"tensor": t, "shape": tuple(t.shape)}

            def passthrough(*args, **kwargs):
                return {"args": args, "kwargs": kwargs}
            """
        )

    with open(hubconf_path, "w", encoding="utf-8") as f:
        f.write(content)


def _consume_small_string(fdp, max_len=24):
    return fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, max_len))


def _pick_model_name(fdp, variant):
    if variant == 0:
        return fdp.PickValueInList(["basic_model", "tensor_op", "factory", "missing_entry"])
    return fdp.PickValueInList(["alt_entry", "nested", "passthrough", "missing_entry"])


def _make_tensor(fdp):
    dtype = fdp.PickValueInList([torch.float32, torch.float64, torch.int64, torch.int32, torch.bool])
    rank = fdp.ConsumeIntInRange(0, 3)
    shape = [fdp.ConsumeIntInRange(0, 4) for _ in range(rank)]
    numel = 1
    for d in shape:
        numel *= d

    if dtype == torch.bool:
        vals = [fdp.ConsumeBool() for _ in range(numel)]
        if rank == 0:
            return torch.tensor(vals[0] if vals else False, dtype=dtype)
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    if dtype in (torch.int64, torch.int32):
        vals = [fdp.ConsumeIntInRange(-8, 8) for _ in range(numel)]
        if rank == 0:
            return torch.tensor(vals[0] if vals else 0, dtype=dtype)
        return torch.tensor(vals, dtype=dtype).reshape(shape)

    vals = [fdp.ConsumeFloatInRange(-8.0, 8.0) for _ in range(numel)]
    if rank == 0:
        return torch.tensor(vals[0] if vals else 0.0, dtype=dtype)
    return torch.tensor(vals, dtype=dtype).reshape(shape)


def _make_python_value(fdp, depth=0):
    if depth > 2:
        choice = fdp.ConsumeIntInRange(0, 4)
    else:
        choice = fdp.ConsumeIntInRange(0, 7)

    if choice == 0:
        return None
    if choice == 1:
        return fdp.ConsumeBool()
    if choice == 2:
        return fdp.ConsumeIntInRange(-32, 32)
    if choice == 3:
        return fdp.ConsumeFloatInRange(-32.0, 32.0)
    if choice == 4:
        return _consume_small_string(fdp, 20)
    if choice == 5:
        return _make_tensor(fdp)
    if choice == 6:
        n = fdp.ConsumeIntInRange(0, 4)
        return [_make_python_value(fdp, depth + 1) for _ in range(n)]
    n = fdp.ConsumeIntInRange(0, 4)
    out = {}
    for _ in range(n):
        key = _consume_small_string(fdp, 12)
        if not key.isidentifier():
            key = "k" + "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in key)
            if not key.isidentifier():
                key = "k"
        out[key] = _make_python_value(fdp, depth + 1)
    return out


def _make_args_list(fdp):
    n = fdp.ConsumeIntInRange(0, 4)
    return [_make_python_value(fdp) for _ in range(n)]


def _make_kwargs_dict(fdp):
    base_keys = [
        "size", "reshape", "return_module", "scale", "bias", "relu",
        "name", "in_features", "out_features", "val", "sum", "data", "x"
    ]
    kwargs = {}
    total = fdp.ConsumeIntInRange(0, 6)
    for _ in range(total):
        if fdp.ConsumeBool():
            key = fdp.PickValueInList(base_keys)
        else:
            key = _consume_small_string(fdp, 12)
            if not key.isidentifier():
                key = "k" + "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in key)
                if not key.isidentifier():
                    key = "k"
        kwargs[key] = _make_python_value(fdp)
    return kwargs


@atheris.instrument_func
def TestOneInput(data: bytes):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        variant = fdp.ConsumeIntInRange(0, 1)
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = os.path.join(tmpdir, "repo")
            _make_local_hub_repo(repo_dir, variant)

            source = fdp.PickValueInList(["local", "github"])
            repo_or_dir = repo_dir if source == "local" else _consume_small_string(fdp, 32)
            if source == "github" and "/" not in repo_or_dir:
                owner = _consume_small_string(fdp, 8) or "pytorch"
                name = _consume_small_string(fdp, 8) or "vision"
                if fdp.ConsumeBool():
                    ref = _consume_small_string(fdp, 8)
                    repo_or_dir = owner + "/" + name + ((":" + ref) if ref else "")
                else:
                    repo_or_dir = owner + "/" + name

            model = _pick_model_name(fdp, variant)
            args = _make_args_list(fdp)
            kwargs = _make_kwargs_dict(fdp)

            trust_repo = fdp.PickValueInList([None, True, False, "check"])
            force_reload = fdp.ConsumeBool()
            verbose = fdp.ConsumeBool()
            skip_validation = fdp.ConsumeBool()

            call_style = fdp.ConsumeIntInRange(0, 2)
            if call_style == 0:
                torch.hub.load(
                    repo_or_dir,
                    model,
                    *args,
                    source=source,
                    trust_repo=trust_repo,
                    force_reload=force_reload,
                    verbose=verbose,
                    skip_validation=skip_validation,
                    **kwargs
                )
            elif call_style == 1:
                torch.hub.load(
                    repo_or_dir=repo_or_dir,
                    model=model,
                    *args,
                    source=source,
                    trust_repo=trust_repo,
                    force_reload=force_reload,
                    verbose=verbose,
                    skip_validation=skip_validation,
                    **kwargs
                )
            else:
                if fdp.ConsumeBool():
                    kwargs2 = dict(kwargs)
                    kwargs2["verbose"] = verbose
                    torch.hub.load(
                        repo_or_dir,
                        model,
                        *args,
                        source=source,
                        trust_repo=trust_repo,
                        force_reload=force_reload,
                        skip_validation=skip_validation,
                        **kwargs2
                    )
                else:
                    torch.hub.load(
                        repo_or_dir,
                        model,
                        *args,
                        source=source,
                        trust_repo=trust_repo,
                        force_reload=force_reload,
                        verbose=verbose,
                        skip_validation=skip_validation
                    )

    except (
        RuntimeError,
        TypeError,
        ValueError,
        IndexError,
        AssertionError,
        NotImplementedError,
    ):
        return
    except Exception:
        return


atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
